### ISSUE TITLE
Bug Report | No Audio Streams on Firefox 85.0.1

### ISSUE THREAD

**Issue by Mennaruuk** [spikecodes/libreddit#100]
**Describe the bug**
Recently, Libreddit only plays video streams. Audio streams are gone.

**To reproduce**
1. Go to https://www.reddit.com/r/Wellthatsucks/comments/ld0aiy/young_teacher_problems/
2. Check if audio plays
3. Now head to https://libredd.it/r/Wellthatsucks/comments/ld0aiy/young_teacher_problems/
4. Check if audio plays

**Expected behavior**
Videos should play both video and audio streams.

Other examples:
https://libreddit.spike.codes/r/Wellthatsucks/comments/ld8s9j/lamborghini_huracan_gets_a_sudden_weight_reduction/
https://libredd.it/r/funnyvideos/comments/ld35z2/this_compilation_is_awesome/
https://libredd.it/r/aww/comments/ld5xex/dad_didnt_want_a_dog_in_his_house_dad_now/

**Additional context**
Thank you:
![ublock](https://user-images.githubusercontent.com/52135169/107073826-d8dc7480-67b5-11eb-86b6-05dc64b13181.png)

**Comment by spikecodes** [comment]
Thanks for this bug report! Currently, Libreddit doesn't support proxying audio but you can follow the progress of this feature here: #14.

**Comment by spikecodes** [comment]
>  Thank you:
:smile: Awesome!
