### ISSUE TITLE
Feature Request | Syntax highlighting

### ISSUE THREAD

**Issue by curlpipe** [spikecodes/libreddit#102]
**Is your feature request related to a problem? Please describe.**
The Reddit app lacks code syntax highlighting, which is sad. I'm sure it wouldn't be too difficult to add it to libreddit. 

**Describe the solution you'd like**
Be able to detect code blocks in posts, guess the language used and appropriately apply highlighting. 

**Describe alternatives you've considered**
This does seem a bit niche and perhaps a little bit complicated but there are some great syntax highlighting libraries. 

**Additional context**
I own a low level syntax highlighting rust crate called synoptic and would love to write some built in language highlighters for it. it's only large dependency is regex, which is already included with libreddit.

**Comment by spikecodes** [comment]
Thanks! I like this idea!

**Comment by spikecodes** [comment]
I feel the harder challenge would be identifying what programming language is used in different code blocks. Because Reddit doesn't support syntax highlighting, users don't label the language in the code block markdown. Therefore, I think I'll be dropping this idea.
