### ISSUE TITLE
Feature Request | Automatically expand GIFs/Videos

### ISSUE THREAD

**Issue by TheCultLeader666** [spikecodes/libreddit#105]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
An option in the settings for videos and GIFs to automatically shown in the feed, similar to images are.

**Describe alternatives you've considered**
The ability to click on the thumbnail to expand the GIF/Video

**Additional context**
N/A

**Comment by robrobinbin** [comment]
I was actually thinking the exact same thing. @spikecodes you can assign me to this one!

I saw that the HTML `video` tag has an `preload` option which can be set to `none` to prevent the browser from preloading it. This might be desirable for a resource usage perspective.

**Comment by TheCultLeader666** [comment]
Oh wow that was quick
