### ISSUE TITLE
Feature Request | Save Posts

### ISSUE THREAD

**Issue by TheCultLeader666** [spikecodes/libreddit#106]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
An option to save posts, and a feed where all of your saved posts show up

**Describe alternatives you've considered**
I can not think of a different idea, except for manually writing down post links

**Additional context**
N/A

**Comment by spikecodes** [comment]
Thanks, it seems like this has been opened here: #81
