### ISSUE TITLE
Feature Request | Infinite Scroll

### ISSUE THREAD

**Issue by TheCultLeader666** [spikecodes/libreddit#108]
**Is your feature request related to a problem? Please describe.**
I think it's tedious to have to press a small button to load the next page

**Describe the solution you'd like**
An option in the settings to turn on infinite scroll

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by spikecodes** [comment]
I don't think infinite scrolling would be possible without the use of JavaScript but I definitely understand your concern. It may be possible to increase the limit of items per page from 25 to 50 or 100 (the maximum according to the Reddit API).

**Comment by spikecodes** [comment]
Closing this issue.
