### ISSUE TITLE
Feature Request | Caching of resources

### ISSUE THREAD

**Issue by FireMasterK** [spikecodes/libreddit#11]
Helps speed up page load times.

https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Cache-Control

**Comment by spikecodes** [comment]
Thanks for the contribution! Just pushed 0f506fc to fix #33 which caches media.

**Comment by FireMasterK** [comment]
You should cache the css and images aswell :)

**Comment by spikecodes** [comment]
Yeah for sure, not done yet with the caching process, just wanted to update this thread.

**Comment by FireMasterK** [comment]
I see that you've used must-revalidate, but are not handling etags

I'd suggest removing it as it's quite a lot of work and is unnecessary for proxied media

**Comment by spikecodes** [comment]
Yeah good idea, I don't need the client to revalidate as the media wouldn't be changing.

**Comment by spikecodes** [comment]
Forgot to update this but all HTTP requests are now cached since the move to Tide! ebbdd7185f309304ea4bad0ef6ad0496451646fb
