### ISSUE TITLE
Bug Report | Empty author flairs showing

### ISSUE THREAD

**Issue by Mennaruuk** [spikecodes/libreddit#110]
**Describe the bug**
There is a small post flair that shows up on some posts randomly and for no apparent reason. When I go down posts in a subreddit and find a culprit post, this flair is at the start of the title. When I click the post, the flair moves to the end of the title.

**To reproduce**
1. I archived [r/askhistorians](https://web.archive.org/web/20210209051844/https://libreddit.spike.codes/r/AskHistorians/) on Libreddit in case this slips away. Check out the first two unstickied posts.
2. Go to [this](https://libreddit.spike.codes/r/AskHistorians/comments/lfphn2/just_how_different_is_olive_oil_of_the_ancient/) post on r/askhistorians
2. Check for the small post flair

**Expected behavior**
I checked the [Reddit](https://www.reddit.com/r/AskHistorians/comments/lfphn2/just_how_different_is_olive_oil_of_the_ancient/) post, and it didn't seem to have any flair, so theoretically there shouldn't be a flair on Libreddit.

**Additional context**
Here's a comparison screenshot:
![libreddit](https://user-images.githubusercontent.com/52135169/107318948-d6a34000-6a6b-11eb-9600-b4657f851286.jpg)
Also how the flair ends up trailing the title when you click the post:
![atend](https://user-images.githubusercontent.com/52135169/107319110-19fdae80-6a6c-11eb-99e4-a84efdfaf126.jpg)
<br/><br/>
<br/><br/>
(I have one more question: I see there's whitespace after text in the flair. Is this a bug or a feature?)
![image](https://user-images.githubusercontent.com/52135169/107319729-63023280-6a6d-11eb-9572-8a8e1a45bb52.png)

**Comment by spikecodes** [comment]
Thanks for this bug report! I'll assign myself to it

**Comment by spikecodes** [comment]
It appears I inadvertently fixed this in 9cfab348eb06f0e92f297175489838dfdc494bf0!

As you can see, the empty flair no longer shows:
![image](https://user-images.githubusercontent.com/19519553/108644317-64d4e880-74a6-11eb-846b-eabaa69a8452.png)

**Comment by Mennaruuk** [comment]
> It appears I inadvertently fixed this in [9cfab34](https://github.com/spikecodes/libreddit/commit/9cfab348eb06f0e92f297175489838dfdc494bf0)!
> 
> As you can see, the empty flair no longer shows:
> ![image](https://user-images.githubusercontent.com/19519553/108644317-64d4e880-74a6-11eb-846b-eabaa69a8452.png)

It's strange. So it stopped showing on that post. But it still shows up on other posts. I [archived](https://web.archive.org/web/20210222005537/https://libredd.it/r/AskHistorians/) r/AskHistorians again, but these are two examples ([one](https://libredd.it/r/AskHistorians/comments/lov0g9/in_mad_men_the_admen_are_always_depicted_with_a/) and [two](https://libredd.it/r/AskHistorians/comments/lon6u3/when_and_why_did_the_word_overmorrow_fall_out_of/)).

It's not that big of a deal, esp. with other goals in this project. It's just making me squirm: what is causing this!?

**Comment by spikecodes** [comment]
Oh that's really weird! I wonder why it stopped showing on that post but still shows elsewhere. Guess the issue persists! I will get to fixing it.

**Comment by Mennaruuk** [comment]
Thank you @spikecodes, stay awesome!

**Comment by spikecodes** [comment]
I appreciate your enthusiasm! :smile: It movitates me to build Libreddit even better!

Just fixed this issue! Changes will be live shortly.

**Comment by Mennaruuk** [comment]
Of course!! I think you should have a donation button on the page so anyone can help further this project. I wanna donate a few bucks towards making it better.

**Comment by spikecodes** [comment]
Thank you so much! I have no fiat method yet but I just listed Bitcoin and Monero addresses in the [README](https://github.com/spikecodes/libreddit/blob/master/README.md).

**Comment by Mennaruuk** [comment]
I dislike to be a Debbie Downer, but I still see the issue on some comments. Here are examples:
https://libredd.it/r/wallstreetbets/comments/lsc5ji/gme_megathread_part_2_for_thursday_february_25th/goqbg5q/
https://libredd.it/r/wallstreetbets/comments/lsc5ji/gme_megathread_part_2_for_thursday_february_25th/goqb1kz/
https://libredd.it/r/wallstreetbets/comments/lsc5ji/gme_megathread_part_2_for_thursday_february_25th/goqbqtr/
https://libredd.it/r/wallstreetbets/comments/lsc5ji/gme_megathread_part_2_for_thursday_february_25th/goqbmfo/

**Comment by spikecodes** [comment]
his is an author flair so it seems to be a slightly different issue but I'll look into it! I'm reopening this issue and renaming it to refer to both post and author flairs.

**Comment by spikecodes** [comment]
Good news, it was a simple fix! :smiley: 
![image](https://user-images.githubusercontent.com/19519553/109198921-b2976c80-7796-11eb-8f3e-f71b1d3cd6f2.png)

**Comment by Mennaruuk** [comment]
You rock!!!! @spikecodes

**Comment by spikecodes** [comment]
Thank you! @Mennaruuk
