### ISSUE TITLE
Feature Request | Support Short URLs

### ISSUE THREAD

**Issue by Mennaruuk** [spikecodes/libreddit#111]
**Is your feature request related to a problem? Please describe.**
URLs like https://libredd.it/r/uBlockOrigin/comments/lg0koq don't work. On Reddit, they redirect to the respective post (https://www.reddit.com/r/uBlockOrigin/comments/lg0koq/pop_up_overlay_ads_changing_on_every_refresh_how/)

**Describe the solution you'd like**
Have short URLs redirect to their matching long URLs without showing the error "Nothing here."

**Describe alternatives you've considered**
I have to temporarily go to the Reddit counterpart to get the long URL before switching to Libreddit.

**Additional context**
![image](https://user-images.githubusercontent.com/52135169/107405737-a0020f80-6ad5-11eb-804c-bb327fd59735.png)

**Comment by spikecodes** [comment]
Thanks! Just pushed e731cfb to fix this, changes should be live shortly!
