### ISSUE TITLE
Feature Request | Clicking "Save" button in settings should return to previous page

### ISSUE THREAD

**Issue by Mennaruuk** [spikecodes/libreddit#114]
**Is your feature request related to a problem? Please describe.**
A minor problem I face is when I save my settings, it doesn't take me back to the previous screen. I think clicking Save should return to previous page or the homepage.

**Describe the solution you'd like**
Save would do two things: save the settings as well as return to previous screen or homepage.

**Describe alternatives you've considered**
For now, I save settings, then manually click the Back button.

**Additional context**
I also think it'd be pretty handy to have a Reset button just in case. Maybe it isn't necessary at this stage with only a few settings, but if settings were to increase in number, a Reset option would save some headaches.

**Comment by spikecodes** [comment]
I'm not sure if this should be added as both https://www.reddit.com/settings and https://old.reddit.com/prefs keep you on the settings page after you press save.

**Comment by Mennaruuk** [comment]
You're right, I've come over from Nitter where saving preferences takes me back to previous page, but for Reddit users who change their settings, maybe it's better to keep it the same way.

**Comment by spikecodes** [comment]
I appreciate the suggestions anyway, thank you!
