### ISSUE TITLE
Feature Request | Add indication to comments when they've been edited

### ISSUE THREAD

**Issue by robrobinbin** [spikecodes/libreddit#117]
**Is your feature request related to a problem? Please describe.**
Currently, you can't see whether a comment have been edited by it's author. Sometimes this can lead to some confusion.

**Describe the solution you'd like**
Add an asterisk (*) after the timestamp if the comment has been edited.

**Describe alternatives you've considered**
Could also be another indicator, such as "(edited)".

**Additional context**
N/A

**Comment by spikecodes** [comment]
![image](https://user-images.githubusercontent.com/19519553/107891538-2d4ec500-6f17-11eb-8f8b-38b57f42f756.png)
Great suggestion! Let me know if it looks good or needs improvement.

It's styled after the Reddit redesign edit indicator:
![image](https://user-images.githubusercontent.com/19519553/107891563-5cfdcd00-6f17-11eb-89a1-fd5b692b89ca.png)

**Comment by robrobinbin** [comment]
Screenshot looks awesome, thanks a lot @spikecodes !
