### ISSUE TITLE
Feature Request | Follow users

### ISSUE THREAD

**Issue by spikecodes** [spikecodes/libreddit#118]
**Is your feature request related to a problem? Please describe.**
N/A

**Describe the solution you'd like**
A "Follow" button on user profiles to subscribe to a user's feed.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by bnainar** [comment]
Without logging in?

**Comment by spikecodes** [comment]
Thanks! Yeah, that was my initial plan but I hadn't gotten around to it until today. Added in b3e4b7bfaee4ed03abf1229e811c5721d3c1e0d1!

**Comment by bnainar** [comment]
You did this massive commit today. You're a genius. I also need to.learn backend
