### ISSUE TITLE
Feature Request | Multi-architecture docker images

### ISSUE THREAD

**Issue by FireMasterK** [spikecodes/libreddit#12]
You can use GitHub actions for this, see
https://github.com/ytorg/Yotter/blob/dev-indep/.github/workflows/docker-build.yml
and
https://github.com/StuffNoOneCaresAbout/Teddit-Docker/blob/main/.github/workflows/docker-build.yml
for examples.

**Comment by unixfox** [comment]
All the document is available here: https://github.com/docker/build-push-action
