### ISSUE TITLE
Bug Report | Firefox Android - PWA has no icon

### ISSUE THREAD

**Issue by SuperSamus** [spikecodes/libreddit#123]
**Describe the bug**
On Firefox Android (didn't test other browsers), when adding the website to the home page, the icon is not Libreddit's icon but just an L placeholder icon.

**To reproduce**
1. Open libredd.it on [Firefox Android](https://play.google.com/store/apps/details?id=org.mozilla.firefox&hl=en_US&gl=US)
2. Add the website to the home page (three dots > Install)
3. See error

**Expected behavior**
Libreddit's icon

Video showing the issue: https://photos.app.goo.gl/wVjrpdXGRPZCAgd57

**Comment by spikecodes** [comment]
Thanks for reporting this! I've been trying to debug why this happens but I can't figure it out. This issue didn't occur when the PWA feature was first added so I do not know why it exists now.

**Comment by spikecodes** [comment]
[v0.5](https://github.com/spikecodes/libreddit/releases/v0.5.0) appears to have fixed this! I am no longer able to reproduce the issue so I am closing this.

**Comment by SuperSamus** [comment]
I can't reproduce it anymore either. :+1: 
(I had to delete Pixel Launcher's data though because it was making confusion between the old and the new icon. Not Libreddit's fault of course)

**Comment by spikecodes** [comment]
Awesome, thanks for looking!
