### ISSUE TITLE
Feature Request | Filter posts by flair

### ISSUE THREAD

**Issue by spikecodes** [spikecodes/libreddit#124]
Extension of #69.

Users should be able to click on a post flair to filter that subreddit to only show posts which have that flair.

**Comment by spikecodes** [comment]
You can now filter posts by flair! Simply click a flair to see all posts in that subreddit with that flair.

1. Click flair
![image](https://user-images.githubusercontent.com/19519553/108609565-94acbf00-73c6-11eb-8cf0-da7a74f28d55.png)

2. View other posts with that flair
![image](https://user-images.githubusercontent.com/19519553/108609586-c6be2100-73c6-11eb-8672-09a11ac638d5.png)

**Comment by sharkusmanch** [comment]
Awesome! Will excluding flairs be part of #69 ?

**Comment by spikecodes** [comment]
Yeah that would likely be under #69 considering it would filter _out_ posts that contain certain flairs.
