### ISSUE TITLE
Feature Request | Additional parameter -p

### ISSUE THREAD

**Issue by fabaff** [spikecodes/libreddit#127]
**Is your feature request related to a problem? Please describe.**

There was a [request](https://github.com/NixOS/nixpkgs/issues/113066) to make libreddit available for NixOS. The package part is [done](https://github.com/NixOS/nixpkgs/pull/113185).

For the service would it be nice to be able to specify the port without the address.

**Describe the solution you'd like**

Add an additional parameter `-p`.

I'm thing about something like:

```text
-a	--address
-p    --port
-r	--redirect-https
```

This would allow one to run it with a different port than the default but with the default address or vice versa.

**Describe alternatives you've considered**

There is a very strong argument against adding `-p` and change `-a`. It would be a breaking change and would require everybody that uses an init script to adjust their configuration.

**Additional context**

No, but happy to provide more.

Thanks.

**Comment by spikecodes** [comment]
I appreciate you packaging Libreddit for NixOS!

Great suggestion! I've added the `-p`/`--port` command line argument in 8560e8a. Changes should be live shortly.
