### ISSUE TITLE
Bug Report | -a issue

### ISSUE THREAD

**Issue by fabaff** [spikecodes/libreddit#128]
**Describe the bug**

The short form doesn't seem to work if one follow the common pattern to work with CLI options.

**To reproduce**

```bash
$ libreddit -a 127.0.0.1:8888
thread 'main' panicked at 'index out of bounds: the len is 1 but the index is 1', src/main.rs:42:45
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Panic in Arbiter thread.
```

**Expected behavior**

Short format to work.

**Additional context**

Not sure if it's only an issue at my end as `-r` and `--address=127.0.0.1:8888` is working as documented.

Thanks

**Comment by spikecodes** [comment]
Thanks for this bug report! I've switched to [clap](https://github.com/clap-rs/clap/) in 3652342 for better command line argument parsing which has fixed this.
