### ISSUE TITLE
Bug Report | `Text-align: left` in subreddit-description would increase readability

### ISSUE THREAD

**Issue by Jonta** [spikecodes/libreddit#130]
**Describe the bug**
Subreddit descriptions/sidebars are centered. Harder to read. Source: https://practicaltypography.com/centered-text.html

**To reproduce**
1. New Firefox-profile, no extensions, 85.0.1
2. Go to https://libredd.it/r/news/
3. Sidebar-text ("Real news articles covering both the […]") is centered

**Expected behavior**
Sidebar-text is left-aligned

**Comment by spikecodes** [comment]
Great suggestion! I've added this and changes will be live shortly
