### ISSUE TITLE
Feature Request | Private/Quarantined/Banned Subreddits

### ISSUE THREAD

**Issue by Mennaruuk** [spikecodes/libreddit#131]
**Is your feature request related to a problem? Please describe.**
There is no way to know on Libreddit if a subreddit is private, quarantined, or banned. Reddit puts out a message whenever a subreddit has such status.

**Describe the solution you'd like**
Libreddit can copy and paste the text that shows from Reddit when a user encounters a private, quarantined, or banned subreddit.

**Describe alternatives you've considered**
Checking out the subreddit on reddit.com.

**Additional context**
You're awesome!

**Comment by spikecodes** [comment]
Fantastic suggestion, thank you!

**Comment by spikecodes** [comment]
This was a great idea and simple to implement! Changes should be live shortly.

**Comment by Mennaruuk** [comment]
WOW THAT WAS FAST AS FRICK! Thanks dude!!!!! You’re really good at this 😅
