### ISSUE TITLE
Bug Report | Right-to-left flair text split by right-to-left post title

### ISSUE THREAD

**Issue by Mennaruuk** [spikecodes/libreddit#132]
**Describe the bug**
Sometimes, post title gets sandwiched within the flair. AFAICS, this is more of a problem with non-English titles.

**To reproduce**
1. Go to this [archived ](https://web.archive.org/web/20210222234242/https://libredd.it/r/jordan/)page of r/jordan
2. Check out the seventh and eighth posts

![imageedit_2_7433432241](https://user-images.githubusercontent.com/52135169/108785621-c8f7bb00-753f-11eb-89cf-240311f244fd.png)
vs

![imageedit_4_6897557682](https://user-images.githubusercontent.com/52135169/108785624-ca28e800-753f-11eb-8ae4-c2187524d91b.png)

**Expected behavior**
Flairs and post titles should be separate.

**Additional context**
![gifntext-gif](https://user-images.githubusercontent.com/52135169/108785912-6a7f0c80-7540-11eb-899d-68d963fe4984.gif)

**Comment by spikecodes** [comment]
Thanks for this bug report! This issue appears to only apply to left-to-right text which renders differently in the browser. Although the HTML code is still properly structured (see image), the flair seems to wrap around the title when both the title and flair contain left-to-right text.

![image](https://user-images.githubusercontent.com/19519553/108786668-007c5c80-756c-11eb-92f4-0e898f65bfb7.png)

I'm not sure yet how I can fix this but I'll do some testing! :)

:smile: I love the GIF!

**Comment by curlpipe** [comment]
Option 1: Enforce `dir="ltr"` in the HTML to make everything left to right
Option 2: Autodetect direction (complicated)

Kinda swaying towards Option 1 here. Perhaps in the future we could add some kind of language in preferences to choose which language to use, and set rtl when using languages like Arabic or Hebrew.
