### ISSUE TITLE
Bug Report | Missing link in link-only post

### ISSUE THREAD

**Issue by burrhole** [spikecodes/libreddit#136]
**Describe the bug**
When a post is only a link, the link does not appear.

**To reproduce**
This post on r/linux:
https://www.reddit.com/r/linux/comments/lseii9/fedora_is_now_99_python2free/
Links to https://fedora.portingdb.xyz/

However the same post on libredd.it:
https://libredd.it/r/linux/comments/lseii9/fedora_is_now_99_python2free/
The only links are to the post page itself

I'm unsure if this is an issue with this post specifically, however I haven't noticed it before.

EDIT:
After a quick look, this seems to be on some of the posts from the same subreddit; the links are visible but not clickable on the main page, but i'm not sure if that is expected behavior or not: https://libredd.it/r/linux/

**Comment by spikecodes** [comment]
Thanks! Fixed in 9183ce1
