### ISSUE TITLE
Feature Request | Get permalink for particular comment

### ISSUE THREAD

**Issue by Leopardus4** [spikecodes/libreddit#137]
**Is your feature request related to a problem? Please describe.**
Many web services have option to get permalink for particular section or comment. 
Example: GitHub - I can go to [repo](https://github.com/joho/7XX-rfc) and click this nice icon near the title of paragraph to get direct link to i. e. "[Somebody Else's Problem](https://github.com/joho/7XX-rfc/blob/master/7xx.md#somebody-elses-problem)" :wink: paragraph. 
Example on Reddit: When I go to [random page](https://www.reddit.com/r/ProgrammerHumor/comments/jtnrlk/everyone_loves_pointers_right/), then click on a *date* of any comment, I would get a permalink to i. e. [this particular comment](https://www.reddit.com/r/ProgrammerHumor/comments/jtnrlk/everyone_loves_pointers_right/gc6ud9z/?context=3) (with `?context=3` part to understand the context).

**Describe the solution you'd like**
It would be very nice to have similar function in Libreddit. It would be an additional button/icon, or link added to existing element (date?). 

**Describe alternatives you've considered**
[There are many other possibilities how to do it ~~better~~ worse](https://userinyerface.com/), but it's not a good idea to go this way.

**Additional context**
I provided links above. Have a nice day!

**Comment by spikecodes** [comment]
I love this idea! Thanks for submitting.

**Comment by Leopardus4** [comment]
Wow!
I had seen this FR in "closed" and had wondered, why? Duplicate? "Wontfix"?
...then I read your comment and commit :smile:. You are so fast! Thank you so much, it works great!

**Comment by spikecodes** [comment]
My pleasure :smiley:

**Comment by spikecodes** [comment]
> hey i'm trying to get a permalink to a comment in the libreddit UI but i can't find it. Was the commit solving this feature request supposed to add that or am i misunderstanding @spikecodes

Sorry if it wasn't clear, here's how:
![image](https://user-images.githubusercontent.com/19519553/139517493-0777205f-fe41-434d-a8de-3af542bd2a15.png)
The timestamp for the comment is actually a link to the comment so simply copy that and you should be good.
