### ISSUE TITLE
Feature Request | Filter subreddits & users

### ISSUE THREAD

**Issue by ClockVapor** [spikecodes/libreddit#138]
It would be cool to have a RES-style ability to filter subreddits and users from your feeds.

**Comment by spikecodes** [comment]
Hey ClockVapor! This would be a great feature, it looks like another issue has been opened for this already: #69
Feel free to track progress there!

**Comment by ClockVapor** [comment]
Oops, sorry about that. I did a search and missed that one

**Comment by spikecodes** [comment]
No worries! Sometimes Github doesn't provide the best search results
