### ISSUE TITLE
Bug Report | Background color mismatch in PWA Icon on iPhone

### ISSUE THREAD

**Issue by Mennaruuk** [spikecodes/libreddit#139]
**Describe the bug**
There is a black border around the icon that makes it look awkward.
![AD5859B8-46CA-45FD-8E77-5A1AFC102BC3](https://user-images.githubusercontent.com/52135169/109361907-fa31fd00-7857-11eb-86e0-0004e445ff02.jpeg)

**To reproduce**
1. Check PWA icon on iPhone

**Expected behavior**
I believe this black border shouldn’t exist.

**Additional context**
I’m loving the new geometric logo!

**Comment by spikecodes** [comment]
Thank you for this bug report! I've just released [v0.5](https://github.com/spikecodes/libreddit/releases/v0.5.0) which has seemed to have fixed another PWA icon issue (#123), does this issue still occur?

**Comment by Mennaruuk** [comment]
Unsure if the site's been updated yet, but this is what I see when I added it to the Home Screen.
![6E81798E-8434-4F33-8D41-EECFE745023E](https://user-images.githubusercontent.com/52135169/111577691-27076f00-8789-11eb-823e-0a3860d7a799.jpeg)

**Comment by spikecodes** [comment]
Darn, it looks like the issue still persists. Thank you for checking anyway!

**Comment by Mennaruuk** [comment]
Could this be because the new icon is circular? Then iOS would color all the transparent areas outside of the circle black. My guess is if you turn that circle into a square, it’ll resolve the problem.

**Comment by spikecodes** [comment]
I've never thought of that, you might be right! I'll let you know once I change the Apple Touch Icon to a square.

**Comment by spikecodes** [comment]
Just pushed 0d6e18d97d1878ab008450e8f910574ba9274fbd where I filled in the background of the Apple Touch Icon. Hopefully that fixes this! Try deleting the old shortcut and adding the PWA to your homescreen once again.

**Comment by Mennaruuk** [comment]
Looking crispy! **_THANK YOU SO MUCH_**
![gif](https://user-images.githubusercontent.com/52135169/111734724-086cab00-8851-11eb-8092-d5f37d6b8123.gif)

**Comment by spikecodes** [comment]
😄 Wonderful! I'm happy to help
