### ISSUE TITLE
Bug Report | No audio for proxied videos

### ISSUE THREAD

**Issue by Zegnat** [spikecodes/libreddit#14]
**Steps to reproduce:**

1. Find a post consisting of a single video hosted by Reddit,
2. Visit it on libreddit using Firefox. (Have not tested to see if this bug exists for other browsers.)

**Result:** the video is proxied and playable by the browser's native player (yeay!) but loses the audio track (boo!).

Example URL: `https://libredd.it/r/valkyrae/comments/klhie9/rock_mannn/`.

**Expected:** head audio when playing the video.

**Comment by spikecodes** [comment]
Good catch. I see that I've been fetching the `fallback_url` value for videos but that doens't have audio.

**Comment by compliment** [comment]
If audio is there, it's available at DASH_audio.mp4 instead of DASH_{resolution}.mp4
Example :
-  `https://v.redd.it/54nu4899c9961/DASH_720.mp4` 
- `https://v.redd.it/54nu4899c9961/DASH_audio.mp4`

**Comment by spikecodes** [comment]
Thank you. I'd somehow have to merge the audio and video in the proxy when streaming it to the user.

**Comment by somoso** [comment]
Is it possible to use ffmpeg behind the scenes to stitch the two together and return it back to the end user?

**Comment by spikecodes** [comment]
Thank you for the suggestions!

> Is it possible to use ffmpeg behind the scenes to stitch the two together and return it back to the end user?
Yeah, that's totally possible but it would feel clunky to be shipping ffmpeg alongside Libreddit and having to redo the proxy system (not sure if I could make it stitch the audio and video and return it together in the current proxy, I think I might have to do this downloading and combining separately).

> EDIT: Had an idea! I know youtube-dl can do video downloads of reddit (+ more), and searching on Github for a "youtube-dl, but more server please" gave me this project: https://github.com/manbearwiz/youtube-dl-server

Is it possible to have a local instance of this running alongside libreddit (not publicly exposed) to initially download reddit videos, but then things like Youtube videos (for better privacy)?
That's a cool idea! Though again, I'm worried about bloating up Libreddit too much with all these media dependencies (especially if they were written in another language than Rust).

**Comment by somoso** [comment]
In that case, maybe something like this? https://docs.rs/youtube_dl/0.6.0/youtube_dl/index.html It wouldn't be a separate server but a crate package that you can import.

One thing I have noticed is that teddit does seem to have this under control, so it might be worth looking into/asking how they've managed to solve this issue.

**Comment by compliment** [comment]
I think bundling ffmpeg is a lot for just stitching audio and video. Is there a problem in shipping a custom js player?
Reddit also provides two more urls, one for mpeg-dash and the other for hls. Both requires client side hls player, if that's okay with everyone.

**Comment by spikecodes** [comment]
I agree that bundling ffmpeg would be a bit bulky. The current options I see are:
- Bundling a media utility (combining audio and video server-side)
- HLS player (combining audio and video server-side)

I wonder if there is a Rust-native utility that could handle the splicing of audio and video. Even so, it may be inefficient to stream from:
- media source → media utility → user.

Rather than (currently) proxying:
- media sources (audio & video) → user.

A JS-requiring player seems to be what Nitter does but would mean Libreddit isn't fully JS-free.

**Comment by FireMasterK** [comment]
I've been working on the same issue, but for another project :P
This is exactly why I've been learning rust as well

I'm trying to use https://github.com/rust-av/rust-av for this.

Let me know if you want to collaborate in any way!

**Comment by spikecodes** [comment]
Thanks FireMasterK! Can Rust-AV be used to combine audio and video?

**Comment by FireMasterK** [comment]
Yes, it can. The process is called muxing.

**Comment by spikecodes** [comment]
But can rust-av be used for muxing in it's current state? I don't see any documentation or example for muxing with it and the readme states:
> eventually demuxer, muxers and codecs

Which leads me to believe that muxing isn't here yet but is instead a planned feature.

**Comment by FireMasterK** [comment]
https://github.com/rust-av/rust-av/issues/140

Just got it updated :)

**Comment by spikecodes** [comment]
Thanks! I'm not sure if rust-av is the right option as there is very little documentation for it.

**Comment by FireMasterK** [comment]
The only other option I see is ffmpeg or C bindings for libav.

What exactly are you missing? I assume we could always open a GitHub issue asking for some help :)

**Comment by spikecodes** [comment]
Sure, I'll ask [here](https://github.com/rust-av/rust-av/issues/141).

**Comment by spikecodes** [comment]
It doesn't appear rust-av supporting muxing or demuxing with MP4s at the moment.

**Comment by spikecodes** [comment]
I have concluded that #145, #76, and #14 all stem from the method Libreddit uses to proxy content so I have unified these issues under a [single bug report](https://github.com/spikecodes/libreddit/issues/147).
