### ISSUE TITLE
Bug Report | Search doesn't redirect (anymore?)

### ISSUE THREAD

**Issue by Jonta** [spikecodes/libreddit#140]
**Describe the bug**
Reddit-search does not redirect to libreddit-search

**To reproduce**
1. https://www.reddit.com/search?q=cat redirects to
2. https://libredd.it/search/

**Expected behavior**
https://libredd.it/search/?q=cat&sort=relevance&t=all

Firefox, Privacy redirect 1.1.46

**Comment by spikecodes** [comment]
This sounds like an issue with Privacy Redirect rather than Libreddit, have you opened a bug report there?

**Comment by Jonta** [comment]
Done: https://github.com/SimonBrazell/privacy-redirect/issues/196

**Comment by spikecodes** [comment]
Nevermind, I was wrong. The issue was that Libreddit did not keep query parameters when normalizing the path to end with `/`.
Thanks for this bug report! Changes should be live shortly.

**Comment by spikecodes** [comment]
The automatic redirect that removes the query may still be stored in your cache so if you want to redirect a search with "cat" in it, you'll probably have to clear your browser cache for Libreddit.
