### ISSUE TITLE
Add my instance to instance list

### ISSUE THREAD

**Issue by imabritishcow** [spikecodes/libreddit#141]
Hey, just wanted to ask if you could add my instance to this list.

URL is at https://libreddit.bcow.xyz/ or over Tor at http://dflv6yjt7il3n3tggf4qhcmkzbti2ppytqx3o7pjrzwgntutpewscyid.onion/, no Cloudflare, hosted in the US.

**Comment by spikecodes** [comment]
Awesome, thank you for hosting Libreddit!
