### ISSUE TITLE
'Couldn't send request to Reddit' error message

### ISSUE THREAD

**Issue by milesmcclane** [spikecodes/libreddit#142]
Not sure if it's a bug or some sort of ip block from Reddit. My self hosted instance suddenly stopped working, only displaying 'Couldn't send request to Reddit'. Any click to anywhere other than settings leads straight back to the message.

Any ideas?

Thanks!

**Comment by spikecodes** [comment]
That test was unsuccessful, I'm reverting to [curl as the HTTP backend now](https://github.com/spikecodes/libreddit/actions/runs/618354404). Once this is successful, I'll push a fixing update.

**Comment by spikecodes** [comment]
Fixed! Reverting to [curl-client] fixed the issue. The new v0.3.1 release will be live [once Libreddit finishes compiling](https://github.com/spikecodes/libreddit/actions/runs/618387221).

**Comment by milesmcclane** [comment]
Brilliant! Fast work - well done! Thanks a lot 👍
