### ISSUE TITLE
Bug Report | /comments/ short urls aren't supported

### ISSUE THREAD

**Issue by B0pol** [spikecodes/libreddit#144]
**Describe the bug**
Using short urls, it says "nothing here"

**To reproduce**
1. Pick any reddit comments / post url, e.g https://libredd.it/r/wholesomememes/comments/ly2qjk/im_honestly_surprised_this_came_from_cyanide_and/
2. Remove everything but https://libredd.it/comments/id, then it becomes https://libredd.it/comments/ly2qjk
3. Try to open it

**Expected behavior**
It redirects to the page

**Additional context**
Permalink are supported, you just need to remove /comments/
https://libredd.it/ly2qjk

It works

**Comment by spikecodes** [comment]
Thanks for this feature request! Just added, changes will be live shortly.
