### ISSUE TITLE
Bug Report | Video problems on Vivaldi

### ISSUE THREAD

**Issue by TheCultLeader666** [spikecodes/libreddit#145]
**Describe the bug**
When browsing libreddit on the Vivaldi Browser, there are many issues with video. The video has no audio, it just buffers endlessly most of the time, when you press play the videos get smaller and are forced into a wider aspect ratio, while still buffering, although they return to normal if they do eventually play. Sometimes you press play and it appears to cause an error in the browser, as the whole window goes gray like it does when you first open the browser. Sometimes videos are just black and don't even buffer. Finally, long videos will only play the first few seconds, and will only appear to be a few seconds long.

**To reproduce**
1. Open the Vivaldi browser
2. Go to [libredd.it](https://libredd.it)
3. Look for videos in the feed
4. Try to play them
4. See issue

**Expected behavior**
The video will play on click (or even automatically), with audio, and will play the entirety of the video
**Additional context**
N/A

**Comment by spikecodes** [comment]
Thanks for this detailed bug report! What operating system are you using Vivaldi on to test this?

**Comment by TheCultLeader666** [comment]
I know that this is either a Vivaldi problem or a libreddit problem, as the issue is still present in the webpanel/sidebar panel, which is not affected by extensions.

**Comment by spikecodes** [comment]
Does the issue occur in Firefox or Brave as well? Safari (and other Webkit-based browsers) seem to have troubles playing videos: #76

**Comment by TheCultLeader666** [comment]
Ok, the weird aspect ratio thing is still present for a split second before each video on brave, and I know from experience that videos work perfectly on firefox, having just switched to vivaldi

**Comment by TheCultLeader666** [comment]
Idk if I should close this, I changed the theme from black to dark and it all works again

**Comment by TheCultLeader666** [comment]
Yeah, not closing it, as the issues came back, but that just makes this all the more weird

**Comment by Mennaruuk** [comment]
On Ubuntu, I have at least reproduced some videos not playing at all on Vivaldi, although video stream do work on Firefox.

https://user-images.githubusercontent.com/52135169/110162980-716a1280-7dbd-11eb-9976-a620e31e1532.mp4



Issue with audio might be related to #14 .

**Comment by spikecodes** [comment]
> On Ubuntu, I have at least reproduced some videos not playing at all on Vivaldi, although video stream do work on Firefox.

Thanks for this video!

Although the media controls (both browsers are based on Chromium) were the same, I wasn't able to reproduce this issue in Brave on ArchLinux:

https://user-images.githubusercontent.com/19519553/110742071-9f23e100-822d-11eb-9eaa-f0d7e1cc2645.mp4

> Issue with audio might be related to #14.

Yeah no videos in Libreddit have audio currently

**Comment by spikecodes** [comment]
(sorry accidentally hit "close with comment")

I installed Vivaldi and was immediately prompted with this message:

![image](https://user-images.githubusercontent.com/19519553/110742557-823bdd80-822e-11eb-9d9f-28950477977f.png)

I believe this is what causes the problem for video playback in Libreddit.

**Comment by spikecodes** [comment]
I followed this article and only had to restart Vivaldi once for that message to fix .
https://help.vivaldi.com/desktop/media/html5-proprietary-media-on-linux/

I was successfully able to reproduce the issue in Vivaldi by clicking play on a video.

https://user-images.githubusercontent.com/19519553/110743069-5b31db80-822f-11eb-9a09-753d214dfcf4.mp4

It eventually played after buffering for 30 seconds and I didn't face issues during the playback.

**Comment by spikecodes** [comment]
I believe this video playback issue, along with #76, comes from the method Libreddit uses to proxy video which is blocking. This means Libreddit has to download proxied media to the stack before serving it again rather than streaming it through.

**Comment by TheCultLeader666** [comment]
I was able to catch the problem with the website sometimes causing the browser to display a gray screen across the entirety of the window

https://user-images.githubusercontent.com/65368815/110802836-91ca1f00-824c-11eb-92ca-9bf9625343fe.mov

**Comment by spikecodes** [comment]
I have concluded that #145, #76, and #14 all stem from the method Libreddit uses to proxy content so I have unified these issues under a [single bug report](https://github.com/spikecodes/libreddit/issues/147).
