### ISSUE TITLE
Issues with Dates

### ISSUE THREAD

**Issue by axian32** [spikecodes/libreddit#146]
Dates on all posts and comments are showing up as "Jan 01 '70" on all libreddit sites.

Picture:
https://i.imgur.com/bYJaFbp.png

**Comment by Mennaruuk** [comment]
Could it be because of[ this commit](https://github.com/spikecodes/libreddit/commit/bf783c2f3a1f371a511aea0be55798d6aab37fc9)?

**Comment by spikecodes** [comment]
Thanks for this blazing fast bug report! :)
Yep, that commit seems to have messed up Libreddit's timestamps, good catch.
