### ISSUE TITLE
Bug Report | Post subject render bug

### ISSUE THREAD

**Issue by WUGqnwvMQPzl** [spikecodes/libreddit#148]
**Describe the bug**
Post subject seems doesn't escape the HTML tag, which can be cause layout problem, or even worse, XSS.

**To reproduce**
For example, this post in r/ReactJS:
https://libredd.it/r/reactjs/comments/m32owg/pre_renders_the_escaped_html_text/

**Expected behavior**
On that example, title will be render as: `<pre> renders the escaped html text`, not ` renders the escaped html text`, and whole layout will not be messed up.

**Additional context**
Screenshot:
![Screenshot 2021-03-12 102112](https://user-images.githubusercontent.com/36147447/110882303-b4c40400-831c-11eb-904e-6d47e5b3173a.png)

_And sorry my bad English_

**Comment by spikecodes** [comment]
Awesome, thanks for this bug report! I just pushed a change which now escapes way more than just post bodies so that this can be patched.
