### ISSUE TITLE
Bug Report | SI-suffixes for large numbers in search results

### ISSUE THREAD

**Issue by Jonta** [spikecodes/libreddit#151]
**Describe the bug**
Long numbers, overly detailed, hard to read

**To reproduce**

1. Search for something that brings up some large subreddits as results
2. "r/subreddit - 123456 Members"

**Expected behavior**
"r/subreddit - 123k members" with "123456 members" on mouseover

**Comment by spikecodes** [comment]
![image](https://user-images.githubusercontent.com/19519553/111722238-5edde780-8859-11eb-8a4b-bbf7d939eeab.png)
Is this the format you were thinking?

**Comment by spikecodes** [comment]
Implemented in f872baa1fea4b7d4401675042aa9f3e6eb905877! Search results for subreddits will be rendered like the above image.

**Comment by Jonta** [comment]
=)

Not too many instances when one needs the exact number, I suppose. Would still be more reddit-like if it appeared on mouseover though

**Comment by spikecodes** [comment]
> Would still be more reddit-like if it appeared on mouseover though

It doesn't look like Reddit shows the exact member count in search results on mouseover either
![image](https://user-images.githubusercontent.com/19519553/111883408-fc006380-89b2-11eb-8dca-276c1a91110c.png)

**Comment by Jonta** [comment]
Ah. I was thinking of dates, where "2 years ago" will expand on mouseover

Perhaps RES shows the exact number, not that I've tried it

**Comment by spikecodes** [comment]
Expanding all truncated numbers is a good idea! I've opened #156 for this
