### ISSUE TITLE
Add libreddit.40two.app to your instance list

### ISSUE THREAD

**Issue by 40two-app** [spikecodes/libreddit#152]
Hi, [40two.app](https://40two.app) has been up and stable for a while now, time to open up to the community. If you can, pls add [libreddit.40two.app](https://libreddit.40two.app) to your list?

**Comment by spikecodes** [comment]
Thank you for selfhosting Libreddit! :)

Yeah I can totally add it, what country is the server hosted in?

**Comment by 40two-app** [comment]
Excellent, thank you. The server runs on a Dutch datacentre. (aka the Netherlands)

**Comment by spikecodes** [comment]
Awesome, just added! https://github.com/spikecodes/libreddit/commit/3c5b4037e29067f1b53bf75fae53a0d84c1939ad
