### ISSUE TITLE
Feature Request | Link to reddit-version on all pages

### ISSUE THREAD

**Issue by Jonta** [spikecodes/libreddit#154]
**Problem:**
Some pages I want to view on reddit itself. E.g. when they look pretty empty in libreddit

**Solution:**
Link in header, akin to what nitter provides for Twitter

**Alternatives:**
Editing the URL

**Additional context:**
Had to turn off Reddit-redirects in Privacy Redirect 1.1.46

**Comment by Mennaruuk** [comment]
I see what you mean. Something like this:
![firefox_ek9tYi5WYS](https://user-images.githubusercontent.com/52135169/111712690-86ff2380-8824-11eb-885a-b2d51481fc59.jpg)

**Comment by spikecodes** [comment]
Good idea, thanks!

**Comment by microraptor** [comment]
It would be very convenient to have a settings option that would add a parameter like `noredirect=true` to the link URL (e.g. "www.reddit.com/r/all?noredirect=true"). The people with redirect extensions like Privacy Redirect could add URLs with that parameter to the exception list.

**Comment by Jonta** [comment]
> It would be very convenient to have a settings option that would add a parameter like `noredirect=true` to the link URL (e.g. "www.reddit.com/r/all?noredirect=true"). The people with redirect extensions like Privacy Redirect could add URLs with that parameter to the exception list.

@microraptor If something like this were to be implemented, I *strongly* suggest changing `noredirect=true` to `redirect=false` to avoid the double negative which is more confusing, and therefore requires more thinking. Similar to a checkbox that says "[ ] turn off light" instead of "[x] turn on light". =)

**Comment by spikecodes** [comment]
> It would be very convenient to have a settings option that would add a parameter like `noredirect=true` to the link URL (e.g. "www.reddit.com/r/all?noredirect=true"). The people with redirect extensions like Privacy Redirect could add URLs with that parameter to the exception list.

Interestingly, Privacy Redirect can already tell when a user has come from a private frontend. So if you enable the Reddit Redirects in Privacy Redirect and click "reddit" on [this post](https://libredd.it/r/AskReddit/comments/m9xmms/whats_cool_now_but_probably_wont_be_in_5_years/), it will take you to Reddit without redirecting you back to Libreddit.

**Comment by radhta** [comment]
Link to reddit, and link to old reddit as well, would be a good idea.

**Comment by mikupls** [comment]
I'm also interested in this feature. I think ideally we would have this link in `base.html` (to avoid custom implementation for all the other templates, like `post.html` is doing right now with the "reddit" link).

@spikecodes do you see any trivial way to implement this? I'm wondering if the only way is to extend the Base template and pass the current URL when rendering all the other templates, which seems a bit annoying.

**Comment by Jonta** [comment]
@spikecodes Should the additional suggestion @radhta made, of linking to old.reddit.com (good if one isn't logged in to reddit, and still wants the good old layout, instead of the bad new one) be made into a new issue?
