### ISSUE TITLE
Feature Request | Increase space between collapse comments and username in comments section

### ISSUE THREAD

**Issue by OpenWick** [spikecodes/libreddit#155]
Many times on mobile I am accidentally clicking usernames next to collapse comment.

It would be better if the distance between them is increased a bit so that accidental clicks won't happen.
![IMG_20210320_164725](https://user-images.githubusercontent.com/78715124/111867841-af119280-899c-11eb-9c69-14ee26aa2d57.jpg)

**Comment by spikecodes** [comment]
Great idea! I know exactly what you mean! I'll work on this today.

**Comment by spikecodes** [comment]
Just added this for v0.5.5!

**Comment by OpenWick** [comment]
Wow awesome :)
