### ISSUE TITLE
Bug Report | [New HSTS option seems to be causing issues?]

### ISSUE THREAD

**Issue by ms-jpq** [spikecodes/libreddit#158]
First of all, thank you very much for writing this awesome service! 

It's really fast and beats the actual reddit UI by a mile.

**Describe the bug**

![图片](https://user-images.githubusercontent.com/50598611/111919684-80e98c80-8a48-11eb-924d-a29df8ed817d.png)

**To reproduce**

I have docker setup to auto pull and experienced the image above about 2 hours ago, which leads me to believe that v0.6 broke something. It was totally working fine and awesome before.

I can go fiddle around with my reverse proxies and cloudflare settings to pin down what's going on more, but I do not have the time right now. (moving places)

So the most likely culprit I see is the new `--hsts` thing that was added during `v0.6.0` interfering with Cloudflare's HSTS settings, which I have turned on.

I understand that this might be a case of `operator error`, since I am sure you have very thoroughly tested it before release, and I see that the official instance are not behind cloudflare.

If you feel that way, please just close the issue.

I am only filing this before I suddenly got a broken page today, and I thought it was best to let you know.

again,

thank you for the awesome work you are doing, and i hope the best for everything :)

**Comment by ms-jpq** [comment]
wait it also could be that im using nginx and using http 1.1 for proxy instead of 1.0, judging by the error

**Comment by Mennaruuk** [comment]
Yeah, I'm also using another instance, and the same error shows up. Should I contact the webmaster of that instance? If so, what can I tell them to do? Thanks a lot!

**Comment by spikecodes** [comment]
Thanks for reporting this! :D

It looks like this might be an issue with v0.6.1 (which switches the client from HTTP/1.1 to HTTP/2) rather than v0.6.0 (which adds the HSTS header).

**Comment by spikecodes** [comment]
I just pushed v0.6.2 which fixes this! Changes will be live on the official instances shortly and the Docker build should be ready soon after that. :smiley:

**Comment by ms-jpq** [comment]
thank you for the hot fix

https://github.com/spikecodes/libreddit/commit/0bb1677520b6347ba97f791450121e5da22acd84
!

**Comment by spikecodes** [comment]
:grin: My pleasure! The `--hsts` header will still work as normal once the Docker build for v0.6.2 finishes.
