### ISSUE TITLE
Tor routing [feature request]

### ISSUE THREAD

**Issue by sorjgdojbodjhdo** [spikecodes/libreddit#16]
Hi,

It would be great to add an option to route traffic through Tor. I'm really happy to have found this software as it is exactly what I needed, thank you.

**Comment by spikecodes** [comment]
Hi, I'm glad you like Libreddit! Do you mean the frontend traffic (`User → Libreddit`) or the backend traffic (`Libreddit → Reddit`)? We have an `.onion` website hosted by a community member if you want to route your frontend traffic through Tor: [spjmllawtheisznfs7uryhxumin26ssv2draj7oope3ok3wuhy43eoyd.onion](http://spjmllawtheisznfs7uryhxumin26ssv2draj7oope3ok3wuhy43eoyd.onion).

**Comment by sorjgdojbodjhdo** [comment]
@spikecodes I'm self hosting my own instance. The project youtube-local (https://github.com/user234683/youtube-local) has an option to route all traffic through Tor. I can activate the option and specify a port where Tor is listening (9050 if Tor browser is running) and my traffic is automatically anonymized. This is what I meant.

**Comment by spikecodes** [comment]
I see what you mean, it looks like `youtube-local` is routing the back-end traffic through Tor. I could see the use for back-end Tor routing but some anonymity is already achieved if many people are using Libreddit (all looks like one user to Reddit). I appreciate the suggestion but this feature isn't planned for Libreddit. If you still want to route the back-end traffic through Tor, you're welcome to self-host a Libreddit instance on a server that uses Tor by using a Linux distribution like Tails.
