### ISSUE TITLE
Feature Request | Nord theme/Dracula Theme

### ISSUE THREAD

**Issue by TheCultLeader666** [spikecodes/libreddit#161]
**Is your feature request related to a problem? Please describe.**
No, it is not related to a problem

**Describe the solution you'd like**
Entries in the theme option to enable a "Nord" theme that follows the [Nord color scheme](https://www.nordtheme.com/docs/colors-and-palettes), and a "Dracula" theme that follows the [Dracula color scheme](https://github.com/dracula/dracula-theme)

**Describe alternatives you've considered**
Using an extension such as dark reader with custom colors with the libreddit light theme

**Additional context**
N/A

**Comment by Henryws** [comment]
I added a Dracula theme. It's in PR right now. I will work on a Nord one later

**Comment by TheCultLeader666** [comment]
Great! 😁

**Comment by spikecodes** [comment]
Thank you for your contribution @Henryws!
