### ISSUE TITLE
Feature Request | Show r/<subreddit>/about/sidebar

### ISSUE THREAD

**Issue by microraptor** [spikecodes/libreddit#162]
**Is your feature request related to a problem? Please describe.**
On `www.reddit.com/r/<subreddit>/about/sidebar` the text of the old.reddit sidebar is shown. Libreddit doesn't display anything there yet.

**Describe the solution you'd like**
Display the information on /about/sidebar pages in order to see the old.reddit sidebar. Perhaps even a link in the normal sidebar to /about/sidebar would be helpful.

**Additional context**
Especially for smaller community the sidebar sometimes still contains helpful information that was not copied to the new sidebar yet.

**Comment by spikecodes** [comment]
Great idea! Just added this in v0.7.0 :)
