### ISSUE TITLE
Bug Report | Libreddit posts flash black when returning to previous page on iOS

### ISSUE THREAD

**Issue by Mennaruuk** [spikecodes/libreddit#164]
**Describe the bug**
On iOS 14, when returning to previous page, Libreddit posts flash black.

**To reproduce**
1. Enable automatic system theme in settings
2. Go to any post
3. Return to Libreddit homepage
4. See if posts flash black

**Expected behavior**
Posts shouldn’t flash black when returning to previous page. 

**Additional context**
One major giveaway: this only occurs when System theme is chosen.

Video

https://user-images.githubusercontent.com/52135169/112062379-3fcfa600-8b36-11eb-8eb1-bdaadb487510.mp4

**Comment by spikecodes** [comment]
Thank you for this bug report! I wasn't able to reproduce the issue in Gecko and Chromium on Android which leads me to believe this is another WebKit-specific issue. I'm not sure if this is something I can fix from my end or if Safari would have to stick closer to the CSS specification to prevent this issue from occurring.

**Comment by Mennaruuk** [comment]
Yeah, I face the same issue with DuckDuckGo. This issue, coupled with lack of video playback on Libreddit, and no GIF playback on Nitter, is giving me a bad experience with Safari. And there's little to do about it, it's hard to get in touch with who develops Safari. I'll close the issue till further changes. Thank you dude!

**Comment by spikecodes** [comment]
I appreciate all your detailed bug reports! Best of luck on fixing your troubles with Safari!
