### ISSUE TITLE
Bug Report | Visual formatting issues on browsers such as Pale Moon or Basilisk

### ISSUE THREAD

**Issue by yoshiyoshyosh** [spikecodes/libreddit#167]
**Describe the bug**
On browsers such as Pale Moon or Basilisk, there are major visual formatting errors such as what is shown below:
![palemoon_2021-03-26_16-44-29](https://user-images.githubusercontent.com/36683489/112699015-f0041e00-8e58-11eb-9cd5-2832071ae0c7.png)
![palemoon_2021-03-26_16-44-46](https://user-images.githubusercontent.com/36683489/112699025-f397a500-8e58-11eb-9e21-6a4c6439388c.png)
![palemoon_2021-03-26_16-45-02](https://user-images.githubusercontent.com/36683489/112699028-f5616880-8e58-11eb-993a-8db854a8b45e.png)
This is what displays with card, clean, and compact styles, respectively.

**To reproduce**
1. Download [Pale Moon](https://www.palemoon.org/) or [Basilisk](http://basilisk-browser.org/)
2. Visit libreddit

**Expected behavior**
Normal formatting, such as what displays on more mainstream bowsers.

**Additional context**
This may also happen on any old firefox fork or XUL-based browser, but I did not test it on others.

**Comment by spikecodes** [comment]
Thank you for opening this bug report! It sounds like XUL-based browsers don't correctly render CSS grids. I'm not sure if they are following the modern CSS standards.
