### ISSUE TITLE
Bug Report | Save settings remove the subscribed subreddits

### ISSUE THREAD

**Issue by xmbiauly** [spikecodes/libreddit#169]
**Describe the bug**
Subscribed subreddits get removed if you click the save button in settings.

**To reproduce**
1. Go to 'https://libredd.it/r/privacy'
2. Click on 'Subscribe'
3. Click on 'Settings'
4. Click on 'Save'

**Comment by TheCultLeader666** [comment]
I have this issue too, but I had not realized the cause

**Comment by Mennaruuk** [comment]
Can confirm. This is the cURL request. Notice that saved subreddits are empty:

`curl "https://libredd.it/settings" -H "User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:87.0) Gecko/20100101 Firefox/87.0" -H "Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8" -H "Accept-Language: en-US,en;q=0.5" --compressed -H "Connection: keep-alive" -H "Cookie: theme=system; front_page=default; layout=card; comment_sort=confidence; show_nsfw=on; subscriptions=; wide=; post_sort=hot" -H "Upgrade-Insecure-Requests: 1" -H "TE: Trailers"`

**Comment by spikecodes** [comment]
Thank you for reporting this! I realized that when I rewrote Libreddit using Hyper, [I accidentally defined "subscriptions" as a setting](https://github.com/spikecodes/libreddit/blob/6a7f725c12fe230ec023f279273471b01b36b7b5/src/settings.rs#L53) (meaning it was reset by settings).
