### ISSUE TITLE
Feature Request | Keyboard-based navigation

### ISSUE THREAD

**Issue by Leopardus4** [spikecodes/libreddit#170]
**Is your feature request related to a problem? Please describe.**
Navigation/scrolling on web pages with mouse is sometimes annoying, especially on long pages. Browsers additionally offer navigation with arrows, `PgDn` and `Tab`. But on pages like reddit, the best scrolling method would be comment-by-comment, rather than "whole screen down" (`PgDn`).

Good example: [here](https://duckduckgo.com/?q=foo&ia=web) I can navigate with arrows or with vim-like `h` ,`j` ,`k` ,`l` keybindings.

**Describe the solution you'd like**
Remapping of arrows behaviour. Example:
- `ArrUp` - jump one comment/post up
- `ArrDown` - one comment down (but rather go to reply than to next comment on same level)
- `PgUp` - previous comment on same level
- `PgDn` - next comment on same level
- `ArrLeft` - go to previous comment on higher level
- `ArrLeft` - go to next comment on higher level

It's only a suggestion, so maybe other mappings would be more comfortable & intuitive. I'm leaving it open for discussion.

**Describe alternatives you've considered**
- another mappings of arrow keys than suggested above
- `h` ,`j` ,`k` ,`l` vim mappings
- additionally remapping `Tab` and `Shift`+`Tab`

**Additional context**
I guess there will be needed few lines in js ([1](https://developer.mozilla.org/en-US/docs/Web/API/Document/keydown_event),[2](https://www.w3schools.com/jsref/met_element_scrollintoview.asp)).

**Comment by Welding-Torch** [comment]
Yes I think this would be very convenient

**Comment by spikecodes** [comment]
I appreciate your detailed issue description but I don't think this feature will be added. I can't see a way to fulfill this without using JavaScript and I'm trying to keep Libreddit's JS to a bare minimum (so that it only covers playback audio)
