### ISSUE TITLE
Add libreddit.silkky.cloud

### ISSUE THREAD

**Issue by TheSilkky** [spikecodes/libreddit#175]
Add libreddit.silkky.cloud. The instance is hosted in Finland on a Hetzner dedicated server.

My configuration can be found here:
https://github.com/TheSilkky/libreddit-silkkycloud

A+ on Mozilla Observatory:
https://observatory.mozilla.org/analyze/libreddit.silkky.cloud

**Comment by spikecodes** [comment]
Thank you for selfhosting Libreddit! :)
