### ISSUE TITLE
Fix hyperlink preview

### ISSUE THREAD

**Issue by ghost** [spikecodes/libreddit#178]
![IMG_20210406_191025](https://user-images.githubusercontent.com/59839368/113720364-2caeff80-970c-11eb-84b5-794f66e15b24.jpg)

Reddit displays that box in a rectangle, here it just varies without aspect ratio

**Comment by spikecodes** [comment]
Thank you for the suggestion but this design is intentional. The current Reddit design leaves so much underutilized space and vertical asymmetry in it's layout of URL previews so Libreddit stretches those vertically to fit the entire post panel.
