### ISSUE TITLE
Support searching for subreddits

### ISSUE THREAD

**Issue by somoso** [spikecodes/libreddit#18]
First of all, just want to say I love this. I pretty much use this every day over reddit.

I'm missing a way to easily browse/search existing subreddits, and missing out on seeing what is on popular and all subreddits. If the links to popular/all were put in first, then a way to browse/search through existing subreddits, that would be excellent.

**Comment by spikecodes** [comment]
Awesome, I'm glad you like Libreddit! I appreciate the suggestion, yeah the ability to search subreddits would be useful. Currently you can [view the posts and sidebar of a subreddit](https://libredd.it/r/privacy) but [wikis](https://reddit.com/r/privacy/wiki/index) are [not yet implemented](https://github.com/spikecodes/libreddit/issues/17).

I didn't quite understand this part though:
> the links to popular/all were put in first, then a way to browse/search through existing subreddits

I interpreted this as the ability to search for subreddits. Though, did you mean the ability to search for posts/comments globally along with inside a subreddit?

With release of [v0.2.4](https://github.com/spikecodes/libreddit/releases/tag/v0.2.4), users can now search globally:
![image](https://user-images.githubusercontent.com/19519553/103445428-d1f79a80-4c28-11eb-937c-1c3facc97bb1.png)
Or inside a subreddit by navigating to the subreddit and click the "in r/____" checkbox before searching:
![image](https://user-images.githubusercontent.com/19519553/103445435-e3d93d80-4c28-11eb-9d09-0a5565ad4190.png)

**Comment by somoso** [comment]
Sorry, I think I was half asleep when I wrote that bit. I meant being able to search for subreddits. 

I did notice the ability to search within subreddits, which is super cool and very handy in the future (I used to go on programming subreddits and search for frameworks and topics, so that'll come in handy for the future!)

**Comment by spikecodes** [comment]
Haha yeah that's what I was thinking. Thanks, great suggestion!

**Comment by robrobinbin** [comment]
I'm taking a look at this, this is what I currently have.

![image](https://user-images.githubusercontent.com/8597693/104521235-c8910980-55fc-11eb-8f3b-d0e59d49d389.png)

I'll be making a PR pretty soon

**Comment by somoso** [comment]
That looks incredible! Fantastic job!
