### ISSUE TITLE
Increase font size of upward Arrow

### ISSUE THREAD

**Issue by bnainar** [spikecodes/libreddit#180]
![IMG_20210406_191025](https://user-images.githubusercontent.com/59839368/113720364-2caeff80-970c-11eb-84b5-794f66e15b24.jpg)

The arrow just before the score count is smaller and thinner.

### Solution
* Increase the thickness and size
* Or, use a CSS icon from http://css.gg, request only that icon

I recommend adding [this](https://css.gg/arrow-up) or [that](https://css.gg/arrow-long-up)

**Comment by Mennaruuk** [comment]
Is this a browser-based problem? It’s showing up okay on iOS Safari.
![EC3A2433-EC70-4AE5-8737-CFB3579668A2](https://user-images.githubusercontent.com/52135169/113737477-0ec1aa80-96cc-11eb-95cb-65e6d0eb0b57.jpeg)

**Comment by spikecodes** [comment]
In the new release of [v0.14.2](https://github.com/spikecodes/libreddit/releases/tag/v0.14.2), Libreddit uses the [Inter](https://rsms.me/inter/) font! This font includes a correctly proportioned arrow which should fix this inconsistency.
![image](https://user-images.githubusercontent.com/19519553/118897070-227e4480-b8f9-11eb-8c7b-2d14e34aa978.png)
