### ISSUE TITLE
Subreddits page

### ISSUE THREAD

**Issue by developers-github** [spikecodes/libreddit#183]

**Comment by spikecodes** [comment]
Hi, are you able to provide more context? Libreddit currently supports searching for subreddits along with searching for posts inside specific subreddits so I'm not sure what you mean.

**Comment by developers-github** [comment]
I mean a dedicated tab/page for searching subreddits and showing them even if they have graphic content (like violence)

**Comment by spikecodes** [comment]
I'm having difficulty understanding what you mean. Is this feature currently available in Reddit? If so, are you able to send a screenshot of the functionality at Reddit?

**Comment by bnainar** [comment]
He/she may mean like a dedicated page to search from, apart from searching from that search box inside a subreddit page. Like GitHub has, github.com/search

You consider implementing, if you want to add a advanced search option

**Comment by developers-github** [comment]
Thank you @bnainar

**Comment by spikecodes** [comment]
I see, thanks!

**Comment by spikecodes** [comment]
I realise this is a duplicate of #125 so I'll close this issue and redirect discussion there.
