### ISSUE TITLE
Lazy loading images

### ISSUE THREAD

**Issue by ghost** [spikecodes/libreddit#184]
What do you think about it? Does it improve performance, or metrics like pagespeed insights (libreddit currently scores 98%)

**Comment by spikecodes** [comment]
The only non-JS method I could see of doing this was using the experimental [loading attribute](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/iframe#attr-loading) on images which didn't appear to have any performance boosts when I performed A/B testing of it in Brave v89.

Do you know of any other way to achieve this without the use of JavaScript?

**Comment by spikecodes** [comment]
I'm not sure if it will have any effect but I added the lazy loading attribute to images in [v0.15.0](https://github.com/spikecodes/libreddit/releases/tag/v0.15.0).
