### ISSUE TITLE
Brotli text compression

### ISSUE THREAD

**Issue by spikecodes** [spikecodes/libreddit#186]
## Is your feature request related to a problem? Please describe.
N/A

## Describe the solution you'd like
Server responses should be compressed using the Brotli text compression algorithm. This could be achieved through [this crate](https://github.com/dropbox/rust-brotli).

## Describe alternatives you've considered
GZIP compression, though it is less efficient than Brotli.

## Additional context
Forked from #185.

**Comment by FireMasterK** [comment]
Shouldn't this be done on a reverse proxy level? 🤔

On nginx, I use https://github.com/google/ngx_brotli

**Comment by spikecodes** [comment]
Thanks for showing me that repo! I think you're right. Like with TLS, the method of text compression should probably fall on the reverse proxy. I will be closing this issue for now.
