### ISSUE TITLE
Docker build Caching

### ISSUE THREAD

**Issue by FireMasterK** [spikecodes/libreddit#189]
## Is your feature request related to a problem? Please describe.
Build take too long currently.

## Describe the solution you'd like
https://evilmartians.com/chronicles/build-images-on-github-actions-with-docker-layer-caching
A Dockerfile which can utilize dependency caching

## Describe alternatives you've considered
N/A

## Additional context
N/A

**Comment by spikecodes** [comment]
Fantastic write-up, thanks for sharing this! I had no idea GitHub Actions had already implemented [worflow caching](https://docs.github.com/en/actions/guides/caching-dependencies-to-speed-up-workflows)! :grin:

**Comment by Scoder12** [comment]
Perhaps something like [this](https://github.com/marketplace/actions/rust-cache) could work for the "Rust" workflow?

**Comment by spikecodes** [comment]
Sorry for the late response. Yeah, that's being used [currently](https://github.com/spikecodes/libreddit/blob/master/.github/workflows/rust.yml#L20-L21).
