### ISSUE TITLE
RSS/Atom export

### ISSUE THREAD

**Issue by erdnaxe** [spikecodes/libreddit#190]
## Is your feature request related to a problem? Please describe.
I would like to be able to fetch content using RSS/Atom feeds.

## Describe the solution you'd like
For example I would like `/r/sub_reddit.rss` to be the RSS feed of `/r/sub_reddit/`, just like the official Reddit instance.

## Describe alternatives you've considered
Parsing libreddit HTML content with RSS-bridge.

## Additional context
/

**Comment by spikecodes** [comment]
Duplicate of #27
