### ISSUE TITLE
Cargo.lock

### ISSUE THREAD

**Issue by fabaff** [spikecodes/libreddit#191]
## Is your feature request related to a problem? Please describe.
After the 0.3.1 the `Cargo.lock` file was removed from the repository. The NixOS package depends on this file to be able to create proper builds.

## Describe the solution you'd like
Please re-add `Cargo.lock`.

## Describe alternatives you've considered
Requires creating the content of `Cargo.lock` manually and shipping it as a patch.

**Comment by spikecodes** [comment]
Thanks for reporting this issue! Future releases will now include the `Cargo.lock` file again.
