### ISSUE TITLE
WIki: Wide content gets clipped.

### ISSUE THREAD

**Issue by jtagcat** [spikecodes/libreddit#192]
Wiki pages, especially the ones with tables get clipped, content is hidden.

Add a horizontal scrollbar to elements within as needed.

**Comment by spikecodes** [comment]
Thanks for reporting this bug! Are you able to link an example of a Wiki page that gets cut off?

**Comment by jtagcat** [comment]
https://r.c7.ee/r/DataHoarder/wiki/hardware#wiki_hard_drives

**Comment by spikecodes** [comment]
Thanks! Should be fixed now

**Comment by jtagcat** [comment]
Would it be (easily) possible to do it per-object? As in scroll in the table, but don't scroll other text. (Somewhat like iframe-like behaviour.)

**Comment by spikecodes** [comment]
Good idea! I'll address this in #197

**Comment by spikecodes** [comment]
Nevermind, that issue addresses a different feature.

**Comment by spikecodes** [comment]
> Would it be (easily) possible to do it per-object? As in scroll in the table, but don't scroll other text. (Somewhat like iframe-like behaviour.)

Just added! b47cfd1
