### ISSUE TITLE
when trying to access the articles from the /r/piracy wiki, nothing appears

### ISSUE THREAD

**Issue by assjdksbak** [spikecodes/libreddit#195]
## Describe the bug
 when trying to access the articles from the /r/piracy wiki, nothing appears, only a link appears to return to the home screen, but they work on reddit.com and old.reddit.com

## To reproduce

1. Go to https://libredd.it/r/Piracy/wiki/megathread (or any of the articles that appear on the wiki)
2. Click on any article, for example, Related / Alternative Subreddits
3. See error

![Captura de pantalla_2021-04-15_00-43-58](https://user-images.githubusercontent.com/81318481/114815339-89ae5380-9da5-11eb-8c7b-e28c11a7942f.png)

![Captura de pantalla_2021-04-15_00-43-27](https://user-images.githubusercontent.com/81318481/114815333-86b36300-9da5-11eb-9629-cbe92839d8a1.png)

## Expected behavior

  be able to see the article

## Additional context

  this also happens on teddit, and the following error appears: Cannot GET /r/Piracy/wiki/megathread/related_subreddits

**Comment by spikecodes** [comment]
Thank you for reporting this bug! Should be fixed now. :grin:

**Comment by assjdksbak** [comment]
> Thank you for reporting this bug! Should be fixed now. grin
> 
> Changes take a few minutes to show on the official instances.

thank you, you didn't take long at all :smiley:
