### ISSUE TITLE
Full-width display.

### ISSUE THREAD

**Issue by jtagcat** [spikecodes/libreddit#197]
## Is your feature request related to a problem? Please describe.
![image](https://user-images.githubusercontent.com/38327267/115082478-80cc9780-9ef5-11eb-876f-54f81ace7c60.png)

In some cases, it'd be better, if more screen real estate was used.

## Describe the solution you'd like

(cookie to retain previous state?)

Add a button to toggle wide/wrapped mode. Default should be configurable in server ~~config~~ env var.

**Comment by spikecodes** [comment]
Thanks! This is achievable through the "Wide UI" option in settings.

**Comment by jtagcat** [comment]
Are there defaults, that could be set by the server (docker env variables, not changing the source)?

**Comment by spikecodes** [comment]
Ooh that's an interesting idea, are you able to open a separate issue for "server config defaults"?
