### ISSUE TITLE
Request for a twitter equivalent in rust

### ISSUE THREAD

**Issue by gsitreble2019** [spikecodes/libreddit#198]
## Is your feature request related to a problem? Please describe.

No.. but would be cool to do this also for twitter. Nitter is there but needs complex installation. libreddit is simple and since it is just one binary easy to copy to any basic server.

## Describe the solution you'd like

Please build one for twitter.

## Describe alternatives you've considered

obviously nitter

## Additional context

https://github.com/zedeus/nitter/issues/370

**Comment by spikecodes** [comment]
I'm glad you like Libreddit's simple installation! :) 

Though, I don't think GitHub Issues on one project should be used to request another project. You're welcome to join our Matrix room to discuss the idea but I'll be closing this issue for now.
