### ISSUE TITLE
Server-side configuration defaults

### ISSUE THREAD

**Issue by jtagcat** [spikecodes/libreddit#199]
Continuation of #197 

I'd like to set custom default settings, without modifying the source.

**Comment by curlpipe** [comment]
What kind of settings are you after? And would these be set in a config file?

**Comment by jtagcat** [comment]
All of them. It'd be smart if the default settings wouldn't be separated from the settings definitions (if a setting is added in the future, it becomes available to set it's default as well).

Config file or env vars, I don't personally care. Env vars can be read from a (config-like) file, so they might be preferred?

**Comment by spikecodes** [comment]
Thanks for this feature request! I've implemented this via environment variables https://github.com/spikecodes/libreddit/commit/e4f9bd7b8d9dc09e9b3b349393711c5eaba8473d.
