### ISSUE TITLE
List subreddit's mods.

### ISSUE THREAD

**Issue by jtagcat** [spikecodes/libreddit#201]
## Describe the solution you'd like
On non-thread pages, show a collapsed section below the sidebar, listing the mods of the subreddit.

**Comment by spikecodes** [comment]
Great idea, thanks! :grin:

**Comment by jtagcat** [comment]
Please use the heart or +1 reaction on github instead of commenting. It comes up as a notification each time.

**Comment by curlpipe** [comment]
I have a PR. It's not a separate collapsed section, instead I integrated it into the sidebar itself. But it does the job.

**Comment by curlpipe** [comment]
@spikecodes Afaik, this issue can be closed :)

**Comment by jtagcat** [comment]
gh doesn't recognize `This PR closes issue no. #201`

Use `Closes #201` instead.

**Comment by spikecodes** [comment]
Just linked them so that should be fixed now.
