### ISSUE TITLE
Adding Self-Hosted Instance

### ISSUE THREAD

**Issue by lrehmann** [spikecodes/libreddit#202]
Hi,

I'd like to  add on [libreddit.domain.glass](https://libreddit.domain.glass) as a community instance.
Thanks for your continued development of libreddit!

Cheers

**Comment by lrehmann** [comment]
NY, USA

**Comment by spikecodes** [comment]
Done! Just listed it: https://github.com/spikecodes/libreddit/commit/ffc3bfe72df4a45ad2f64001627dbfca749afe29
