### ISSUE TITLE
Show posts from subscribed users on the home page

### ISSUE THREAD

**Issue by beerisgood** [spikecodes/libreddit#206]
## Is your feature request related to a problem? Please describe.
no problem but convenience feature.

## Describe the solution you'd like
i would like to have the posts of subscribed users presented on e.g. https://libredd.it/, instead of only subscribed subs as before.

## Describe alternatives you've considered
at the moment i need to click on "Feeds" -> specific user under "REDDIT FEEDS"

## Additional context
see
![image](https://user-images.githubusercontent.com/9625159/115973553-2ca95f00-a556-11eb-85aa-738a41ec10c6.png)

**Comment by spikecodes** [comment]
I believe this should be currently implemented. For instance, if I follow [u/Merkuri22](https://libredd.it/u/Merkuri22), I will see the posts that they made to their profile in my feed:

![image](https://user-images.githubusercontent.com/19519553/117558103-88e9a400-b069-11eb-949b-b95674055c12.png)

**Comment by beerisgood** [comment]
> I believe this is already implemented. For instance, if I follow [u/Merkuri22](https://libredd.it/u/Merkuri22), I will see the posts that they made to their profile in my feed:
> 
> ![image](https://user-images.githubusercontent.com/19519553/117558103-88e9a400-b069-11eb-949b-b95674055c12.png)

Posts on own profile aren't the same.

**Comment by spikecodes** [comment]
Following should only show posts that they make to their profile as that is [intended Reddit behavior](https://libredd.it/r/NewToReddit/comments/cfua31/what_does_following_someone_actually_do/eufc78h?utm_source=share&utm_medium=web2x&context=3). Are you suggesting Libreddit differ from Reddit by showing posts that users make to subreddits?

**Comment by beerisgood** [comment]
> Following should only show posts that they make to their profile as that is [intended Reddit behavior](https://libredd.it/r/NewToReddit/comments/cfua31/what_does_following_someone_actually_do/eufc78h?utm_source=share&utm_medium=web2x&context=3). Are you suggesting Libreddit differ from Reddit by showing posts that users make to subreddits?

That's my request.
