### ISSUE TITLE
Videos have no audio

### ISSUE THREAD

**Issue by cabinetto** [spikecodes/libreddit#207]
Every single video I clicked on had no audio at all, and the volume icon is blank. Downloading the video from libredd.it reveals no audio either.
Example: https://libredd.it/r/DiretoDoZapZap/comments/mxa2ny/n%C3%A3o_d%C3%A1_nem_tempo_de_parar_quando_precisamos_fazer/

![image](https://user-images.githubusercontent.com/76763406/116011922-d0017f00-a5fd-11eb-9e23-b8ab2c71a728.png)

**Comment by Mennaruuk** [comment]
Duplicate #147

**Comment by spikecodes** [comment]
Thanks for the bug report! Yeah, this looks like a duplicate.
