### ISSUE TITLE
Card and Compact Layouts

### ISSUE THREAD

**Issue by curlpipe** [spikecodes/libreddit#21]
When I browse a subreddit, I notice that the images are blurred and lack resolution which the icons on the official reddit page shows perfectly.

Here's an example:
https://libredd.it/r/leopardsatemyface

![image](https://user-images.githubusercontent.com/11898833/103464841-c8f0f100-4d2e-11eb-8ec7-a328373a4ef0.png)

vs reddit:
https://reddit.com/r/leopardsatemyface

![image](https://user-images.githubusercontent.com/11898833/103464860-e625bf80-4d2e-11eb-8745-60ad49cff1e3.png)

Perhaps there is a better way to lay these images out. 

Thank you!

**Comment by spikecodes** [comment]
Thank you for the PR! I totally see what you mean. Libreddit fetches the thumbnail image when you're scrolling through a subreddit (emulating Reddit's "Classic" layout) but it looks what you are referring to is Reddit's "Card" layout.

This is part of a larger goal to add layouts along with a configuration menu, I've opened an issue for configuration: #22 

Thank you for the contribution!

**Comment by spikecodes** [comment]
Card and compact layouts are now available! The layout can be customized in the settings menu.

Card:
![image](https://user-images.githubusercontent.com/19519553/103727990-8b3fd280-4f91-11eb-9def-a18caff8fa5e.png)

Compact:
![image](https://user-images.githubusercontent.com/19519553/103728004-98f55800-4f91-11eb-967d-22e2df3a6fba.png)

Changes should be live on the official instances shortly.
