### ISSUE TITLE
Armv7 docker build?

### ISSUE THREAD

**Issue by kjboa** [spikecodes/libreddit#221]
Good day, the other day I found this project and wanted to try it out on a free Raspberry I had lying around. However (logically) the arm64 image does not work on the armv7 raspberry. I tried to change the dockerfile so that it compiles but failed. Is there any chance of getting an official armv7 image?

**Comment by thehoff** [comment]
I could probably have a look at cross compiling this up if needed. Reach out and I can help with it.

**Comment by dbrennand** [comment]
Hi,

So I think I'm making some progress with this. I have 0 rust experience so please bear with me if I don't understand your replies.

So I am using the docker image from this [repo](https://github.com/Ragnaroek/rust-on-raspberry-docker) to cross compile for Raspberry Pi.

I believe I have successfully cross compiled but am now unsure what I should do next.

Steps:

```
1. git clone git@github.com:spikecodes/libreddit.git
1. docker pull ragnaroek/rust-raspberry:1.52.1
# I'm using WSL 2 integration on Windows 10
2. docker run -v /mnt/c/Users/user/GitHub/libreddit:/home/cross/project -t ragnaroek/rust-raspberry:1.52.1 build --release
```

**Comment by dbrennand** [comment]
Made some more progress.

Here is the [dockerfile](https://github.com/dbrennand/libreddit/blob/dockerarmv7/Dockerfile.armv7) I have currently.

I'm using the following command to build the image for armv7:

`docker buildx build -f .\Dockerfile.armv7 --no-cache --platform linux/arm/v7 -t devlibreddit:armv7 .`

I then save the image: `docker save -o libredditarm.tar devlibreddit:armv7` and scp up to my Raspberry Pi. However, there is something I'm missing as when I run the image I recieve the error: `standard_init_linux.go:219: exec user process caused: no such file or directory`. 😞 

I haven't got much experience cross compiling and am not sure if I have done any work of use for this. I hope so 👍🏻 

Anyone got any suggestions? 😄

**Comment by kjboa** [comment]
That's the same error i encountered. As far as i know 219 means the architecture is in incompatible

**Comment by dbrennand** [comment]
Got any suggestions @thehoff ?

**Comment by dbrennand** [comment]
So, I have kept going and decided to look at using the `rust:slim` as the builder image.

I'm currently using this [dockerfile](https://github.com/dbrennand/libreddit/blob/dockerarmv7/Dockerfile.armv7rust).

I have been following steps from this guide: https://medium.com/swlh/compiling-rust-for-raspberry-pi-arm-922b55dbb050

However, I'm still hitting a wall with `standard_init_linux.go:219: exec user process caused: no such file or directory` 😕

**Comment by dbrennand** [comment]
Yarika! I got it working!

Here is my [dockerfile](https://github.com/dbrennand/libreddit/blob/dockerarmv7/Dockerfile.armv7rust).

**Comment by thehoff** [comment]
Sorry I've been dark after offering to help. Had some home issues. I'll run this up tonight.

**Comment by spikecodes** [comment]
Thank you for your hard work @dbrennand! Your contribution looks fantastic and would allow Raspberry Pi hosting, an important feature for self-hosted software! :smile: 

I just tested these steps (or the equivalent for `docker build` rather than `docker buildx`) and Libreddit ran successfully on my Raspberry Pi 3b.

I'd be happy to test and review a PR for this!
