### ISSUE TITLE
Fix for bleeding of Zalgo Text all over comments

### ISSUE THREAD

**Issue by Baerbeisser** [spikecodes/libreddit#228]
The spreading phenomenom of zalgo text bleeds all over other comments in libreddit. Looks like this:
![zalgo](https://user-images.githubusercontent.com/22264628/119357335-b8bebb80-bca7-11eb-9be3-b78c429dd6db.png)

Fix: CSS
```
.comment_body {
    overflow: auto;
}
```
with no side-effects i'm aware of.

**Comment by spikecodes** [comment]
Thanks for catching this! Are you able to link me to an example of where that happens?

**Comment by Baerbeisser** [comment]
At the moment not, look in r/technope or r/softwaregore
... did you apply the fix already? Examples do not bleed anymore.

**Comment by spikecodes** [comment]
No worries! I found [an example](https://libredd.it/r/NoStupidQuestions/comments/5hqamz/how_do_you_create_crazy_looking_text_like_this/db2klkm) to test on:
![image](https://user-images.githubusercontent.com/19519553/120029904-43742300-bfe6-11eb-807a-087e6c119107.png)
With fix:
![image](https://user-images.githubusercontent.com/19519553/120029932-50911200-bfe6-11eb-98bd-9ef2984226f5.png)

Just pushed your fix. It works great, thanks!
