### ISSUE TITLE
Feature Request | Subscribe to subreddits

### ISSUE THREAD

**Issue by gerroon** [spikecodes/libreddit#23]
Hi
It would be nice of one can add favorite subs and posts within the app. some kind of side bar access would be good I think.

thanks

**Comment by spikecodes** [comment]
I like this idea, good suggestion!

**Comment by spikecodes** [comment]
Not sure how it can be done without accounts but perhaps through the use of cookies (see #22).

**Comment by gerroon** [comment]
Hi

The reason I asked about it because as a user I do not want to use an account or pollute my browser bookmarks. It would be nice if it is implemented from the user point of view. Just a suggestion.

Thanks

**Comment by spikecodes** [comment]
Libreddit supports multireddits as of 565f4f2 so you can actually grab a "multireddit of your subscriptions" [here](https://reddit.com/subreddits) (bottom right) and visit that in Libreddit:

Eg. https://libredd.it/r/archlinux+Monero+linux+bitcoin+Unexpected+unixporn

**Comment by gerroon** [comment]
Thanks for the update, just did a pull and all seems broken?

https://i.imgur.com/OR3x11b.png

**Comment by spikecodes** [comment]
> just did a pull

Do you mean you ran `git pull` on your own instance?

I visited the example link I sent above and it rendered as:
![image](https://user-images.githubusercontent.com/19519553/103496315-93154080-4df2-11eb-843b-96b21bf0597c.png)

**Comment by gerroon** [comment]
I am using Docker docker pull spikecodes/libreddit

The prev version was like the one you have in your post, the current docker pull has broken pages like I posted above.

**Comment by spikecodes** [comment]
Just tried docker pulling and it shows fine for me but I will be pushing an update shortly so perhaps that will fix it on your end.

**Comment by gerroon** [comment]
Still broken, no idea. Something must have changed  that it is broken since all I did was to pull the new version. 

I can try to debug it if you can tell me how to get some logs.

**Comment by spikecodes** [comment]
Are you able to open a new issue for this? Can you include a screenshot, your browser and your operating system?
