### ISSUE TITLE
Add my instance to instance list

### ISSUE THREAD

**Issue by trevorthalacker** [spikecodes/libreddit#230]
I have a libreddit instance at https://libreddit.trevorthalacker.com that I would like added to the instance list

**Comment by spikecodes** [comment]
Thank you for selfhosting Libreddit!

What country is your instance hosted in?

I tried visiting the link but was met with a Cloudflare error:
![image](https://user-images.githubusercontent.com/19519553/120139417-f485e380-c1c7-11eb-8db9-3493962cb072.png)

**Comment by trevorthalacker** [comment]
It's currently hosted in New York (where my VPS is), so the United States.
I got the server back online (i have no idea what happened there)
30 May 2021, 21:23 by ***@***.***:

**Comment by spikecodes** [comment]
Thanks! I've added it to the instance list :)
