### ISSUE TITLE
[Feature request] Pass Reddit images through Libreddit

### ISSUE THREAD

**Issue by mimetism** [spikecodes/libreddit#236]
## Is your feature request related to a problem? Please describe.
Images hosted on Reddit are tied to "i.redd.it". If Reddit domains are blocked, these images cannot be seen.

## Describe the solution you'd like
It would be great if the images could be passed through Libreddit, just like the written content.

## Additional context
For instance, the other alternative service, "teddit", passes the images in a link of the type "teddit.net/pics/".

**Comment by spikecodes** [comment]
Thanks for opening this issue but this is already implemented. Libreddit, like Teddit, already relays media which is why Reddit domains are blocked in the CSP (like other external domains, for security). Example: https://libredd.it/img/upk37bqxk8971.jpg

If you visit https://libredd.it, you'll see all media is relayed

**Comment by mimetism** [comment]
Thank you for responding!

I realised that the feature had already been implemented shortly after opening the ticket. However, the reason why I opened it was that some images are still not displayed. For example, this is a random post chosen from r/popular: [https://libredd.it/r/EscapefromTarkov/comments/odn91o/therapist_level_1_now_sells_lucky_scav_junk_box/](url); the preview is an empty image, while the post itself contains [https://i.redd.it/7bo3z0b7x7971.png](url), which I cannot reach as the domain is blocked on my OS.

In addition, the empty preview is also seen when scrolling a list of posts and seeing one that links to an external source; one example is this other randomly chosen post: [https://libredd.it/r/news/comments/odvck0/i_cant_live_on_709_a_month_americans_on_social/](url). Should the preview be empty?

**Comment by spikecodes** [comment]
Thanks for reporting that! Are you able to open a dedicated issue for that bug?

**Comment by midi** [comment]
Created #246
