### ISSUE TITLE
New Libreddit Instance

### ISSUE THREAD

**Issue by cyberhost-uk** [spikecodes/libreddit#238]
URL: https://libreddit.cyberhost.uk
Country: Finland
DNS: Cloudflare (No Proxy)

Let me know if you need any additional info :)

**Comment by kgnfth** [comment]
URL: https://libreddit.awesomehub.io
Server Location: Finland
DNS: Selfhosted [PowerDNS](https://github.com/PowerDNS/pdns)

**Comment by spikecodes** [comment]
> URL: https://libreddit.cyberhost.uk
> Country: Finland
> DNS: Cloudflare (No Proxy)
> 
> Let me know if you need any additional info :)

Thank you for selfhosting Libreddit! :)

**Comment by spikecodes** [comment]
Thanks @kgnfth! Are you able to open a separate issue?

**Comment by kgnfth** [comment]
> Thanks @kgnfth! Are you able to open a separate issue?

Done
