### ISSUE TITLE
Feature Request | Display Awards on posts

### ISSUE THREAD

**Issue by curlpipe** [spikecodes/libreddit#24]
It would be amazing if libreddit could display awards on posts that have them. 

One of the last cosmetic additions for sure!

Great work :)

**Comment by spikecodes** [comment]
Good suggestion!

**Comment by Mennaruuk** [comment]
There's a good Reddit front end called [threadclient](https://github.com/pfgithub/threadclient), they have [an interesting way](https://thread.pfg.pw/reddit/r/interestingasfuck/comments/le3n2o/making_chocolate_from_scratch/) of getting awards to show up.

**Comment by spikecodes** [comment]
Interesting, thanks! I haven't heard of threadclient before. It appears that they send all requests to Reddit through your browser.

**Comment by microraptor** [comment]
Because awards might become quite annoying, maybe a settings option to only show the total amount of awards or total worth in coins would be nice too.

**Comment by DiegoMagdaleno** [comment]
Im a little bit busy, but I can take up this request if you want :)

**Comment by spikecodes** [comment]
That would be awesome, thank you!

**Comment by DiegoMagdaleno** [comment]
Just showing a little bit of the progress I have done :D 

<img width="372" alt="Screen Shot 2021-03-27 at 2 59 43 PM" src="https://user-images.githubusercontent.com/38844659/112734778-79752800-8f0d-11eb-93a9-fbfd3a4abe45.png">
<img width="952" alt="Screen Shot 2021-03-27 at 3 02 53 PM" src="https://user-images.githubusercontent.com/38844659/112734786-885bda80-8f0d-11eb-8e53-3f573217c18d.png">

**Comment by spikecodes** [comment]
That is looking fantastic, thank you so much!

**Comment by mikupls** [comment]
Hey, thanks for the contribution, looks great. 

I saw some possible inconsistencies though, and am wondering if it's intended. In the subreddit browsing view, there are no award counts for me. In the post itself there are; but only for the post itself, and not the comments:

![Screenshot from 2021-11-25 23-27-49](https://user-images.githubusercontent.com/93015331/143504835-4065ce03-f00b-4c28-be84-4ab3e036ccff.png)

![Screenshot from 2021-11-25 23-28-07](https://user-images.githubusercontent.com/93015331/143504845-b6caa446-82a8-47d0-a93b-60343271442e.png)

Any thoughts?

**Comment by spikecodes** [comment]
Yep! That functionality is intended because showing the numbers in a feeds make the awards go on so long that they push everything to the next line and often expand the content. An alternative approach might be to truncate the number of awards (and with it, the award counts next to them) to a max of 4 awards. ← That's what Reddit does

> my only suggestion would be to show the real numbers when hovering, if possible
Good idea, thanks!

**Comment by mikupls** [comment]
No strong opinion on the first paragraph. Hard to tell which version will feel better to use, and the current one feels fine enough for now to me personally.

Let me know if I shall open a new issue to track the hover numbers.

**Comment by microraptor** [comment]
It would be nice to have an option, where it only shows one number. Either the worth of all awards received for the post/comment (if that is possible) or how many awards in total. Then on hover it could show which wards it received.
