### ISSUE TITLE
How to pass preferences using url parameters?

### ISSUE THREAD

**Issue by specter78** [spikecodes/libreddit#240]
DDG, invidious allows passing preferences with url parameters.

From what I know so far, libreddit does not allow the same, but gives a url to set cookies for the same.

However, this doesn't work if one clears cookies often.

So, how to pass preferences using url parameters, like `url/?comment_sort=top`.

**Comment by spikecodes** [comment]
The comment sort method can be passed in the URL using the same format that Reddit urls would be sent. Example to sort r/privacy by top post: https://libredd.it/r/rust/top

Does this answer your question?

**Comment by specter78** [comment]
Yes. Thank you.
