### ISSUE TITLE
Reduce a click when sorting comment

### ISSUE THREAD

**Issue by specter78** [spikecodes/libreddit#241]
Presently, to sort comments, one has to first click on sort type and then the arrow.

This can be reduced to just one click. Select sort type and page should refresh without need to click on the arrow

**Comment by spikecodes** [comment]
Thanks for opening this issue! Unfortunately, this is not possible without the use of JavaScript and one of Libreddit's goals is to only use JavaScript for media-audio playback so this is not planned.
