### ISSUE TITLE
Any documentation on deploying to Netlify?

### ISSUE THREAD

**Issue by azeemOshaan** [spikecodes/libreddit#243]
Does anyone have any instructions on the right way to deploy this repo on Netlify? 
Netlify does support Rust as far as I know. Any help will be appreciated. Thanks

**Comment by spikecodes** [comment]
Netlify supports Rust but I think only for serverless functions of a website rather than hosting an application like Libreddit so I don't think it would work

**Comment by spikecodes** [comment]
Closing for now
