### ISSUE TITLE
"Too Many Requests" since couple of days...

### ISSUE THREAD

**Issue by noqd** [spikecodes/libreddit#244]
Bug? I don't know. Since some days I can not access https://libredd.it/

Error always says: 
Too Many Requests
Head back home?

Picture: https://imgbox.com/j3RnLzE1

Reproduce?
It happens on every Browser I tested, Firefox, Librewolf, Edge, Chromium etc.

**Comment by spikecodes** [comment]
Thank you for reporting this, it appears that Libreddit's two official instances are being ratelimited by Reddit. I'll have to investigate a way to prevent this from happening but in the meantime, I recommend using one of the unofficial instances listed in the README.

**Comment by matheusAMDS** [comment]
I don't understand anything about Rust so maybe i'm missing something, but shouldn't the fetched results be cached on a database like Redis? Or it is in being cached in another way and i'm stupid?

**Comment by spikecodes** [comment]
Yeah, Libreddit currently caches results using the Rust crate [cached](https://github.com/jaemk/cached). Though, once the cache timeout ends, Libreddit shows the error message that Reddit sends (too many requests).

**Comment by spikecodes** [comment]
From what I can tell, Libreddit's official instances haven't been hit with this problem for quite a while so I'll be closing this issue.
