### ISSUE TITLE
Migrate official instance to Capsul to preserve privacy

### ISSUE THREAD

**Issue by 5trongthany** [spikecodes/libreddit#248]
## Is your feature request related to a problem?

While libreddit does a great job of helping improve the privacy of browsing reddit, it's noted that the hosting provider does monitor the usage of traffic.

## Describe the solution you'd like
Capsul.org is a hosting provider that is run as non-profit and does not monitor traffic. From their FAQ page: "We will never snoop on your traffic or inspect what's going on inside of our customer virtual machines - we don't want to."

## Additional context
Capsul home page: https://capsul.org
Capsul FAQ Page: https://capsul.org/faq

Capsul pricing:
![image](https://user-images.githubusercontent.com/65565784/126217387-ab526c76-9dba-4315-aa7d-b751992bb0ad.png)

**Comment by spikecodes** [comment]
Thanks for the suggestion! At the moment, I can't afford a virtual private server but it would be nice to transfer to one eventually. I'm closing this issue for now but if I do switch to a VPS for the official instances, I'll post an update here.
