### ISSUE TITLE
Search only shows first page results

### ISSUE THREAD

**Issue by gerroon** [spikecodes/libreddit#25]
Hi

I did "blender" search in unrealengine and it shows many pages of results. The same search result in a single search results page in Libreddit. Not sure if there is some limitation.

https://old.reddit.com/r/unrealengine/search?q=blender&restrict_sr=on&count=50&after=t3_jts647

vs

http://IP/r/unrealengine/search/?q=blender&restrict_sr=on&sort=new

**Comment by spikecodes** [comment]
Great bug report! I realize that for searches, I need to increase the "count" variable each page to parse more results.

**Comment by spikecodes** [comment]
Just fixed with a3384cb! Changes should be live shortly.
