### ISSUE TITLE
Enabling HLS on a multireddit takes you to a broken page

### ISSUE THREAD

**Issue by bersLucas** [spikecodes/libreddit#251]
## Describe the bug

When you're on a multireddit and you click on _Enable HLS_ under a video post, it redirects you to 
`/r/subredditA%20subredditB%20subredditC` instead of `/r/subredditA+subredditB+subredditC` which is an Error page.
## To reproduce

* Visit a multireddit with HLS disabled and _Hide notification about possible HLS usage_ also disabled
* Click on _Enable HLS_

## Expected behavior

Clicking on _Enable HLS_ would redirect back to the previous page

**Comment by spikecodes** [comment]
Thanks for reporting this! :)
