### ISSUE TITLE
Unraid Installation Guide - Wiki creation for links?

### ISSUE THREAD

**Issue by Joshndroid** [spikecodes/libreddit#253]
## Is your feature request related to a problem? Please describe.

You don't have an Unraid installation guide

## Describe the solution you'd like
A wiki that is able to be edited by further contributors and then a link into the installation section for unraid users.

## Describe alternatives you've considered
N/A

## Additional context

Hello.
I came across your program while initially searching for a privacy focused reddit front end after checking out nitter/invidious/etc

I utilise Unraid as my main server PC as many others do out there.
If you have not heard of Unraid before - https://unraid.net/
Unraid community apps - https://unraid.net/community/apps

I have setup your libreddit docker to run within unraid. At present I have written a bit of a guide for others out there who wish to give this a whirl. I will post it here as you dont have a wiki setup where I can post it in there. I was potentially going to submit a community apps version compatible to make the process a bit easier for others but may leave mine to run for a while longer before I jump to that.

If possible, could you start a wiki that I could post the guide to and potentially allow it to be linked to to the installation section of your readme?

Here is what I have working within my setup thus far;

-----------------------------------------------------------------------------------------

Libreddit – Unraid Docker Installation

This Unraid Docker Installation guide will mostly assume a few things;
1.	You have docker enabled within Unraid
2.	You have enabled community apps within Unraid
3.	You have enabled within settings the ability to utilize dockerhub for search results (see settings within apps tab)
4.	OPTIONAL - You have a reverse proxy container and network to allow for certificate handling & SSL connections
With that in mind, the installation of Libreddit is rather simple once you have the above setup.
5.	Head over to apps and search for Libreddit
6.	Click to begin the installation of Libreddit within the search result. (The repo is spikecodes/libreddit)
7.	Set the toggle on the right in the template as ‘advanced view’ (It defaults to basic view)
8.	Set your ‘Icon URL’ as  https://github.com/spikecodes/libreddit/blob/master/static/logo.png?raw=true (This will provide you with the Libreddit logo)
9.	Set your ‘WebUI’ as http://[IP]:[PORT:8080]/ (This could be changed to whatever suits your local server port requirements - see below)
10.	Set ‘Extra Parameters’ as --restart=always
11.	Set your network type as needed (OPTIONAL - Set network type as your network that you utilize for your SSL certs (for me its proxnetwork).)
12.	Add in your static IP address that you will utilize for Libreddit. (It makes it easier to get to your hosted instance)
13.	Now add in a ‘port’ as;
•	Name – Port
•	Container Port – 8080
•	Host Port – 8080 (this could be changed to whatever suits your local server port requirements if your 8080 is already in use)
•	Default Value – 8080 (this could be changed to whatever suits your local server port requirements - as above)
•	Connection Type – TCP
•	Description – Container Port: 8080
14.	Click apply to download/install/start the container.
15.	OPTIONAL – Head over to your SSL cert provider container of choice and set-up as necessary to server certs to your Libreddit instance for your domain.

**Comment by Joshndroid** [comment]
I have since created a template for Unraid users to utilise, however those are based on this guide that I had developed along the way (which keeps this valid not only from an unraid perspective but could also be a bit of a help in situations like using dockerman or portainer). From my understanding that I may need to create you a 'Unraid-docker-installation.md' or something similar in a docs folder which would allow various docs to be created and submitted easily to the project as it does not appear that you are an organisation and without that wikis can't be authored my others as far as im aware.

**Comment by Joshndroid** [comment]
see - https://github.com/spikecodes/libreddit/pull/255

**Comment by spikecodes** [comment]
Thank you for this detailed installation guide for Unraid! I followed https://docs.github.com/en/communities/documenting-your-project-with-wikis/changing-access-permissions-for-wikis to enable Wiki contributions so you should now be able to directly add this to Libreddit's wiki. Ergo, I don't #255 is necessary now that the Wiki is publicly editable.
