### ISSUE TITLE
Cross Posted Videos are not probably displayed

### ISSUE THREAD

**Issue by SZanko** [spikecodes/libreddit#258]
## Describe the bug

Cross posted videos are not probably displayed, instead of the video there is only a link to the video.

## To reproduce

1. Visit [example Crossposted Video](https://libredd.it/r/wien/comments/p3gfx9/public_transportation_in_europe/)
2. Click the Link to get Redirected to Reddit

## Expected behavior

Display the video in the page instead of clicking a link which leads to [reddit](https://reddit.com)

**Comment by spikecodes** [comment]
Thanks for reporting this! This video playback would be already covered by #13 so I'm going to close this issue in favor of that one
