### ISSUE TITLE
/r/3DPrinting wiki pages are broken

### ISSUE THREAD

**Issue by HeavenVolkoff** [spikecodes/libreddit#259]
## Describe the bug
All wiki sub-pages, not the main one, are broken in /r/3DPrinting. Their HTML code is rendered as plain text.

## To reproduce

1. Go to https://libredd.it/r/3Dprinting/wiki/index
2. Click on any of the links
3. Wiki page HTML is rendered as text

## Expected behavior
Should render /r/3DPrinting's wiki page correctly

## Additional context
I didn't have much time to investigate, but a curious element that is present in all pages is a `<!-- SC_OFF -->` `<!-- SC_ON -->` HTML comment that wraps all the content. According to a quick search, this seems to be something related to `space compression`.
https://github.com/reddit-archive/reddit/blob/master/r2/r2/lib/filters.py#L69-L91
https://reddit.com/r/redditdev/comments/lowlm2/whats_the_meaning_of_sc_offsc_on_on_rss_feeds/
https://reddit.com/r/redditdev/comments/f7zv87/whats_the_meaning_of_sc_offsc_on_on_rss_feeds/

Probably related with https://github.com/spikecodes/libreddit/issues/196

**Comment by spikecodes** [comment]
Thanks for reporting this! Yeah, this appears to be the same issue as #196 so I'll close this issue in favor of that one.
