### ISSUE TITLE
Restrict proxy to Reddit-hosted media

### ISSUE THREAD

**Issue by janost** [spikecodes/libreddit#26]
The `/proxy` endpoint takes a base64 encoded URL as a parameter and doesn't perform any kind of validation on it, making this an unrestricted open proxy. Although only GET requests can be performed this way, I'm not sure this is a good idea, at least for public facing instances.

**Comment by spikecodes** [comment]
Great suggestion, yeah I noticed the abuse potential of it. I'll work on restricting the proxy to only serve Reddit-hosted media.

**Comment by spikecodes** [comment]
Just patched this! 5ea504e

Now, the proxy restricts URLs to Redd-hosted media domains including: thumbnails, previews, images and videos.

https://github.com/spikecodes/libreddit/blob/5ea504e6e8458b54473913d9527a7218eae1bb50/src/proxy.rs#L7-L14
