### ISSUE TITLE
New instance

### ISSUE THREAD

**Issue by e12005490** [spikecodes/libreddit#260]
Hi! I would like to add my instance to the list:

URL: [https://libreddit.some-things.org](https://libreddit.some-things.org)
Country: Switzerland
Cloudflare: no

It is also accessible as an onion service:

URL: [http://inytumdgnri7xsqtvpntjevaelxtgbjqkuqhtf6txxhwbll2fwqtakqd.onion](http://inytumdgnri7xsqtvpntjevaelxtgbjqkuqhtf6txxhwbll2fwqtakqd.onion)

**Comment by spikecodes** [comment]
Awesome, thank you for selfhosting Libreddit! I appreciate the onion service too :)
