### ISSUE TITLE
libredd.it/user/username/submitted not supported

### ISSUE THREAD

**Issue by Jonta** [spikecodes/libreddit#263]
| URL | Status |
|:-|:-|
| https://reddit.com/user/Planetsahead/submitted/ | works |
| https://libredd.it/user/Planetsahead/submitted/ | does not |

#### Additional context
Button for it on https://libredd.it/user/Planetsahead/ when feature is implemented/bug is fixed, please. =)

**Comment by spikecodes** [comment]
Thanks for sharing this feature suggestion! This would actually be covered by #119, which would allow people to disambiguate between posts and comments made by Reddit so I'll be closing this issue in favor of that one
