### ISSUE TITLE
rss feed?

### ISSUE THREAD

**Issue by somedevreally** [spikecodes/libreddit#27]
any plans for rss feed?

**Comment by spikecodes** [comment]
Building a private front-end for Reddit has allowed me to improve speed, remove ads, reduce resource size and bring privacy. Whereas, creating RSS feeds and/or API would only have the advantage of privacy over using Reddit's official [RSS feeds](https://www.reddit.com/wiki/rss) and [API](https://www.reddit.com/dev/api).

My implementation wouldn't be any better than having a reverse proxy between Reddit's API and the user and therefore, I've decided for now that it wouldn't be worth it to pursue these things.

**Comment by somini** [comment]
Any chance of reconsidering this? Just a proxy over the official feeds while replacing the URL with the current hostname would be enough.

**Comment by spikecodes** [comment]
RSS feeds aren't something that are planned for Libreddit but if you want a private proxied version of Reddit RSS feeds, I recommend taking a look at [Teddit's API](https://codeberg.org/teddit/teddit/wiki#teddit-api).

For example, to get an RSS feed of r/rust, the feed url would be:
https://teddit.net/r/rust?api=&target=reddit&type=rss

**Comment by EsmailELBoBDev2** [comment]
Well, Teddit is great do not get me wrong. But the problem within Reddit's RSS feed itself, they got no image preview or anything and as someone who subbed into /r/memes (yes) i find it hard to look them via rss feed so i made a quick google search and i stumbled into this: https://libredd.it/fvg3ed/ so here you go for future myself or anyone looking you got teddit's and this rss feed!

Also let me know if there another workaround about image previews in reddit's feeds

**Comment by somini** [comment]
> Well, Teddit is great do not get me wrong. But the problem within Reddit's RSS feed itself, they got no image preview or anything and as someone who subbed into /r/memes (yes) i find it hard to look them via rss feed so i made a quick google search and i stumbled into this: https://libredd.it/fvg3ed/ so here you go for future myself or anyone looking you got teddit's and this rss feed!
> 
> Also let me know if there another workaround about image previews in reddit's feeds

Thanks for digging that up. Here's the code:

https://github.com/trashhalo/reddit-rss

**Comment by somedevreally** [comment]
one more 
https://github.com/johnwarne/reddit-top-rss (Generate RSS feeds for specified subreddits with score thresholds)

**Comment by spikecodes** [comment]
Hey @CutestNekoAqua, I think we might be open to an integration with [reddit-rss](https://github.com/trashhalo/reddit-rss), as shared by somini above. There could be a "feed" button (with the RSS icon as an SVG) on the sidebars for subreddits and user profiles that would link to the corresponding RSS feed. Ex: The feed for r/rust would be https://reddit.0qz.fun/r/rust.json

**Comment by mada199122** [comment]
for me a plus one... if you can consider to implement a RSS feed!!!

@spikecodes sorry but how is it possible to use [reddit-rss](https://github.com/trashhalo/reddit-rss) with Libreddit?

**Comment by helmut72** [comment]
From the FAQ:

```
Libreddit doesn't have an API or any RSS feeds because most of Libreddit's benefits come from the web interface (faster speeds, no ads, less resources loaded, etc.) so there really wouldn't be any advantage to using a Libreddit API/RSS feed over a proxied Reddit API/RSS feed.
```

There is an advantage. When using a RSS app like [Reeder App](https://reeder.app), opening the full page opens my Libreddit instance instead of Reddit.
