### ISSUE TITLE
v.redd.it-link does not redirect to libreddit

### ISSUE THREAD

**Issue by Jonta** [spikecodes/libreddit#270]
## To reproduce

- https://libredd.it/r/homelab/comments/m7r23y/every_time_when_i_tell_my_wife_about_anything/
- Links to
- https://v.redd.it/xgc179daasn61
- Takes me to
- https://www.reddit.com/r/TikTokCringe/comments/m7q5p6/every_time_when_i_tell_my_wife_about_anything/

## Expected behavior

- https://libredd.it/r/TikTokCringe/comments/m7q5p6/every_time_when_i_tell_my_wife_about_anything/

## Additional context

Not logged into reddit

**Comment by spikecodes** [comment]
Appears to be fixed by #334
