### ISSUE TITLE
Blank page when you hit enter on an empty search box

### ISSUE THREAD

**Issue by maheshbansod-algoscale** [spikecodes/libreddit#272]
## Describe the bug
Hitting enter on the search box without typing anything gives you a blank page.

## To reproduce

Click on search box. Press Enter.

## Expected behavior
I guess, nothing should happen at all? And if directly a URL is pasted in the browser for search containing an empty query then you might consider redirecting to the home page.

**Comment by spikecodes** [comment]
Thanks for reporting this! Good idea about redirecting empty searches to the home page. With the release of v0.15.2, this should be fixed.
