### ISSUE TITLE
Disable logging on a self-hosted instance

### ISSUE THREAD

**Issue by arunsathiya** [spikecodes/libreddit#273]
Congratulations and thank you, this is a great project! I have setup an instance on my Raspberry Pi. I am wondering if there is a way to disable logging (searches made, posts visited, etc) 

This is assuming there are some kind of logs within my Raspberry Pi at the moment, and also, am I able to check those logs?

**Comment by TheCultLeader666** [comment]
Libreddit doesn't log by default (pretty sure)

**Comment by ArtisanByteCrafter** [comment]
I just checked my docker logs and I can confirm there is exactly one log, at least written to stout:

```
Starting Libreddit...

Running Libreddit v0.15.1 on 0.0.0.0:8080!
```

that's it. :)

**Comment by spikecodes** [comment]
> This is assuming there are some kind of logs within my Raspberry Pi at the moment, and also, am I able to check those logs?
Thanks for double checking! Libreddit releases actually perform no logging (except announcing what version and what port it's listening on) to protect user privacy. I appreciate you hosting it though and I hope you like Libredd it! :)
