### ISSUE TITLE
'\_' in URLs needs to be changed to '_'

### ISSUE THREAD

**Issue by microraptor** [spikecodes/libreddit#281]
## Describe the bug
Apparently new Reddit  changes `_` to `\_` in URLs. An when new Reddit or the app display the URL they change it back again. However libreddit doesn't do that yet (and neither old.reddit).

## To reproduce

See here:
https://libredd.it/r/NatureIsFuckingLit/comments/pfywdx/isistius_brasiliensis_cookiecutter_shark_mouth/hb7tusx
and here:
https://old.reddit.com/r/NatureIsFuckingLit/comments/pfywdx/isistius_brasiliensis_cookiecutter_shark_mouth/hb7tusx/
But if opened in new Reddit the URL is correct:
https://www.reddit.com/r/NatureIsFuckingLit/comments/pfywdx/isistius_brasiliensis_cookiecutter_shark_mouth/hb7tusx/

## Expected behavior
`\_` in Urls needs to be displayed as `_`

**Comment by spikecodes** [comment]
Sorry, I'm trying to reproduce the error but I'm not sure if I understand what the problem is. The Libreddit and old.reddit.com links work fine for me, is that intentional? And aside from the domain, all three links have the same URL paths.

**Comment by microraptor** [comment]
Sorry about the confusion, I was unclear in my description. I don't mean the Reddit links themselves, but the comment they link to.

In libreddit and old.reddit the comment reads:
`https://www.wikiwand.com/en/Cookiecutter\_shark`

In new Reddit and the app the comment shows the working link:
`https://www.wikiwand.com/en/Cookiecutter_shark`

**Comment by mikupls** [comment]
+1, just encountered this for the first time myself: https://libredd.it/r/linux_gaming/comments/qwsc86/game_feels_choppy/hl8ap3v/?context=3

**Comment by mikupls** [comment]
Okay, I think I got it. While we are replacing backslashes all over the place, we never remove the HTML-encoded version of it, which also shows up sometimes ("%5C"). I have a working patch ready for PR soon.
