### ISSUE TITLE
"<" and ">" are escaped as "&amp;lt;" / "&amp;gt;" on list

### ISSUE THREAD

**Issue by noyexcl** [spikecodes/libreddit#286]
## Describe the bug

I guess it's escaped twice (&amp;lt; -> &amp;amp;lt;)

## To reproduce

https://libredd.it/r/rust/search?q=Vec&restrict_sr=on&sort=relevance&t=all

**Comment by spikecodes** [comment]
Very strange. This appears to be the same issue as #196 so I'll be closing this issue in favor of that one.
