### ISSUE TITLE
another error.

### ISSUE THREAD

**Issue by ghost** [spikecodes/libreddit#298]
## Describe the bug

It says: "Hmmmm.... We Couldn't Reach Your Repl
Make sure your repl has a port open and is ready to receive HTTP traffic."
## To reproduce
1. Go to 'https://libredd.it/'
2. See error

## Expected behavior

For it to be working.
## Additional context

![Screen Shot 2021-10-14 at 2 01 57 PM](https://user-images.githubusercontent.com/82217573/137379783-af87ab2d-e283-4871-a2cf-a4e6d67e4292.png)

**Comment by spikecodes** [comment]
Closing in favor on #296, which also talks about the recent outages. I recommend using a different instance for now, to better disperse the load
