### ISSUE TITLE
A way to see deleted reddit posts

### ISSUE THREAD

**Issue by Midou36O** [spikecodes/libreddit#299]
## Is your feature request related to a problem? Please describe.

Sometimes when browsing reddit you can find removed posts that you really need to look at, and it's very frustrating to find those deleted posts
## Describe the solution you'd like
[removeddit](https://github.com/JubbeArt/removeddit) offers you the ability to see those ddeleted messages, what i think would be great is instead of seeing "deleted" message it should show "deleted, want to see the removed message?" And you click on it to see the deleted post.

## Describe alternatives you've considered
Actually going to https://removeddit.com but it has since gone down :(

## Additional context
`null`

**Comment by rehashedsalt** [comment]
This would add significant complexity and intensity to libreddit as well, as data would have to be stored and archived in a backing DB. The closer this app can be to statelessness, the better.

I'd say a good solution to this would be the development of another project that could act as a reddit API shim with some sort of transparent archiving component. It'd be useful for applications outside of libreddit, and would only require an additional configurable for libreddit to support it.

**Comment by spikecodes** [comment]
Great idea! I've added this for posts and comments that have been removed by mods.

**Comment by Midou36O** [comment]
Would it be possible to choose if we want to use another instance of reveddit? (In case the person wants to self host it and not tinker with the source code)

**Comment by austinhuang0131** [comment]
I mean everyone just uses 1 API and that's the Pushshift API, since they are *the one* datamining reddit, so would it be possible to ping the API directly (like [Infinity for Reddit](https://f-droid.org/en/packages/ml.docilealligator.infinityforreddit/))?
