### ISSUE TITLE
Feature Request | Change font configuration (font-display: swap?)

### ISSUE THREAD

**Issue by Mayurifag** [spikecodes/libreddit#305]
## Is your feature request related to a problem? Please describe.
It seems to me there are several ways the font of libreddit may be enhanced. For example, I'm being triggered, when every time site loads firstly it shows the UI without text, you wait-wait some ms and after that text is appeared being styled with 'Inter' font. But I want to see text as fast as possible.

## Describe the solution you'd like
I'd like to see `font-display: swap` option in `@font-face` section in css file or suggest something like that.

Pull request (should be tested) may look something like that:

```css
# static/style.css
@font-face {
	font-family: 'Inter';
	font-display: swap;
	...
}
```

## Describe alternatives you've considered
Not an alternative, but another thing to be discussed is to use different font configuration, that will use font that is most likely already presents on users device, so user won't see site without text and server's network will have less usage.

## Additional context
There are many things developer may also do, i.e. <https://simonhearne.com/2021/layout-shifts-webfonts/>, but font-display option is the most critical for me.

**Comment by spikecodes** [comment]
Thanks for sharing that great blog post by Simon. I understand how you want to see text as soon as possible but I feel like it may look more janky to display the swapping of fonts to users. Also, if text is taking a long time to load, I'd recommend using a different instance (https://libredd.it gets so much traffic that the page gets quite slow at times).

**Comment by Mayurifag** [comment]
Thanks for your answer!
I use your server` instance located at <https://libreddit.spike.codes>, but I wish to selfhost my own instance, with swap font-display — perhaps, I would monkeypatch the docker instance, xd.

Okay, I see, you don't like it, so users won't see that enhancement. Saddy, but thats your repo, so rules up to you. 😃

**Comment by spikecodes** [comment]
Thank you for understanding! Yeah, monkeypatching the Docker image or using Stylus in the browser would work well for tweaking that part of the CSS.

Sorry that I took a month to respond by the way. I fell off track with my open source work and have only gotten back into the groove a couple days ago, but I hope to maintain much more actively going forwards.
