### ISSUE TITLE
Nginx config help, install path?

### ISSUE THREAD

**Issue by Reinin-dev** [spikecodes/libreddit#308]
Hello, while running the libreddit install script on my server I wanted to reverse proxy it through nginx. However I realized that i needed a file path for this, but I can't seem to find where libreddit installed to. If it doesn't install to a file directory, how do I reverse proxy it?

**Comment by spikecodes** [comment]
Hello. Sorry, which libreddit install script are you referring to? Do you mean the SystemD [service script](https://github.com/spikecodes/libreddit/blob/master/contrib/libreddit.service)?

**Comment by Reinin-dev** [comment]
No, I'm referring to the one in your releases titled "libreddit" [here](https://github.com/spikecodes/libreddit/releases/tag/v0.16.0). This is the script you also sent to me over Matrix iirc.

**Comment by spikecodes** [comment]
Ah, you mean the `libreddit` binary? That is actually the entire Libreddit project (not the install script), stored in one file. Wherever that file is downloaded is where Libreddit is installed to.

> However I realized that i needed a file path for this

I am a bit confused, why would you need the file path to reverse proxy it with NGINX? NGINX's [`proxy_pass`](https://nginx.org/en/docs/http/ngx_http_proxy_module.html#proxy_pass) derivative only asks for the URL where the proxied service can be accessed (for Libreddit, it's `http://localhost:8080` by default).

**Comment by Reinin-dev** [comment]
Yeah I at first though of using file path because I was unsure as to how to change the port that libreddit used as my default port was being used for invidious.

**Comment by spikecodes** [comment]
Do you need any more assistance with this issue or should I go ahead and close it?

**Comment by Reinin-dev** [comment]
You can close this, thank you.
