### ISSUE TITLE
Feature Request | Minimal search-bar option for front page

### ISSUE THREAD

**Issue by notthewave** [spikecodes/libreddit#31]
Aside from privacy I prefer alternative front-ends as they remove some of the bad distracting design that social-media sites implement to keep users on their site as long as possible. (E.g. endless scrolling etc.) I feel like trending-tabs / front-pages have a similar or the same goal in mind. They provide low-key interesting content that however is 95% irrelevant. 

I'd suggest replacing the front-page with a centered search-bar like on [nitter](https://nitter.net).

On the other hand Reddit literally describes itself as the front-page of the internet. Therefore some people might expect such a front-page when visiting libreddit. 

Either introduce a toggle or force people to visit r/all by themselves. Or in case you decide not to implement it, let people manually remove it via \<input removal method>, which however likely poses problems when switching instances frequently.

**Comment by spikecodes** [comment]
Yeah I see where you're coming from. A more minimal distraction-less design would be nice.

 You mentioned:
> let people manually remove it via , which however...

I noticed there was a missing word between "via" and ",". What did you mean to send there?

**Comment by notthewave** [comment]
Oh lol didn't notice that >&< comment things out :laughing: see above now

**Comment by notthewave** [comment]
The "fix" to https://github.com/spikecodes/libreddit/issues/23 bit further down is definitely a better solution than the one I proposed.

**Comment by spikecodes** [comment]
> Oh lol didn't notice that >&< comment things out laughing see above now.
> 
> I usually remove distracting elements with ublock-origin. I suppose it's also possible with custom css profiles but I've never done that before.
> 
> Thank you for your efforts!

Haha no worries! Yeah that is an option for sure.

> The "fix" to #23 bit further down is definitely a better solution than the one I proposed.

Ah yeah that works as well.

**Comment by spikecodes** [comment]
In b8cdc605a284b7f93a5dd82ea3621b9873520f7c, I added a way to customize the front page from r/popular to r/all so some progress made but no "Searchbar" option yet.

**Comment by spikecodes** [comment]
This searchbar option is no longer planned so I'm closing this issue.
