### ISSUE TITLE
Feature Request | Replace reddit.com links always automatically with libreddit links

### ISSUE THREAD

**Issue by laalsaas** [spikecodes/libreddit#312]
## Is your feature request related to a problem? Please describe.

Some links starting with reddit.com are not automatically replaced to libreddit links. I haven't spotted a pattern yet, but the link in [this one](https://libredd.it/r/funny/comments/qmwdve/subreddit_of_the_month_november_2021/) won't change, while the link in [this post](https://libredd.it/r/tifu/comments/qolepz/tifu_by_agreeing_to_serve_in_the_army_update/) gets replaced properly. My assumption is that it might have something to do with the post type, like it doesn't work in the reddit posts of the type link, but this is just an assumption i haven't further investigated.

## Describe the solution you'd like

libreddit should always replace reddit.com links to libreddit links, without exceptions.
## Describe alternatives you've considered

The use could convert the link manual everytime, but this would suck.

**Comment by spikecodes** [comment]
Thanks! This appears to mainly happen to `post_url`s.

**Comment by spikecodes** [comment]
Should be fixed by https://github.com/spikecodes/libreddit/commit/7aeabfc4bc62e145bc8f16789c6ef3c574b4dd6a.

**Comment by azizLIGHT** [comment]
I've been testing this and found some cases where libreddit rewrites didn't happen:
https://libredd.it/r/bestof/comments/rqjlz1/9k3d_explains_the_absolute_house_of_cards_that/
https://libredd.it/r/bestof/comments/rqgl4p/udangerous_budget8897_provides_a_fantastic/
https://libredd.it/r/bestof/comments/rq0t9j/umiagomusprime_explains_the_motivation_behind_why/
https://libredd.it/r/bestof/comments/rp4tsj/usnowypinkrose_describes_in_agonizing_detail_how/
https://libredd.it/r/bestof/comments/rpazdu/really_interesting_insight_into_homelessness/
https://libredd.it/r/bestof/comments/rovk2f/ufaroffland_discusses_some_of_the_stigmas_towards/

Something to do with not using https://www.reddit.com as the post link: ie: using np.reddit.com, old.reddit.com or reddit.com without www

/r/bestof gives a variety of links to reddit to test this out FYI

**Comment by spikecodes** [comment]
@azizLIGHT Thanks for catching these alternative Reddit domains! Should be fixed as of [v0.21.3](https://github.com/spikecodes/libreddit/releases/tag/v0.21.3).
