### ISSUE TITLE
NSFW thumbnails do not proxy correctly

### ISSUE THREAD

**Issue by Zegnat** [spikecodes/libreddit#32]
**Steps to reproduce:**

1. Find a photo post marked as NSFW.

**Result:** a broken thumbnail image is shown as the proxy failed.

![Screenshot showing a broken thumbnail on an r/trashy post that was shown on the libredd.it homepage.](https://user-images.githubusercontent.com/490579/103660823-566e5400-4f6e-11eb-907f-4cfea3d9ede8.png)

I ran into this randomly on the libredd.it homepage, and can't actually find this actual post any more. But randomly browsing the site, this problem seems to occur for all NSFW photo posts.

**Expected:** show no image at all when a post is marked as NSFW. (Or an otherwise obscured image.)

**Comment by spikecodes** [comment]
Thanks for the bug report! Fixed with 2b0193f and changes should be live shortly!

NSFW posts don't have thumbnails (they have "nsfw" in place of the image url) but now Libreddit loads no image rather than failing to proxy one.
