### ISSUE TITLE
[New Instance] Mutareddit

### ISSUE THREAD

**Issue by Midou36O** [spikecodes/libreddit#323]
It's been a while i've been using my self hosted instance, and i tought why not open it to the others? So here it is: https://libreddit.mutahar.rocks
Sometimes it may go down (for updates) but not frequently so no worries :)

**Comment by spikecodes** [comment]
Thanks for hosting Libreddit! I can add it to the list, can you tell me:
- Do you use Cloudflare Proxy on it?
- Which country is it hosted in?

**Comment by Midou36O** [comment]
I don't use Cloudflare, hell *i hate cloudflare*, it's hosted in france :)

**Comment by spikecodes** [comment]
Thanks! Just added it to the list https://github.com/spikecodes/libreddit/commit/3a9e6b4ca08201768fee5cf50a643fb875ef916c
