### ISSUE TITLE
Feature Request | Add "Predictions" support

### ISSUE THREAD

**Issue by mikupls** [spikecodes/libreddit#325]
## Is your feature request related to a problem? Please describe.
Reddit now has something called "Predictions". Example in `https://www.reddit.com/r/HolUp/comments/q69c4p/predictions_tournament/`.

## Describe the solution you'd like
Implement proper support for this new feature in libreddit.

## Describe alternatives you've considered
Alternative: Decide that we do not want to see this feature in libreddit? I think generally we strive for feature-parity though. (E.g. there is a feature request open for poll support).

---

Edit: seems like this might only be useful for logged-in users? Seems like voting and even seeing vote counts is not possible for anonymous users. Seeing the question and options is possible though.

**Comment by spikecodes** [comment]
Thanks for sharing this new Reddit feature with me! I wonder why they added this premium-oriented variation of polls other than to gain more money from users. As you noted, Reddit says premium is required to see vote counts for these predictions but I noticed that they're publicly viewable (no account needed) from [the API](https://www.reddit.com/r/HolUp/comments/q69c4p/predictions_tournament/.json):
![image](https://user-images.githubusercontent.com/19519553/142749505-f4248cbf-4ceb-4268-be6e-fb0ed8563390.png)

From a signed-out perspective, they seem almost identical to polls so I think this should be covered by #150 so I'll close this issue.

**Comment by mikupls** [comment]
Makes sense, and I think you already found the reason why they added this :sweat_smile:
