### ISSUE TITLE
Meta: consider adding a "feature parity" label on GitHub

### ISSUE THREAD

**Issue by mikupls** [spikecodes/libreddit#326]
It seems like currently we have various feature requests here on GitHub. Some of these are related to bringing libreddit on feature-parity with vanilla reddit (e.g. #325) while others focus on making libreddit unique/more useful (e.g. #312).

Would it make sense to add an issue label specifically for this use-case (i.e. distinguishing the two)?

**Comment by spikecodes** [comment]
Great idea, thanks! :)

**Comment by mikupls** [comment]
Cool! I see you went ahead with applying these already :)
If you want help with that, I'm happy to do some labeling myself.
