### ISSUE TITLE
proxied videos failing to load on chrome 

### ISSUE THREAD

**Issue by pranavvarmaraja** [spikecodes/libreddit#33]
Just wanted to let you know how much better this is than new and old reddit! The UI is beautifully designed and the speed rivals that of old reddit which is a feat in and of itself. I even set up a redirect which redirects all reddit requests to libreddit! Thanks for the good work! The issue I encountered is as follows:

- proxied videos embedded within posts fail to load on chrome (and edge/presumably most chromium based browsers) for some reason (tested on windows and ubuntu 20.04)
- not 100% sure where the issue is coming from, as on firefox the feature works perfectly
[Example Post w/ Embedded Video](https://libredd.it/r/unixporn/comments/kq6kue/openbox_fake_natural_tiling_no_scripts/)

**Comment by spikecodes** [comment]
Thank you!

Good bug report, I see what you mean. I think the issue may have to do with content type, I'll take a look at it.

**Comment by spikecodes** [comment]
0f506fc should fix this, changes will be live shortly.
