### ISSUE TITLE
Improve text post previews

### ISSUE THREAD

**Issue by mikupls** [spikecodes/libreddit#332]
Some additions to text preview are needed as follow-up to #328:
- I thought that using `selftext` (and not selftext_html) will properly display the newline characters, but seems like this is not the case. Maybe we can fix it with one of the template built-in filters.
- Markdown is not rendered in the preview, but it should be.

Comparison:

![Screenshot from 2021-11-21 12-00-32](https://user-images.githubusercontent.com/93015331/142759193-77d64573-0b1a-465c-a3a1-a17dbf1b586b.png)

![Screenshot from 2021-11-21 12-04-42](https://user-images.githubusercontent.com/93015331/142759271-4d9594c9-572e-4260-94fa-6ddd1bfebd97.png)

Meta: I don't think normal users have permissions to set/change labels on GitHub issues; I would have gone with "feature parity". Not sure if you want to allow this to anyone though because of possible spam?

**Comment by spikecodes** [comment]
Good ideas, thanks!

> Meta: I don't think normal users have permissions to set/change labels on GitHub issues; I would have gone with "feature parity". Not sure if you want to allow this to anyone though because of possible spam?

I've just created [a feature parity issue template](https://github.com/spikecodes/libreddit/blob/master/.github/ISSUE_TEMPLATE/feature_parity.md) so that you'll be able to add issues with that label in the future. Hopefully this helps!
