### ISSUE TITLE
vertical overflow with post preview on Chromium based browsers

### ISSUE THREAD

**Issue by lbrdt** [spikecodes/libreddit#338]
## Describe the bug
Was checking the update changelog and decided to upgrade. However the overflow is creating a mess. Seems to happen only in chromium based browsers?
![screen](https://i.imgur.com/TqA8ifl.png)

## To reproduce

Upgrade to Libreddit 18.0
Open `r/offmychest`

## Expected behavior
No text overflow

## Additional context
Tested on latest stable Chromium (Ubuntu XFCE), Vivaldi  (Windows 10)
Gradient is fine on Firefox (Windows 10)

**Comment by mikupls** [comment]
Well, that is not great :( Thanks for the quick report.

I can confirm that Firefox works, and I think that spikecodes is testing on Brave (which is Chromium based iirc).

Do you have any non-default settings?

I will only get a chance to debug in the next days; maybe spikecodes will be faster to fix this up.

**Comment by lbrdt** [comment]
I tried them on private browser window, so all are on defaults

**Comment by bretjb** [comment]
The same thing happens with mobile safari as well. 
![Screenshot 2021-11-22 at 8 59 02 AM](https://user-images.githubusercontent.com/4078738/142884148-ee7e986d-eed0-4ab0-9862-dd9853aa538d.png)

**Comment by pbui** [comment]
Also experiencing this... Using the "compact" layout is a usable workaround probably because of: https://github.com/spikecodes/libreddit/pull/329

Perhaps the "clean" layout should also have `post_preview` display set to `None`?

**Comment by spikecodes** [comment]
Sorry about this! I've just pushed [v0.18.1](https://github.com/spikecodes/libreddit/commit/9f8d36cb00746d718ef65abadb3f376f05e27a66) which hides this overflow and properly renders the "fade out" of the post previews.

Changes should be live on the main instances shortly.
