### ISSUE TITLE
Option to host on glitch

### ISSUE THREAD

**Issue by Erisfiregamer1** [spikecodes/libreddit#339]
## Is your feature request related to a problem? Please describe.
I've tried to host Libreddit on Heroku, but it always gets stuck when I try to create the app!

## Describe the solution you'd like
I'd like it if a remix on Glitch button could be added, to streamline use and allow for easier hosting.

## Describe alternatives you've considered
Repl.it - Blocked
Self-hosting - I'm on a Chromebook.

## Additional context
[none]

**Comment by spikecodes** [comment]
Thanks for this suggestion! After some playing around with Glitch, I've setup a Libreddit instance there that others can fork (or "Remix", as Glitch calls it) to host it there themselves.

**Comment by Erisfiregamer1** [comment]
Thank you!! (Us poor people with heroku blocked thank you from the bottom
of our hearts)
