### ISSUE TITLE
Light theme

### ISSUE THREAD

**Issue by eightfiftytwo** [spikecodes/libreddit#34]
Awesome work! May I suggest a light mode, maybe a sepia or solarized one? Perhaps even allowing users to define their own themes?

**Comment by spikecodes** [comment]
Thank you! :) Great suggestion! I've added light theme to my to-do list.

**Comment by curlpipe** [comment]
Customising colours would be really cool, I totally agree.

**Comment by spikecodes** [comment]
About to publish light theme! 
![image](https://user-images.githubusercontent.com/19519553/104136940-1f24ec00-534e-11eb-87cc-d5aed3e7e023.png)

Only a few more tweaks needed.

**Comment by spikecodes** [comment]
Light theme released! 08683fa (a bit different than the screenshot above)
