### ISSUE TITLE
[NEW INSTANCE] 

### ISSUE THREAD

**Issue by northboot** [spikecodes/libreddit#342]
I'm hosting a private instance available at https://libreddit.northboot.xyz/ and http://ecue64ybzvn6vjzl37kcsnwt4ycmbsyf74nbttyg7rkc3t3qwnj7mcyd.onion/. Feel free to add it to the list so anyone can use it!
The instance is located in Germany and is not using Cloudflare.

**Comment by spikecodes** [comment]
Awesome, thanks for hosting Libreddit! :) https://github.com/spikecodes/libreddit/commit/99a83ea11b99663080d73101a03ecb2938c6c8c6
