### ISSUE TITLE
Sharing my instance

### ISSUE THREAD

**Issue by kzshantonu** [spikecodes/libreddit#344]
https://www.leddit.xyz/

Hosted on fly.io free tier. Frankfurt region. No CDN

**Comment by spikecodes** [comment]
Thanks for hosting libreddit!

**Comment by mzfr** [comment]
@kzshantonu Can you please share exactly how you hosted libreddit on fly.io.

**Comment by kzshantonu** [comment]
@mzfr  

1. get [flyctl](https://fly.io/docs/hands-on/install-flyctl).
2. create empty directory.
3. Open terminal, cd into that directory.
4. wget [this](https://gist.githubusercontent.com/kzshantonu/389a35169b203555dbf1458a65d6d085/raw/3e041e82078fc4e150a5659c64f729fac03f0ee8/fly.toml) and save as `fly.toml`.
5. edit the file and set an unique app name under `app = `.
6. run `flyctl deploy`

**Comment by mzfr** [comment]
@kzshantonu Thanks for the help :)
