### ISSUE TITLE
Use resized award icons

### ISSUE THREAD

**Issue by spikecodes** [spikecodes/libreddit#346]
## Is your feature request related to a problem? Please describe.
Currently, the 512px icons are used for awards which uses up way more connection bandwidth than is needed.

## Describe the solution you'd like
Have Libreddit use the smaller icons for awards.

**Comment by mikupls** [comment]
I feel like on a big screen and with some zoom level (I use 120% usually) I can notice the lower quality. But not sure if this slight annoyance is worth the extra traffic. I often use libreddit when on low bandwidth, so this is nice overall.

Maybe in the future we could have a switch/setting that allows regulating whether to prefer low-res for previews or not (also for images, which I believe is tracked in a separate issue)
