### ISSUE TITLE
HTML tags showing as text in search results

### ISSUE THREAD

**Issue by burrhole** [spikecodes/libreddit#348]
## Describe the bug
When using libreddit's search function, the text post search results include html tags

## To reproduce
Use the search bar on the main page or any subreddit and look at text posts

## Expected behavior
Some preview text should appear without HTML tags

## Additional context
Using the main instance at libredd.it

Attached is an image of what I'm referring to:
![image](https://user-images.githubusercontent.com/31171855/143793817-af62233b-db1d-45f9-bc02-a226a989bc73.png)

**Comment by spikecodes** [comment]
Thanks for reporting this! Yeah, this appears to be the same issue as #196 so I'll close this issue in favor of that one.
