### ISSUE TITLE
New instance

### ISSUE THREAD

**Issue by alefvanoon** [spikecodes/libreddit#349]
Please add http://libredoxhxwnmsb6dvzzd35hmgzmawsq5i764es7witwhddvpc2razid.onion/ to instance list.

**Comment by spikecodes** [comment]
Thank you for hosting Libreddit! May I ask what country the hidden service is hosted in and whether you use Cloudflare CDN with it?

**Comment by alefvanoon** [comment]
It's on tor (us based)
So I don't use cloudflare...

**Comment by spikecodes** [comment]
Thanks!
