### ISSUE TITLE
Fixed top bar

### ISSUE THREAD

**Issue by Robb1010** [spikecodes/libreddit#35]
Hello, I think it would be a good idea to have the top bar fixed so that we can have easy access to search and home page. 
CSS needed change: 

`nav {
    position: fixed;
    width: 98vw;
    top: 0;
    z-index: 90;
}`

`main {
    margin-top: 8vh;
}`

z-index should prolly be much less, I put it at 90 just to make sure it works. 

For mobile, the main margin value should be a bit higher.

**Comment by spikecodes** [comment]
Great suggestion! Just added this with 59a34a0e855d5990780e34354d2c43a2bebbe180, changes should be live shortly
