### ISSUE TITLE
Cannot import large amount of Subscriptions

### ISSUE THREAD

**Issue by MetalNeo** [spikecodes/libreddit#352]
## Describe the bug
I cannot import my subscriptions because I have too many subscriptions. Opening the link in libreddit does open a new multireddit, but the multireddit cannot be subscribed to.

## To reproduce

1. Subscribe to over 250 subreddits.
2. Open the multireddit link in libreddit.
3. Note that some subreddits are not included.
4. Click/tap Subscribe to Multireddit.
5. Subreddits are not subscribed to.

## Expected behavior
Subscriptions should import.

## Additional context
A workaround to import the full list would also be nice, instead of having to create multiple multireddit links.

**Comment by MetalNeo** [comment]
I have also noticed that there is a limit of how many subscriptions you can have as well.

**Comment by spikecodes** [comment]
Thanks for sharing this issue! Do you have a multireddit link that you could share with that many subs for testing?

**Comment by MetalNeo** [comment]
[Link](https://www.reddit.com/r/2american4you+2Asia4u+2balkan4you+2DGirlsEatingCutely+2DsDrawing+2DsPlayingSports+2European4you+2MiddleEast4you+2visegrad4you+4chan+AcerAspireLaptops+Adguard+admincraft+AdmiralBulldog+AdorableDragons+aestheticrain+ahoge+allbenchmarks+amazon+Amd+Android+androiddev+androidroot+AnimalsBeingDerps+animationgifs+Anime_Despair+animeangels+animearmor+AnimeART+animeartsoriginal+AnimeBlush+AnimeBoba+AnimeBurgers+animeclouds+animegirlsatstations+animegirlsdabbing+AnimeGirlsInKimonos+AnimeGirlsReading+AnimeGirlsWithFood+AnimeHoodies+animehotbeverages+animelegs+AnimeLounging+animemaids+animememes+Animemes+AnimeMusicians+animepointyears+AnimePolos+animeponytails+AnimeSandals+AnimeSleeves+animetanktops+Animewallpaper+animewomeninsuits+announcements+ANormalDayInRussia+aoe2+AppHookup+applehelp+archlinux+ArknightsHQ+Artifact+artknights+AskLibertarians+AskNetsec+AskProgramming+AsrielUndertale+ATT+awenime+awk+awwcoholics+awwnime+ayaneo+AyyMD+BadAssDragons+battlestations+BayoLegs+bedrocklinux+BikiniBottomTwitter+bindingofisaac+BirdsForScale+bisq+Bitcoin+BitcoinBeginners+Bitwarden+BlossoMoe+BlueOrange+Bossfight+brave_browser+Briar+btc+buddhistasfuck+buildapc+buildapcsales+BuildAPCSalesMeta+BuyItForLife+C_Programming+cakewallet+calvinandhobbes+CalvinInRealLife+CalyxOS+CasualConversation+catgirlhoodies+CatsStandingUp+changemyview+Chasriel_Squad+ChimeraOS+chloe+chocolatey+chrome+chromeos+CityPorn+CleanExpansions+coaxedintoasnafu+coding+ColdwindFarm+comics+ComputerSecurity+computing+ComradeSShow+coolguides+Corsair+cpp+CrackWatch+crashbandicoot+CrazyHand+creepywholesome+CrewsCrew+CroppedHentaiMemes+crypto+Crypto_com+crypto_currency+CryptoCurrency+cscareerquestions+csharp+csMajors+cutelittlefangs+cybersecurity+Cybersecurity101+dailyprogrammer+Damnthatsinteresting+dank_meme+dankchristianmemes+DankMemesFromSite19+DarkCircledWaifu+datacenter+DataHoarder+deadbydaylight+debian+debianinrandomplaces+DeclineIntoCensorship+degoogle+Dell+Deltarune+dishonored+disnonored+distroballs+DistroHopping+DivineMoe+DIY_tech+django+djangolearning+docker+DontSayLazy+DoomedHotel+DotA2+dragonswithjobs+DreamyAnimeEyes+DrunkRobots+duolingo+Earthchan+Ebay+emacs+emulation+EmulationOnAndroid+EmulationOnPC+emulators+Emuwarflashbacks+EnglishLearning+Enhancement+EpicMounts+ethereum+EtikaRedditNetwork+EvilMoe+ExpandBonk+ExpandDong+ExplainLikeImCalvin+fantasymoe+Fedora+FGOcomics+FGOfanart+FindMeADistro+Fire+firefox+flask+fluffyboi+Folding+forhire+formalwaifus+fortwayne+foss+fossdroid+FreeGamesOnSteam+freenas+Freenet+freesoftware+FreeTube+Frugal+Frugal_Jerk+fsharp+Futuremoe+Gaben+gamecollecting+GameDeals+GamerSupremeRace+Gamingcirclejerk+GamingLaptops+gamingpc+gao)

The limit on libreddit appears to be 314 subscriptions by my rough count.

**Comment by MetalNeo** [comment]
I realized that my previous link may not have included enough subreddits. Here is one with more (318).

[Link](https://www.reddit.com/r/2american4you+2Asia4u+2balkan4you+2DGirlsEatingCutely+2DsDrawing+2DsPlayingSports+2European4you+2MiddleEast4you+2visegrad4you+4chan+AcerAspireLaptops+Adguard+admincraft+AdmiralBulldog+AdorableDragons+aestheticrain+ahoge+allbenchmarks+amazon+Amd+Android+androiddev+androidroot+AnimalsBeingDerps+animationgifs+Anime_Despair+animeangels+animearmor+AnimeART+animeartsoriginal+AnimeBlush+AnimeBoba+AnimeBurgers+animeclouds+animegirlsatstations+animegirlsdabbing+AnimeGirlsInKimonos+AnimeGirlsReading+AnimeGirlsWithFood+AnimeHoodies+animehotbeverages+animelegs+AnimeLounging+animemaids+animememes+Animemes+AnimeMusicians+animepointyears+AnimePolos+animeponytails+AnimeSandals+AnimeSleeves+animetanktops+Animewallpaper+animewomeninsuits+announcements+ANormalDayInRussia+aoe2+AppHookup+applehelp+archlinux+ArknightsHQ+Artifact+artknights+AskLibertarians+AskNetsec+AskProgramming+AsrielUndertale+ATT+awenime+awk+awwcoholics+awwnime+ayaneo+AyyMD+BadAssDragons+battlestations+BayoLegs+bedrocklinux+BikiniBottomTwitter+bindingofisaac+BirdsForScale+bisq+Bitcoin+BitcoinBeginners+Bitwarden+BlossoMoe+BlueOrange+Bossfight+brave_browser+Briar+btc+buddhistasfuck+buildapc+buildapcsales+BuildAPCSalesMeta+BuyItForLife+C_Programming+cakewallet+calvinandhobbes+CalvinInRealLife+CalyxOS+CasualConversation+catgirlhoodies+CatsStandingUp+changemyview+Chasriel_Squad+ChimeraOS+chloe+chocolatey+chrome+chromeos+CityPorn+CleanExpansions+coaxedintoasnafu+coding+ColdwindFarm+comics+ComputerSecurity+computing+ComradeSShow+coolguides+Corsair+cpp+CrackWatch+crashbandicoot+CrazyHand+creepywholesome+CrewsCrew+CroppedHentaiMemes+crypto+Crypto_com+crypto_currency+CryptoCurrency+cscareerquestions+csharp+csMajors+cutelittlefangs+cybersecurity+Cybersecurity101+dailyprogrammer+Damnthatsinteresting+dank_meme+dankchristianmemes+DankMemesFromSite19+DarkCircledWaifu+datacenter+DataHoarder+deadbydaylight+debian+debianinrandomplaces+DeclineIntoCensorship+degoogle+Dell+Deltarune+dishonored+disnonored+distroballs+DistroHopping+DivineMoe+DIY_tech+django+djangolearning+docker+DontSayLazy+DoomedHotel+DotA2+dragonswithjobs+DreamyAnimeEyes+DrunkRobots+duolingo+Earthchan+Ebay+emacs+emulation+EmulationOnAndroid+EmulationOnPC+emulators+Emuwarflashbacks+EnglishLearning+Enhancement+EpicMounts+ethereum+EtikaRedditNetwork+EvilMoe+ExpandBonk+ExpandDong+ExplainLikeImCalvin+fantasymoe+Fedora+FGOcomics+FGOfanart+FindMeADistro+Fire+firefox+flask+fluffyboi+Folding+forhire+formalwaifus+fortwayne+foss+fossdroid+FreeGamesOnSteam+freenas+Freenet+freesoftware+FreeTube+Frugal+Frugal_Jerk+fsharp+Futuremoe+Gaben+gamecollecting+GameDeals+GamerSupremeRace+Gamingcirclejerk+GamingLaptops+gamingpc+gao+GarlicBreadMemes+GarudaLinux+Gentoo+gigabytegaming+glitch_art+gnu+gog+golang+goodanimemes+goodguyapps+google+GooglePixel+gottagetagrip+gpdwin+GrapheneOS+greentext+hacking+hardware+hardwarememes+hardwareswap+haskell+hatsune+HazbinHotel+headpats+headphones+hellsomememes+HighQualityGifs+HistoryMemes+homeautomation+homelab+homelabsales+HomeNetworking+HomeServer+HotlineMiami+HowToHack+htpc+hurd+HydroHomies+i2p+ImaginaryAngels+ImaginaryAnimals+ImaginaryAnime+imaginaryapex+ImaginaryArchers+ImaginaryArmor+ImaginaryArtists+ImaginaryAstronauts+ImaginaryAutumnscapes+ImaginaryAww+ImaginaryBattlefields+ImaginaryBeasts+ImaginaryBehemoths+ImaginaryBeingDerps+ImaginaryBestOf+ImaginaryBikers+ImaginaryBlep+ImaginaryBodyscapes+ImaginaryCharacters+ImaginaryCityscapes+ImaginaryColorscapes+ImaginaryCowboys+ImaginaryCritRole+ImaginaryCybernetics+ImaginaryDemons+ImaginaryDragons+ImaginaryDwarves+ImaginaryExplosions+ImaginaryFaeries+ImaginaryFeels+ImaginaryFood+ImaginaryFuturism+ImaginaryGaming+ImaginaryGiants+ImaginaryGraveyards+ImaginaryHolidays+ImaginaryHorrors+ImaginaryHunters+ImaginaryHybrids+ImaginaryImmortals+ImaginaryInteriors+ImaginaryKanto+ImaginaryKnights+ImaginaryLandscapes+ImaginaryLeviathans+ImaginaryLibraries+ImaginaryMaids+ImaginaryMedical+ImaginaryMeIRL+ImaginaryMindscapes+ImaginaryMonsterGirls+ImaginaryMonsters+ImaginaryMovies+ImaginaryMythology+ImaginaryNecronomicon+ImaginaryNetwork+ImaginaryNobles+ImaginaryNomads+ImaginaryOrcs)

Side note: the exact limit of subscriptions on libreddit appears to be 317. If you remove one subreddit from the link, then libreddit will be able to subscribe to it.

**Comment by Nogooduser** [comment]
Could this be the same issue Teddit has where surpassing the cookie size of 4096 bytes, you can't store anymore info on it? 

I feared this would be the case when I first discovered libreddit, as I had run into the issue on Teddit as well. 314 subscriptions is decent, I myself only subscribe to about 200-ish subs, but it would suck if the limit was hardcoded into browsers.

**Comment by spikecodes** [comment]
Thanks for sharing that @Nogooduser! I think you may be right. I tested in Firefox and it was ~4097 bytes there, so it's a limitation with the browser more than Libreddit. In that case, I'll be closing this issue but let me know if anyone finds a workaround!

**Comment by throwabird** [comment]
I stumbled upon this issue aswell and wondered if libreddit could use localStorage for managing subscriptions or split the subscriptions in multiple cookies to solve this issue?

**Comment by PAI5REECHO** [comment]
> if libreddit could use localStorage for managing subscriptions

Can't because of JavaScript

> split the subscriptions in multiple cookies

:+1:

**Comment by PAI5REECHO** [comment]
See 3rd item listed in https://github.com/spikecodes/libreddit/pull/391#issuecomment-1096295995

**Comment by PAI5REECHO** [comment]
@spikecodes can this be reopened for someone to solve via the multiple cookies solution?
