### ISSUE TITLE
New Public Instance - lr.cowfee.moe

### ISSUE THREAD

**Issue by rehashedsalt** [spikecodes/libreddit#353]
Hi all,

I intend on running this service for quite a while, and have an instance hosted at [lr.cowfee.moe](https://lr.cowfee.moe). No Cloudflare, DNS goes through route53, box is hosted by Linode in their Dallas DC. I'd like to request that my instance be added to the master list 😄 

I keep no access or error logs from the service, just whatever the container spits to STDOUT. Ingress is proxied through nginx for TLS, but [logs get shredded](https://gitlab.com/rehashedsalt/ansible/-/blob/master/playbooks/prod_web.yml#L111).

I run the app with some [default settings tweaked for my personal use](https://gitlab.com/rehashedsalt/ansible/-/blob/master/playbooks/tasks/web/libreddit.yml#L6).

**Comment by TheCultLeader666** [comment]
Since spike didn't say it, Thank you for hosting libreddit!
