### ISSUE TITLE
Rewrite links to reddit.com to those of the libreddit instance

### ISSUE THREAD

**Issue by rehashedsalt** [spikecodes/libreddit#354]
## Is your feature request related to a problem? Please describe.
It's relatively common in posts and comments on reddit for them to contain a link elsewhere in the site, such as when users link to particular comments in threads. Here's an example post from my instance;

https://lr.cowfee.moe/r/feedthebeast/comments/r5qv85/minecraft_java_edition_118_the_caves_cliffs/

For the sake of privacy, libreddit should rewrite these URLs to keep the user on the instance instead of taking them back to reddit.

## Describe the solution you'd like
The solution would be two parts:
* libreddit would have to be aware of its external-facing URL (ex. `https://libredd.it`); and
* libreddit would then edit the content of links to rewrite reddit urls (ex. `https://reddit.com/r/all`) to those of the instance's equivalent (ex. `https://libredd.it/r/all`)

This functions identically to behavior exhibited by similar anonymization tools, such as Nitter and Invidious.

Additionally, reddit-owned link shorteners like `v.redd.it` should probably be expanded and redirected to the instance as well.

## Describe alternatives you've considered
🤷 

## Additional context
Like I said above: Invidious and Nitter already support similar features. It might be worth glancing at how they do things for implementation specifics.

**Comment by spikecodes** [comment]
Thanks! The issue of rewriting most links seems to be covered by #312 and `v.redd.it` links are covered by #270 so I'll be closing this issue in favor of those.
