### ISSUE TITLE
Add default variable for feeds

### ISSUE THREAD

**Issue by r7l** [spikecodes/libreddit#359]
## Is your feature request related to a problem? Please describe.

Feeds are currently stored in browser (as it is with any other setting). This is a good and valid option for any public instance. But for anyone running a private instance, it might be nice to be able to set their feeds as a default variable, as it is with the settings.

Running my own instance is a great experience and using the default variables makes me having my settings sync across any browser i have around. The only thing missing is my list of feeds being provided as a default. Using libreddit from multiple different machines (PC, Laptop, Tablet) makes it kinda hard to keep sync.

## Describe the solution you'd like

I think it could be done in a variable like `LIBREDDIT_DEFAULT_FEEDS` where you could add the feeds in a single string like it works with the multireddit link: `"news+memes+linux"` and so on. This should turn the instance into a state like it is, when you subscribe to a multireddit link, including the personal frontpage.

Having a default value for feeds would allow anyone with a private instance to add additional subs at a single place (like the Dockerfile) and have it sync everywhere.

**Comment by nemesio65** [comment]
using an ENV variable of `LIBREDDIT_DEFAULT_SUBSCRIPTIONS` works. 

Example: 
`LIBREDDIT_DEFAULT_SUBSCRIPTIONS=news+memes+linux`

**Comment by r7l** [comment]
Thanks allot! I didn't see it in the list that is included in the readme file. It works perfectly.
