### ISSUE TITLE
Favicons?

### ISSUE THREAD

**Issue by Robb1010** [spikecodes/libreddit#36]
I've spent 5 mins doing a small set of favicons, would be a good idea to get them as a placeholder maybe until you are set on a logo?

![libreddit16](https://user-images.githubusercontent.com/11844042/103951869-57061680-5137-11eb-953b-c16cfb17518c.png)

![libreddit32](https://user-images.githubusercontent.com/11844042/103951882-5a999d80-5137-11eb-9203-f44ff8a4927b.png)

![libreddit60](https://user-images.githubusercontent.com/11844042/103951889-5d948e00-5137-11eb-90d1-220754fc5e34.png)

![libreddit144](https://user-images.githubusercontent.com/11844042/103951898-61281500-5137-11eb-9aba-cb0927b2cb14.png)

![libreddit196](https://user-images.githubusercontent.com/11844042/103951907-638a6f00-5137-11eb-80b6-31a1238c2cbc.png)

**Comment by spikecodes** [comment]
Good idea, thank you for these designs! I think it might work better with a capital `l` or otherwise some distinction between this and Ir

**Comment by spikecodes** [comment]
![image](https://user-images.githubusercontent.com/19519553/104395324-55ed3480-54fd-11eb-8a5e-e434553e8bde.png)

Thoughts on something like this?

**Comment by spikecodes** [comment]
Favicon added in 9660725!

**Comment by privsecti** [comment]
How about going full geometric, something like this:

![104395324-55ed3480-54fd-11eb-8a5e-e434553e8bde_](https://user-images.githubusercontent.com/64699891/109099317-3dac3e80-7766-11eb-8b9d-e55b6859b68b.png)

Might be too abstract though. Just my 2 cents.

**Comment by spikecodes** [comment]
Thanks! I really like that geometric style! I made a variant with a flipped `r` for readability which I'll use as the favicon:
![logo](https://user-images.githubusercontent.com/19519553/109187776-22532a80-778a-11eb-9c77-3bfd47c39b60.png)
