### ISSUE TITLE
latest release doesn't have binary, so Repl deployment fails

### ISSUE THREAD

**Issue by bersLucas** [spikecodes/libreddit#373]
## Describe the bug

the `main.sh` file in the default repl.it depends on a binary file to deploy, and version 0.20.3 does have one, causing a 404 and a deployment to fail.

## To reproduce

Fork the default repl.it, and recieve a 404, the main.sh file is below:

```
wget -O libreddit https://github.com/spikecodes/libreddit/releases/latest/download/libreddit
chmod +x libreddit
./libreddit -H 63115201
```

**Comment by spikecodes** [comment]
Thanks for letting me know! Libreddit builds usually take ~5 mins but for some reason, this one got stuck on the `Release` step which made it go over the 6 hour run limit. I'm hoping that was just a one-time issue so I'm pushing v0.20.4 now to see if it resurfaces.

**Comment by spikecodes** [comment]
Yep! That's fixed it.
