### ISSUE TITLE
Cargo version and automation

### ISSUE THREAD

**Issue by e12005490** [spikecodes/libreddit#374]
Same as in #256: the latest version available on crates.io is [0.15.1](https://crates.io/crates/libreddit/versions) instead of 0.20.3. If you are still planning on automating the publishing process then maybe something like [cargo-release](https://github.com/crate-ci/cargo-release) could help you. If not, it would be great if you could update the list of installation/update options in the README. Thanks :-)

**Comment by spikecodes** [comment]
Thanks for reminding me! As of https://github.com/spikecodes/libreddit/commit/992d7889c46cd4ca8f83619ca0c96cf38acb4f80, this should now be automated. :sunglasses:
