### ISSUE TITLE
Post Titles direct to current page instead of external links

### ISSUE THREAD

**Issue by pbui** [spikecodes/libreddit#375]
## Describe the bug

External links (post_title) point back to current page instead of external page.

## To reproduce

Go to any post that links to an external link such as:

https://libreddit.spike.codes/r/news/comments/rpwaqn/germany_to_allow_sale_of_cannabis_for_pleasure/

The post_title "Germany to Allow Sale of Cannabis ‘for Pleasure Purposes’, Opponents Outraged" links back to the current page.

## Expected behavior

Clicking on the post_title should go to external link: https://berlinspectator.com/2021/12/14/germany-to-allow-sale-of-cannabis-for-pleasure-purposes-2/

## Additional context

This appears to be new behavior and prevents being able to access the external link directly from libreddit.

**Comment by spikecodes** [comment]
Thanks for letting me know! It appears the fix to #354 unintentionally broke this.

Fixed as of b3d4f6f91c2e9d9fb338c20256d45ada1f5406b0. Changes should be live shortly!
