### ISSUE TITLE
Crossposts aren't linked

### ISSUE THREAD

**Issue by pbui** [spikecodes/libreddit#376]
## Describe the bug

Post titles to internal links (ie. to another subreddit post) reference the current page.

## To reproduce

For example, this post:

https://libreddit.spike.codes/r/linux/comments/rq51h4/what_to_expect_for_fedora_workstation_in_2022/

Should take you to the post in the Fedora subreddit as shown in the original reddit:

https://www.reddit.com/r/linux/comments/rq51h4/what_to_expect_for_fedora_workstation_in_2022/

Instead, clicking on the post title just goes to the current page.

## Expected behavior

Internal links should reference the other post rather than the current page.

## Additional context

May be further fallout from the work on #354.

**Comment by spikecodes** [comment]
Thanks for letting me know! Should be fixed as of v0.21.2.
