### ISSUE TITLE
Date format string is displayed instead of formatted date in posts and comments.

### ISSUE THREAD

**Issue by adrian-lebioda** [spikecodes/libreddit#378]
## Describe the bug

Date format string is displayed instead of formatted date in posts and comments.

## To reproduce

1. Go to any post for example: https://libredd.it/r/Gloomhaven/comments/nocxer/updated_gloomhaven_rules_based_on_public/
2. Check post and comments date
3. They look like `%b %d '%y`

![date_bug](https://user-images.githubusercontent.com/14971507/147701254-b3c64dc8-aa2b-4b7c-abf1-54f009aee884.png)

4. Same goes for full date time string on hover

## Expected behavior

Instead of  `%b %d '%y` proper date should be displayed.

## Additional context

Not sure since which version this exists, however I noticed it in 0.21.3

**Comment by spikecodes** [comment]
Thanks for catching this! I updated `time` in v0.21.3 so that seems to have broken how dates/times are formatted.
