### ISSUE TITLE
502 error when subscribing to malformed multireddit URL with + characters

### ISSUE THREAD

**Issue by azizLIGHT** [spikecodes/libreddit#379]
## Describe the bug

If the multireddit URL has a + in unexpected places, clicking the `Subscribe to Multireddit` button leads to error. Many instances throw a 502 error Bad gateway, whereas the official instance returns a replit.com page: `Hmmmm.... We Couldn't Reach Your Repl` 
## To reproduce

1. Select any instance link to a subreddit
2. Add `+` to the end of the URL: ie: https://libredd.it/r/pics+ OR https://libredd.it/r/pics+funny+ OR https://libreddit.kavin.rocks/r/pics+ OR https://libreddit.kavin.rocks/r/pics+funny+
3. Add _n_ amount of `+` in between subreddits: https://libredd.it/r/pics++funny OR https://libredd.it/r/pics+++funny OR https://libreddit.kavin.rocks/r/pics++funny OR https://libreddit.kavin.rocks/r/pics+++funny 
4. Combine for more malformed urls: https://libredd.it/r/pics++funny+
5. Click `Subscribe to Multireddit` button
6. See 502 error on instances except on libredd.it
## Expected behavior

Should be able to subscribe to reddits regardless if there's a + at the end of URL or not. Or if user puts too many + in URL
## Additional context

![image](https://user-images.githubusercontent.com/8013867/147832024-0b5a4076-6305-4745-b3b0-139067296b36.png)

I came across this bug while trying to migrate and accidentally left the + at the end of a very large multireddit URL that I generated by script. The + character is common for joining subreddits and users may be typoing and adding too many here and there so this bug may apply to a lot of people

**Comment by spikecodes** [comment]
The `Hmmmm.... We Couldn't Reach Your Repl` actually signals an outage for that instance and I think that's what was happening. I'm able to successfully visit every one of the links so I think your issue was a temporary outage. https://libredd.it is quite popular so sometimes it can't handle all the traffic or becomes slow, so I recommend testing with https://libreddit.spike.codes.

**Comment by azizLIGHT** [comment]
To account for outages, I just rechecked all the instances three times each. I still get the 502 error for malformed urls for instances that are up

Please try a few of the malformed URLs as constructed below and hit the `Subscribe to Multireddit` button under the hot/new header. This is different from the other subscribe button that would appear for individual subreddits in the right sidebar
![image](https://user-images.githubusercontent.com/8013867/147838876-02b17ac2-f3a4-48f1-a840-48264d44940b.png)

I did notice that the errors did not occur on v0.10.5 (test 12) but occured on v0.15.2 (test 8), v0.17.0 (test 19), and newer versions like v0.20 or greater. Perhaps there's some regression between versions v0.10.5 and v0.15.2

One more thing to note is that test 24 gave no error while being on a later version v0.21.4. I'm not sure why this is, maybe there is some modified code on that instance.


| #  | proper url                                      | version | instance up? | subscribe without trailing +? | malformed url                                    | instance up? | subscribe with trailing +? | specific error when subscribing:                                                                                                                                                                                                           |
|----|-------------------------------------------------|:-------:|:------------:|:-----------------------------:|--------------------------------------------------|--------------|:--------------------------:|--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| 1  | https://libredd.it/r/pics+pic                   | v0.21.4 |       ✅      |               ✅               | https://libredd.it/r/pics+pic+                   |       ✅      |              ❌             | Hmmmm.... We Couldn't Reach Your Repl                                                                                                                                                                                                      |
| 2  | https://libreddit.spike.codes/r/pics+pic        | v0.21.4 |       ✅      |               ✅               | https://libreddit.spike.codes/r/pics+pic+        |       ✅      |              ❌             | Hmmmm.... We Couldn't Reach Your Repl                                                                                                                                                                                                      |
| 3  | https://libreddit.dothq.co/r/pics+pic           | v0.20.2 |       ✅      |               ✅               | https://libreddit.dothq.co/r/pics+pic+           |       ✅      |              ❌             | Error 502 Ray ID: 6c65ef9997e4128b • 2021-12-31 19:32:49 UTC                                                                                                                                                                               |
| 4  | https://libreddit.kavin.rocks/r/pics+pic        | v0.21.4 |       ✅      |               ✅               | https://libreddit.kavin.rocks/r/pics+pic+        |       ✅      |              ❌             | 502 Bad Gateway  nginx                                                                                                                                                                                                                     |
| 5  | https://libreddit.40two.app/r/pics+pic          |    ?    |       ❌      |               ?               | https://libreddit.40two.app/r/pics+pic+          |       ❌      |              ?             |                                                                                                                                                                                                                                            |
| 6  | https://reddit.invak.id/r/pics+pic              | v0.21.4 |       ✅      |               ✅               | https://reddit.invak.id/r/pics+pic+              |       ✅      |              ❌             | This page isn’t working reddit.invak.id is currently unable to handle this request. HTTP ERROR 502                                                                                                                                         |
| 7  | https://reddit.phii.me/r/pics+pic               |    ?    |       ❌      |               ?               | https://reddit.phii.me/r/pics+pic+               |       ❌      |              ?             |                                                                                                                      ?                                                                                                                     |
| 8  | https://lr.riverside.rocks/r/pics+pic           | v0.15.2 |       ✅      |               ✅               | https://lr.riverside.rocks/r/pics+pic+           |       ✅      |              ❌             | Proxy Error The proxy server received an invalid response from an upstream server. The proxy server could not handle the request Reason:   Error reading from remote server   Apache/2.4.46 (Ubuntu) Server at lr.riverside.rocks Port 443 |
| 9  | https://libreddit.silkky.cloud/r/pics+pic       | v0.21.4 |       ✅      |               ✅               | https://libreddit.silkky.cloud/r/pics+pic+       |       ✅      |              ❌             | Error 502 Ray ID: 6c661cf4bb4d09b2 • 2021-12-31 20:03:47 UTC                                                                                                                                                                               |
| 10 | https://libreddit.database.red/r/pics+pic       |    ?    |       ❌      |               ?               | https://libreddit.database.red/r/pics+pic+       |       ❌      |              ?             |                                                                                                                                                                                                                                            |
| 11 | https://libreddit.exonip.de/r/pics+pic          |    ?    |       ❌      |               ?               | https://libreddit.exonip.de/r/pics+pic+          |       ❌      |              ?             |                                                                                                                                                                                                                                            |
| _**12**_ | _**https://libreddit.domain.glass/r/pics+pic**_       | _**v0.10.5**_ |       ✅      |               ✅               | _**https://libreddit.domain.glass/r/pics+pic+**_       |       ✅      |              ✅             | _**CAN SUBSCRIBE MALFORMED MULTIREDDITS, as well as banned subreddits**_                                                                                                                                                                         |
| 13 | https://libreddit.sugoma.tk/r/pics+pic          |    ?    |       ❌      |               ?               | https://libreddit.sugoma.tk/r/pics+pic+          |       ❌      |              ?             |                                                                                                                                                                                                                                            |
| 14 | https://libreddit.jamiethalacker.dev/r/pics+pic | v0.21.5 |       ✅      |               ✅               | https://libreddit.jamiethalacker.dev/r/pics+pic+ |       ✅      |              ❌             | Error 502 Ray ID: 6c6633c0ef612239 • 2021-12-31 20:19:20 UTC                                                                                                                                                                               |
| 15 | https://reddit.artemislena.eu/r/pics+pic        | v0.20.2 |       ✅      |               ✅               | https://reddit.artemislena.eu/r/pics+pic+        |       ✅      |              ❌             | This page isn’t working reddit.artemislena.eu  is currently unable to handle this request.  HTTP ERROR 502                                                                                                                                 |
| 16 | https://r.nf/r/pics+pic                         | v0.21.4 |       ✅      |               ✅               | https://r.nf/r/pics+pic+                         |       ✅      |              ❌             | Error 502 Ray ID: 6c6638c1feb10318 • 2021-12-31 20:22:44 UTC                                                                                                                                                                               |
| 17 | https://libreddit.awesomehub.io/r/pics+pic      |    ?    |       ❌      |               ?               | https://libreddit.awesomehub.io/r/pics+pic+      |       ❌      |              ?             |                                                                                                                                                                                                                                            |
| 18 | https://libreddit.some-things.org/r/pics+pic    | v0.21.4 |       ✅      |               ✅               | https://libreddit.some-things.org/r/pics+pic+    |       ✅      |              ❌             | 502 Bad Gateway  nginx/1.18.0                                                                                                                                                                                                              |
| 19 | https://reddit.stuehieyr.com/r/pics+pic         | v0.17.0 |       ✅      |               ✅               | https://reddit.stuehieyr.com/r/pics+pic+         |       ✅      |              ❌             | 500 Internal Server Error                                                                                                                                                                                                                  |
| 20 | https://lr.mint.lgbt/r/pics+pic                 | v0.21.4 |       ✅      |               ✅               | https://lr.mint.lgbt/r/pics+pic+                 |       ✅      |              ❌             | 502 Bad Gateway  nginx                                                                                                                                                                                                                     |
| 21 | https://libreddit.alefvanoon.xyz/r/pics+pic     | v0.21.4 |       ✅      |               ✅               | https://libreddit.alefvanoon.xyz/r/pics+pic+     |       ✅      |              ❌             | Error 502 Ray ID: 6c6644ca09dc02a0 • 2021-12-31 20:30:58 UTC                                                                                                                                                                               |
| 22 | https://libreddit.igna.rocks/r/pics+pic         | v0.21.4 |       ✅      |               ✅               | https://libreddit.igna.rocks/r/pics+pic+         |       ✅      |              ❌             | Hmmmm.... We Couldn't Reach Your Repl                                                                                                                                                                                                      |
| 23 | https://libreddit.autarkic.org/r/pics+pic       | v0.20.2 |       ✅      |               ✅               | https://libreddit.autarkic.org/r/pics+pic+       |       ✅      |              ❌             | Bad Gateway                                                                                                                                                                                                                                |
| _**24**_ | _**https://libreddit.flux.industries/r/pics+pic**_    | _**v0.21.4** |_       ✅      |               ✅               | _**https://libreddit.flux.industries/r/pics+pic+**_    |       ✅      |              _**?**_             | _**No error, but no subscription either. Same for banned subreddits**_                                                                                                                                                                           |
| 25 | https://libreddit.drivet.xyz/r/pics+pic         | v0.20.2 |       ✅      |               ✅               | https://libreddit.drivet.xyz/r/pics+pic+         |       ✅      |              ❌             | Error 502 Ray ID: 6c664f52779e3717 • 2021-12-31 20:38:10 UTC                                                                                                                                                                               |
| 26 | https://lr.oversold.host/r/pics+pic             | v0.20.2 |       ✅      |               ✅               | https://lr.oversold.host/r/pics+pic+             |       ✅      |              ❌             | 502 Bad Gateway  nginx                                                                                                                                                                                                                     |
| 27 | https://libreddit.de/r/pics+pic                 | v0.21.2 |       ✅      |               ✅               | https://libreddit.de/r/pics+pic+                 |       ✅      |              ❌             | 502 Bad Gateway  nginx/1.18.0                                                                                                                                                                                                              |
| 28 | https://libreddit.pussthecat.org/r/pics+pic     | v0.21.2 |       ✅      |               ✅               | https://libreddit.pussthecat.org/r/pics+pic+     |       ✅      |              ❌             | 502 Bad Gateway  nginx                                                                                                                                                                                                                     |
| 29 | https://libreddit.mutahar.rocks/r/pics+pic      |    ?    |       ❌      |               ?               | https://libreddit.mutahar.rocks/r/pics+pic+      |       ❌      |              ?             |                                                                                                                                                                                                                                            |
| 30 | https://libreddit.northboot.xyz/r/pics+pic      | v0.21.4 |       ✅      |               ✅               | https://libreddit.northboot.xyz/r/pics+pic+      |       ✅      |              ❌             | 502 Bad Gateway  nginx                                                                                                                                                                                                                     |
| 31 | https://leddit.xyz/r/pics+pic                   | v0.21.5 |       ✅      |               ✅               | https://leddit.xyz/r/pics+pic+                   |       ✅      |              ❌             | This page isn’t working leddit.xyz  is currently unable to handle this request.  HTTP ERROR 502                                                                                                                                            |
| 32 | https://lr.cowfee.moe/r/pics+pic                | v0.21.4 |       ✅      |               ✅               | https://lr.cowfee.moe/r/pics+pic+                |       ✅      |              ❌             | 502 Bad Gateway  nginx/1.21.3                                                                                                                                                                                                              |
| 33 | https://libreddit.hu/r/pics+pic                 | v0.20.2 |       ✅      |               ✅               | https://libreddit.hu/r/pics+pic+                 |       ✅      |              ❌             | Error 502 Ray ID: 6c665b3f58e167db • 2021-12-31 20:46:18 UTC                                                                                                                                                                               |
| 34 | https://libreddit.totaldarkness.net/r/pics+pic  | v0.20.2 |       ✅      |               ✅               | https://libreddit.totaldarkness.net/r/pics+pic+  |       ✅      |              ❌             | 502 Bad Gateway  nginx                                                                                                                                                                                                                     |
| 35 | https://libreddit.esmailelbob.xyz/r/pics+pic    | v0.20.2 |       ✅      |               ✅               | https://libreddit.esmailelbob.xyz/r/pics+pic+    |       ✅      |              ❌             | 502 Bad Gateway  nginx                                                                                                                                                                                                                     |
| 36 | https://libreddit.nl/r/pics+pic                 | v0.20.2 |       ✅      |               ✅               | https://libreddit.nl/r/pics+pic+                 |       ✅      |              ❌             | 502 Bad Gateway The server returned an invalid or incomplete response.                                                                                                                                                                     |

**Comment by spikecodes** [comment]
Thank you for the very detailed reporting! You're right, the outage seems irrelevant.
