### ISSUE TITLE
Add lr.stilic.ml instance

### ISSUE THREAD

**Issue by Stilic** [spikecodes/libreddit#380]
Hello!

Can you add my Libreddit instance at https://lr.stilic.ml to the README?

**Comment by spikecodes** [comment]
Hey Stillic! Thanks for hosting Libreddit! What country is your server hosted in and does it use Cloudflare as the proxy?

**Comment by Stilic** [comment]
It is hosted on a Kimsufi server (provided by OVH, a french company). It uses Cloudflare proxy.

**Comment by spikecodes** [comment]
Thanks! :)
