### ISSUE TITLE
"could not load platform certs" when URL is accessed, GUI not loading

### ISSUE THREAD

**Issue by ryang3d** [spikecodes/libreddit#385]
### Describe the bug
New install on existing Ubuntu 20.04 system throwing errors when URL (http://0.0.0.0:8080) is accessed, and GUI is unable to load. When running `libreddit` from terminal, I am seeing this as soon as the url is accessed.

`Running Libreddit v0.21.7 on 0.0.0.0:8080!`
`thread 'tokio-runtime-worker' panicked at 'could not load platform certs: Custom { kind: InvalidData, error: "Could not load PEM file \"/usr/lib/ssl/certs/ca-certificates.crt\"" }', /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/hyper-rustls-0.23.0/src/config.rs:31:62
note: run with 'RUST_BACKTRACE=1' environment variable to display a backtrace`

Getting this when attempting to open in browser:
![image](https://user-images.githubusercontent.com/13091837/148318880-6e666052-f9b8-49a0-a96d-649e5df12e62.png)

### To reproduce
Not exactly sure other than: For me, I am just running libreddit and then trying to access the UI from a web browser. Seems like nobody else is running into this issue, so I'm hoping I'm just making a rookie/newb mistake.

### Expecteds behavior
I would expect the libreddit UI to load up in my web browser, and not see those errors about certs/PEM files in my terminal window.

### Additional context
Yes, I am stubborn and am not quite ready to go all in on Docker just yet, and would prefer to stick with a native install for now. This system was recently upgraded from Ubuntu 18.04 to 20.04, and is running a bunch of other services without issue. I can confirm that the ca-certificates.crt file in the location above does exist. Temporarily running `libreddit` as root does not make a difference (same messages appear).

**Comment by spikecodes** [comment]
Strange. Just to confirm; you installed Libreddit through GitHub Releases, correct?

**Comment by spikecodes** [comment]
I'm glad that Docker is working for you! I think I found the original issue: Libreddit connects to Reddit over HTTPS meaning it reads from your device's native certificates, as handled by OpenSSL.

Can you try installing `ca-certificates` and rerunning Libreddit?

```bash
sudo apt install ca-certificates
```

**Comment by ryang3d** [comment]
ca-certificates was already installed, but I ran a reinstall just in case. No dice/same issue

**Comment by ryang3d** [comment]
Going to try to keep rolling with Docker for now.

Before I close this issue though - unrelated (let me know if I should open a new issue): While I'm still fairly new to Docker, any idea why the libreddit container is showing as unhealthy? I've added a few other services as docker containers, but libreddit is the only one that shows up as unhealthy (the rest are healthy or running). That said, it does seem to be working, just curious if there is anything I can/should do about it, or if this is expected behavior.

Thanks for your responses @spikecodes! Really appreciate it :)

**Comment by spikecodes** [comment]
Thank you for the kind words Ryan! :)

That is odd, I'm not able to reproduce this issue either. I followed these exact steps in [Play With Docker](https://labs.play-with-docker.com) but Docker showed libreddit as healthy:
1. `docker pull spikecodes/libreddit`
2. `docker run -d --name libreddit -p 8080:8080 spikecodes/libreddit`
3. Wait a few minutes for it to start
4. `docker ps -a` shows:

![image](https://user-images.githubusercontent.com/19519553/148628729-eddc6273-ce17-42ed-be70-a869c108b008.png)

**Comment by ryang3d** [comment]
Okay, so I tried removing the container, deleting the image, and then running the commands above, but still see "unhealthy" once it is up and running. I am also running Portainer, which makes it look like a wget error might be the cause:
![image](https://user-images.githubusercontent.com/13091837/148630732-26fa19b0-d742-4d15-a69f-6b19ccfd9f21.png)

Not sure what to make of that since it seems like the image works fine for you and others

**Comment by ryang3d** [comment]
Closing for now, but will try to report back if/when I get around the remaining issues.
