### ISSUE TITLE
Redirect HTTP requests to HTTPS

### ISSUE THREAD

**Issue by spikecodes** [spikecodes/libreddit#39]
**Is your feature request related to a problem? Please describe.**
http://libredd.it and http://libreddit.spike.codes don't redirect to their HTTPS versions.

**Describe the solution you'd like**
A command line argument (`--redirect-https`) to redirect requests from HTTP to HTTPS. 

**Additional context**
This command line argument should not be the default as self-hosters would not have TLS by default.

**Comment by Zegnat** [comment]
For some background reading, since libreddit is mostly just plain text, here is an interesting take on only enabling HTTPS redirects in modern browsers, keeping the site also accessible for old platforms: [Plaintext HTTP in a Modern World](https://jcs.org/2021/01/06/plaintext).

**Comment by spikecodes** [comment]
Thanks! Yeah I considered using Strict-Transport-Security (HSTS) for upgrading requests but it only starts upgrading after the user has made their first HTTPS request. Instead, I'd want to manually redirect all HTTP requests to HTTPS if a command line argument (`--redirect-https`) is provided.

**Comment by spikecodes** [comment]
Implemented in 6127f2a!
