### ISSUE TITLE
Export/import subscriptions/preferences

### ISSUE THREAD

**Issue by hellojaccc** [spikecodes/libreddit#396]
## Is your feature request related to a problem? Please describe.

I can't import subscriptions with multireddit url in PWA because i can't open specific url in pwa.

## Describe the solution you'd like

Ability to import/export preferences to a json file like teddit

## Additional context

![image](https://user-images.githubusercontent.com/71537512/149670729-09587c0c-05db-4b0d-b177-880889c56fa3.png)

**Comment by azizLIGHT** [comment]
On the settings page, there is a link there you can use to export your settings, including subscribed subreddits.

It looks like this: 
![Screenshot_20220116-224715](https://user-images.githubusercontent.com/8013867/149705354-04b05d4a-63d1-466f-bc52-8dd7d454d4ed.png)
To restore your preferences and subreddits, just visit the url

Does this satisfy your export/import needs?

**Comment by hellojaccc** [comment]
I can't visit specific url in Progressive Web App (Add to homescreen). They have no url bar so

**Comment by Juliusfrank11** [comment]
This actually did work for me, but libreddit couldn't process all the subreddits I put in the url. It would be nice if you could set the subscriptions in some sort of file or import them from txt

**Comment by spikecodes** [comment]
@hellojaccc Thanks for this PR suggestion! If you paste the restore settings link into Safari and then open the PWA, will it use the same settings/subscriptions as the link included?

@Juliusfrank11 Unfortunately, that issue occurs because [browsers set a maximum cookie size](https://github.com/spikecodes/libreddit/issues/352#issuecomment-997512469) so even if the subscriptions were imported from a text box or a file upload, that problem would still happen.

**Comment by hellojaccc** [comment]
> @hellojaccc Thanks for this bug report! If you paste the restore settings link into Safari and then open the PWA, will it use the same settings/subscriptions as the link included?

Safari and PWA has separate cookie so it won't use the same settings.

**Comment by awalkerca** [comment]
Adding support for this. I’d love to be able to use as a PWA on iOS. A way to synchronize my browser and mobile PWA would be helpful. Perhaps even just an import text input that parses the standard export url?

**Comment by 24788329** [comment]
Am also on iOS and having PWA support for importing/restoring subreddits across devices and resets would be incredibly valuable. Any updates?

@hellojaccc were you able to get this working with an iOS PWA on the home screen? I followed your link but couldn’t figure out how the multiple URL opener tool transferred subreddits to the Libreddit PWA.
