### ISSUE TITLE
Add reddi.tk instance

### ISSUE THREAD

**Issue by lbrdt** [spikecodes/libreddit#397]
Hi, please add this instance to the list.

domain: https://reddi.tk
country: us
cloudflare: yes

**Comment by spikecodes** [comment]
Thanks for hosting Libreddit! :)

**Comment by lbrdt** [comment]
Thank you so much for making Libreddit! 

can you please delete this issue. : )

**Comment by spikecodes** [comment]
I appreciate the kind words!

Sorry but GitHub only allows me to close the issue not delete it.
