### ISSUE TITLE
Mobile Friendly

### ISSUE THREAD

**Issue by Sepero** [spikecodes/libreddit#4]
Dear heavens! This is exactly what I've been needing in my life. Thank you so much!

If I may put in a request, I'd like to humbly ask that the web interface be made mobile browser friendly. Cheers

**Comment by spikecodes** [comment]
:) Wonderful! Thank you for the great suggestion! I will try to make it more cross-platform responsive.

**Comment by spikecodes** [comment]
Alright I've made some progress. I'd now consider Libreddit responsive for mobile. :sunglasses: 
This update will be live shortly!

Before: 
![image](https://user-images.githubusercontent.com/19519553/101269746-debac880-3726-11eb-8f06-e5a587bd650a.png)

After:
![image](https://user-images.githubusercontent.com/19519553/101271870-c30ded00-373b-11eb-9b6a-4883cfc2ffaf.png)

**Comment by Sepero** [comment]
It looks fantastic. You're great!

**Comment by spikecodes** [comment]
:D Thank you!
