### ISSUE TITLE
New instance!

### ISSUE THREAD

**Issue by Jenni32222** [spikecodes/libreddit#401]
I would like to make my Libreddit instance public!

URL: https://libreddit.datatunnel.xyz
Hosted in Amsterdam.
No Cloudflare :)

**Comment by spikecodes** [comment]
Thanks for hosting Libreddit! :)

**Comment by Jenni32222** [comment]
Server has been migrated to a new host, this changed to location to Finland.

**Comment by spikecodes** [comment]
Updated, thanks!
