### ISSUE TITLE
Bug Report | Post sorting buttons don't work in multireddits

### ISSUE THREAD

**Issue by ClockVapor** [spikecodes/libreddit#41]
**Describe the bug**
When using multireddit functionality (e.g. libredd.it/r/funny+pics), the post sorting buttons at the top don't track the multireddit, and they route to base URLs like libredd.it/new, libredd.it/top, etc.

**To reproduce**
1. Visit libredd.it/r/funny+pics
2. Click on any of the post sorting buttons at the top of the page.
3. Note that the selected subreddits in the multireddit are forgotten, and you are now on the default front page (i.e. /r/all or /r/popular).

**Expected behavior**
The selected subreddits in the multireddit should be remembered when clicking any of the post sorting buttons.

**Additional context**
Manually entering a multireddit URL with sorting works as expected (e.g. libredd.it/r/funny+pics/top), it's just the buttons that route incorrectly.

**Comment by spikecodes** [comment]
Thanks! I'll look into this.

**Comment by spikecodes** [comment]
Fixed!
