### ISSUE TITLE
Adding instances.json file

### ISSUE THREAD

**Issue by ManeraKai** [spikecodes/libreddit#416]
We have an extension called [LibRedirect](https://libredirect.github.io/) that redirects reddit and other sites to alternative frontend like yours (libreddit). We need a way to automatically update our [instances list](https://github.com/libredirect/instances/blob/main/data.json). We can do it by scraping this site's README, but what if the instances are in a json file in the Repo.
Ex: `instances.json`
```
[
    {
        "instance": "libredd.it",
        "country": "us"
    },
    {
        "instance": "libreddit.spike.codes",
        "country": "us"
    },
    {
        "instance": "libreddit.dothq.co",
        "country": "de"
    },
    {
        "instance": "libreddit.kavin.rocks",
        "country": "in"
    },
    {
        "instance": "libreddit.40two.app",
        "country": "nl"
    },
    {
        "instance": "spjmllawtheisznfs7uryhxumin26ssv2draj7oope3ok3wuhy43eoyd.onion",
        "country": "in"
    }
]
```

**Comment by azizLIGHT** [comment]
Related: https://github.com/spikecodes/libreddit/pull/223

**Comment by spikecodes** [comment]
This suggestion has finally been fulfilled with the new [libreddit-instances](https://github.com/libreddit/libreddit-instances) repository!
