### ISSUE TITLE
Show crosspost information

### ISSUE THREAD

**Issue by onebyte4** [spikecodes/libreddit#418]
## How does this feature work on Reddit?

[reddit shows crosspost information bar above image/post](https://old.reddit.com/r/destiny2/comments/ccwcjz/me_carrying_my_friends_through_the_campaign_this/)  - [in libreddit](https://libredd.it/r/destiny2/comments/ccwcjz/me_carrying_my_friends_through_the_campaign_this/) 

[example selfpost](https://old.reddit.com/r/beta/comments/drciud/how_would_you_feel_about_a_feature_where_if/) -  [in libreddit](https://libredd.it/r/beta/comments/drciud/how_would_you_feel_about_a_feature_where_if)

## Describe the implementation into Libreddit
show this information in libreddit like reddit for both self posts and image posts

## Additional context
reddit shows like this:
![screenshot](https://user-images.githubusercontent.com/79567896/152652081-37ef3d74-b986-4e64-a2c0-76cb32ffecbc.png)

**Comment by spikecodes** [comment]
Thanks! Merging this with #13
