### ISSUE TITLE
Documentation pro-tip for Chrome extension setup to auto-redirect official Reddit links to user's preferred instance

### ISSUE THREAD

**Issue by joonas-fi** [spikecodes/libreddit#419]
I wrote a blog post about the general problem and its solution: https://joonas.fi/today-i-learned/2022/alternative-website-usage-with-url-redirect-chrome-extension/

Would you accept a README PR to link to the article that I wrote? My website doesn't have ads, I just want to spread the goodness!

**Comment by spikecodes** [comment]
Thanks for the awesome article! I really like your blog too. I didn't link your article but I did include the solution (using an automatic redirect extension) in the instance list: 
![image](https://user-images.githubusercontent.com/19519553/169631288-2c8f8e69-f98a-415c-96c4-519d6ca46946.png)

**Comment by joonas-fi** [comment]
Thanks! That's a good solution! 👍 

Thanks for the great software, and have a nice weekend :)
