### ISSUE TITLE
Libreddit Accounts

### ISSUE THREAD

**Issue by trymeouteh** [spikecodes/libreddit#427]
Simular to Invidious, the ability to have an account on a libreddit instance and be able to subscribe to subreddits and have a feed.

**Comment by r7l** [comment]
You can subscribe already. It's explained in the [wiki](https://github.com/spikecodes/libreddit/wiki/Import-Reddit-Subscriptions).

**Comment by trymeouteh** [comment]
An account system would be nice to be able to login on other devices and get your subscriptions synced.

**Comment by spikecodes** [comment]
This isn't planned but Libreddit does support exporting and importing preferences which can be used to sync across devices!

**Comment by grubeli** [comment]
Something like https://github.com/burhan-syed/troddit would be cool
