### ISSUE TITLE
Feature Request | Search only in current subreddit

### ISSUE THREAD

**Issue by stemy2** [spikecodes/libreddit#43]
**Is your feature request related to a problem? Please describe.**
I'm a big fan of a particular subreddit and i'd like to perform seraches only in the said subreddit, and not everywhere in reddit.

**Describe the solution you'd like**
A checkbox "search only in the current subreddit".

**Comment by spikecodes** [comment]
Hi! Thanks for opening this. Libreddit actually already had this feature but it seems the last update broke it. Just fixed with 48d2943! Changes should be live shortly
