### ISSUE TITLE
Long titles with unbroken text break outside of post container

### ISSUE THREAD

**Issue by mattcarlotta** [spikecodes/libreddit#435]
## Describe the bug

When a title has long unbroken text: `22222222222222222222222222222222222222222222222222` it will expand beyond the `post` container:
![Screenshot from 2022-02-22 11-37-32](https://user-images.githubusercontent.com/22607722/155206413-60d3de4c-e277-4dd0-ae4c-c9f0ef040e52.png)

## Expected behavior

The second link within the `post_title` class element, should break the text and wrap beneath itself using `overflow-wrap: break-word;`:
![Screenshot from 2022-02-22 11-39-11](https://user-images.githubusercontent.com/22607722/155206649-db69b764-4248-46b2-ae2f-54311520d27e.png)

**Comment by mikupls** [comment]
Thanks, this looks correct to me from short testing. I have a patch in https://github.com/mikupls/libreddit/commit/8e11678d8352b93263016a779b607a0371f52fdd and can send a PR once spikecodes is back.

**Comment by spikecodes** [comment]
Thanks for reporting this!
