### ISSUE TITLE
Include reddit.rtrace.io in the list of public instances

### ISSUE THREAD

**Issue by unclearParadigm** [spikecodes/libreddit#438]
Hey,

I've been hosting libreddit for close to a half year now, and it's rock solid and stable in production. I'm reaching uptime-rates > 99.9% (see https://status.rtrace.io). Thanks a lot for this awesome frontend! Last week I added another instance behind a load-balancer, and I'm now able to auto-scale, based on the incoming load and number of requests. Since that, I've decided to share the instance with the broad world! I'd be glad if you could add it to the list of public instances.

The instance is reachable via HTTPS (Let's Encrypt) here: https://reddit.rtrace.io

Further info:
- I'm NOT (and never will be) using Cloudflare.
- The Server(s) are hosted at Netcup in Germany.
- Running within Podman Containers
- On Fedora Server
- Also hosted with much love ;)

Thanks!

BR,
Ruffy

**Comment by spikecodes** [comment]
Hey Ruffy, thanks so much for hosting Libreddit! I appreciate the detailed information on the instance too.
