### ISSUE TITLE
Archiving Posts

### ISSUE THREAD

**Issue by alphaonion** [spikecodes/libreddit#439]
It would be awesome to be able to archive posts with comments, OR to provide an rss feed for post and comments.

**Comment by walkxcode** [comment]
+1 This, having a button to open the RSS feed of a post would be very useful.

**Comment by spikecodes** [comment]
Sorry what do you mean by archive posts? Are you referring to signing into your Reddit account to archive posts that you've made to Reddit?

**Comment by walkxcode** [comment]
I don't need archiving, just a button to access RSS feed. Don't know about the other guy tho.

**Comment by spikecodes** [comment]
Closing this in favor of #27 which explains why RSS feeds are not planned for Libreddit
