### ISSUE TITLE
Broken Instances

### ISSUE THREAD

**Issue by walkxcode** [spikecodes/libreddit#447]
I've found the following libreddit instances to be down or returning errors.

https://libreddit.40two.app/ - Server Not Found
https://reddit.phii.me/ - Server Not Found
https://libreddit.database.red/ - 404
https://libreddit.sugoma.tk/ - Server Not Found
https://libreddit.awesomehub.io/ - Server Not Found
https://libreddit.flux.industries - Not Loading
https://lr.oversold.host/ - Cloudflare 502 (Host Error)
https://libreddit.crewz.me/ - Server Not Found

**Comment by spikecodes** [comment]
Thanks for this report! I haven't gotten around to building the instance viewer website yet but I feel this solution would be best: https://github.com/spikecodes/libreddit/pull/331#issuecomment-974752799

**Comment by spikecodes** [comment]
Thanks for this report! I haven't gotten around to building the instance viewer website yet but I feel this solution would be best: https://github.com/spikecodes/libreddit/pull/331#issuecomment-974752799
