### ISSUE TITLE
Libreddit stops working and renderes 500 Internal Server Error Status Page (but HTTP 404)

### ISSUE THREAD

**Issue by unclearParadigm** [spikecodes/libreddit#448]
## Describe the bug

Pretty much all instances stopped working at the same time (around 22:06 UTC+1, 14th of March).
Libreddit returns just a 500 Status Code. Interesting enough, Libreddit renders a Status 500 Error directly on the main-page.
The browser Console (Firefox in my case) returns a 404 HTTP status code.
  
![image](https://user-images.githubusercontent.com/42910918/158262125-c14e5c31-3a59-49c1-9b66-f5c3ef9d8a3c.png)

![image](https://user-images.githubusercontent.com/42910918/158262833-9beddbfa-3ab4-4df1-a9a6-0e0a4fe2d1e6.png)

The "Default"-Page seems to be affected. Subreddits still work if you directly access them (e.g. [r/austria](https://reddit.rtrace.io/r/austria)). Changing the Default-Page to "All" seems to make it working again.

## To reproduce

1. Go to [ 'a random libreddit instance'](https://reddit.rtrace.io/)
2. see 500 HTTP status code

~I'll see whether I find relevant logs and attach them here~

**Comment by StephanieSunshine** [comment]
Can confirm, I found this issue trying to find if anyone else was experiencing it.

**Comment by unclearParadigm** [comment]
Okay, seems that we're back in normal operation. Seemed to be just a temporary glitch on Reddit-Server side. It works now again. Checked multiple instances.

**Comment by spikecodes** [comment]
Thanks for reporting this so quickly! Yeah, Reddit servers had a temporary issue but it's fixed now.
