### ISSUE TITLE
Empty subreddit info on home page

### ISSUE THREAD

**Issue by 674Y3r** [spikecodes/libreddit#449]
## Describe the bug
After an update to v0.22.2 libreddit shows empty subreddit information on homepage (requires at least 1 subsribed subreddit).
- Subscribe button points to https://libreddit.spike.codes/r/subscribe?redirect=
- Filter button points to https://libreddit.spike.codes/r/filter?redirect=

## To reproduce
1. Go to https://libreddit.spike.codes,
2. Subscribe to at least 1 subreddit,
3. Go to https://libreddit.spike.codes again,
4. See empty subreddit information.
![image](https://user-images.githubusercontent.com/87250374/158634524-fbde2de2-1b81-4604-8f40-87fc9a57b1de.png)

## Expected behavior
No subreddit information on homepage with at least 1 subscribed subreddit.

**Comment by spikecodes** [comment]
Thanks! Fixed in v0.22.3
