### ISSUE TITLE
Building with the AUR version errors

### ISSUE THREAD

**Issue by Stetsed** [spikecodes/libreddit#451]
## Describe the bug
When trying to build the package "libreddit-git", from the AUR it gives an error about cargo lock. To be exact it gives the below error:
```
error: the lock file /home/stetsed/libreddit-git/src/libreddit/Cargo.lock needs to be updated but --locked was passed to prevent this
If you want to try to generate the lock file without accessing the network, remove the --locked flag and use --offline instead.
```

## To reproduce

1. Copy the repository with "git clone https://aur.archlinux.org/libreddit-git.git"
2. Go into the directory with "cd libreddit-git"
3. Start the build process with "makepkg -si"
4. Voila, you shall see the error appear.

## Expected behavior

It should build the package and then follow the rest of the build script to install it.

## Additional context

Some extra information will be attached here, and I have ran pacman -Syu and everything is updated. I hope somebody else can also test, because if it works for somebody else it might be smth in my setup which is breaking it.
Kernel: 5.16.15-zen1-1-zen
Rust Version: 1:1.59.0-1
Cargo Version: 1.59.0

**Comment by Stetsed** [comment]
So I messed around with the PKGBUILD file, and removing the --locked flag seemed to have fixed it.

**Comment by spikecodes** [comment]
Thanks for reporting! I attempted to recreate this but was unable to. I believe the recent updates (notably to Cargo.toml and Cargo.lock) must have fixed this so I'll be closing this issue but let me know if it persists
