### ISSUE TITLE
Google block?

### ISSUE THREAD

**Issue by wtfwhydoi** [spikecodes/libreddit#452]
Hello, I’m not quite sure if it’s possible, but I am wondering if you could do a Google block on my Reddit username? I don’t want it to show up when someone Googles it, if possible. I’m very dumb with this kind of stuff and would appreciate the help. If it’s possible to message me privately about my Reddit username, that would be great. Thank you!

**Comment by 1over137** [comment]
For things like Reddit accounts, it's best to clean it up with some external tools that will edit out all your messages and start anew. You shouldn't rely on people being able to remove you from search results.

**Comment by spikecodes** [comment]
Hi! Libreddit currently blocks search engines from indexing user profiles but your posts may still show in results. If you want to remove those, you'll have to tackle that on the Reddit-side as Libreddit receives all data from there. @1over137 gave good advice; you can use a tool like [redact.dev](https://redact.dev/services/reddit) to mass delete your comments and posts if you want
