### ISSUE TITLE
Add my instance

### ISSUE THREAD

**Issue by 1over137** [spikecodes/libreddit#454]
Add my newly set up instance
https://libreddit.notyourcomputer.net/
Hosted on my home server through a VPS gateway to bypass CGNAT.
No Cloudflare or other CDN services

**Comment by spikecodes** [comment]
Hi! Thank you for hosting Libreddit. What country is your home server located in?

**Comment by 1over137** [comment]
USA.

**Comment by spikecodes** [comment]
Thanks for hosting Libreddit! https://github.com/spikecodes/libreddit/commit/1c50c8f30dfc19e5f43073b8b31d17d2d77943df
