### ISSUE TITLE
Add an option to put a custom link on the top bar (to homepage)

### ISSUE THREAD

**Issue by 1over137** [spikecodes/libreddit#455]
Many instances of alt-frontends like libreddit are hosted on personal websites which can have interesting content. It would be nice if people visited sites other than those owned by megacorporations.
It would be great if there is a "homepage" link on the top left to optionally open a link to the main website of the person hosting it.

**Comment by spikecodes** [comment]
Hi! This functionality would be provided by #347 (which adds banners that can include links) so I'll close this issue in favor of that one.
