### ISSUE TITLE
شركة كشف تسربات المياه بالرياض 0502400989

### ISSUE THREAD

**Issue by hasaballaa** [spikecodes/libreddit#458]
## Additional context
 
[شركة كشف تسربات المياه بالرياض
](https://rokn-aladham.com/%D9%83%D8%B4%D9%81-%D8%AA%D8%B3%D8%B1%D8%A8%D8%A7%D8%AA-%D8%A7%D9%84%D9%85%D9%8A%D8%A7%D9%87-%D8%A8%D8%A7%D9%84%D8%B1%D9%8A%D8%A7%D8%B6/)

**Comment by RadioToad** [comment]
Not a bug, link leads to a random website.
