### ISSUE TITLE
[ADD INSTANCE] libreddit.0xc0d3.xyz

### ISSUE THREAD

**Issue by scriptzteam** [spikecodes/libreddit#459]
You can also add this one - libreddit.0xc0d3.xyz

Its loaded like this:
Cloudflare -> VPN server (locations are randomly changed) -> our hidden server -> libreddit -> reddit

:-)

**Comment by spikecodes** [comment]
Hi, what country is your hidden server hosted in?

**Comment by scriptzteam** [comment]
Why does it matter?

**Comment by spikecodes** [comment]
It's common practice for privacy products to list the server location because different countries are subject to different surveillance rules and subpoena laws

**Comment by scriptzteam** [comment]
its just f*cking reddit "proxy" cmon...
