### ISSUE TITLE
New Instance - https://libreddit.lunar.icu

### ISSUE THREAD

**Issue by MaximilianGT500** [spikecodes/libreddit#460]
Hello, can you add my Instance to the Public List: https://libreddit.lunar.icu ?

Thanks,
Maximilian

**Comment by spikecodes** [comment]
Hi what country is your instance hosted in and does it use Cloudflare Proxy?

**Comment by austinhuang0131** [comment]
There is Cloudflare.

The Nitter, Invidious, rimgo and Whoogle instances on that domain were self-declared to be in Germany.

**Comment by spikecodes** [comment]
Thanks!
