### ISSUE TITLE
Make subscription feed more inclusive to low traffic subreddits

### ISSUE THREAD

**Issue by PAI5REECHO** [spikecodes/libreddit#473]
## Is your feature request related to a problem? Please describe.
It seems like the subscription feed is dominated by posts from high traffic subreddits which is annoying since I still want to also see the most upvoted posts on small subreddits I'm subscribed to.

## Describe the solution you'd like
Somehow include all content from subscribed subreddits more evenly

**Comment by spikecodes** [comment]
The relevancy of posts in your subscription feed is determined by Reddit's sorting algorithms so I'm closing this issue and recommending you bring the concern up with Reddit at [r/ideasfortheadmins](https://www.reddit.com/r/ideasfortheadmins/).
