### ISSUE TITLE
link overflow

### ISSUE THREAD

**Issue by Ghostfreak803** [spikecodes/libreddit#480]
## Describe the bug

Noticed a link that goes outside the post border

## Steps to reproduce the bug

Open https://libredd.it/tqskr1 on phone (I use Samsung M51)

## Additional context / screenshot

![Screenshot_Bromite](https://user-images.githubusercontent.com/35540132/162154353-fd5b370b-1edb-400c-91fe-abaa55468ee9.jpg)

**Comment by mikupls** [comment]
I can somewhat reproduce using the "Wide UI" option, but I cannot get the same result as above.

![x](https://user-images.githubusercontent.com/93015331/163671422-ad2a3c32-4673-4e8a-95ed-2edee438bcd2.png)

Solution is likely to add another `overflow-wrap: anywhere` to `post_body` like #462. But I'm not sure how it would interact with the solution for #471.

---

Which version of libreddit did you use, and did you modify any settings? Which browser are you using?

**Comment by Ghostfreak803** [comment]
> Which version of libreddit did you use, and did you modify any settings? Which browser are you using?

Using libreddit v0.22.6 (no modification in any setting, using the official instance at https://libredd.it)
Having the same issue on following browsers (all on my phone):
Bromite: 100.0.4896.83
Chrome: 100.0.4896.88
Interestingly enough, the page loads fine on Firefox android (99.2.0) with no overflow.. So i don't know what to make of that. Here's a screenshot:
![Screenshot_20220416-161211_Firefox](https://user-images.githubusercontent.com/35540132/163671880-9b2c618a-6d9b-401d-81b8-9a3e68cf2fd7.jpg)

**Comment by mikupls** [comment]
Ah, thanks for the quick feedback! I can reproduce this with Chromium.

Adding the overflow-wrap seems to fix it.

![x](https://user-images.githubusercontent.com/93015331/163708034-ab238fb4-9a6b-4a90-918b-a63610905f15.png)
