### ISSUE TITLE
⬆️ Update Instance Location

### ISSUE THREAD

**Issue by walkxcode** [spikecodes/libreddit#483]
Hello,

I just wanted to report that my instance is now hosted in 🇳🇱 NL instead of 🇩🇪 DE.
My instance is https://r.walkx.org 🙂

**Comment by safarivillas** [comment]
Nice info!
As of late sent off [Liberty Lands Lahore](https://www.ourupn.com/liberty-lands-lahore-a-project-by-etihad-town-lahore) plots are insightfully planned to work with investors with the best. This housing society depicts brilliant town planning as offering the best residential and commercial plots

**Comment by spikecodes** [comment]
Thanks for hosting Libreddit! https://github.com/spikecodes/libreddit/commit/1c50c8f30dfc19e5f43073b8b31d17d2d77943df
