### ISSUE TITLE
⬆️ - Add instance

### ISSUE THREAD

**Issue by Ahwxx** [spikecodes/libreddit#484]
Hey there!

I've been hosting my own instance for some time and thought I'd make an issue.

URL: [https://r.ahwx.org](https://r.ahwx.org)

Hosted in the Netherlands using CloudFlare.

Thanks!
- Ahwx

**Comment by spikecodes** [comment]
Thanks for hosting Libreddit! https://github.com/spikecodes/libreddit/commit/1c50c8f30dfc19e5f43073b8b31d17d2d77943df
