### ISSUE TITLE
I made a new instance ;)

### ISSUE THREAD

**Issue by probsdelonghi** [spikecodes/libreddit#488]
https://bob.fr.to 
hhosted on replit, so i have no idea where its being hosted =/
no cloudflare

**Comment by probsdelonghi** [comment]
actually, i probably needs to be self-hosted ,doesn't it? Oh well , if its allowed on just say France

**Comment by spikecodes** [comment]
Thanks for hosting Libreddit! https://github.com/spikecodes/libreddit/commit/1c50c8f30dfc19e5f43073b8b31d17d2d77943df
