### ISSUE TITLE
Feature Request | Support rich-text flairs with "Emoji"

### ISSUE THREAD

**Issue by robrobinbin** [spikecodes/libreddit#49]
**Is your feature request related to a problem? Please describe.**
"Emoji" in flairs use their :fallback_text:.

**Describe the solution you'd like**
Support emoji images in flairs.

**Additional context**
I started work on this over at https://github.com/robrobinbin/libreddit/tree/rich-flairs, but it needs some more debugging and polishing. I'll create a pull request once I'm finished.

**Comment by spikecodes** [comment]
Good suggestion, thank you for these useful contributions!

**Comment by spikecodes** [comment]
Closed by #50
