### ISSUE TITLE
Please add https://reddit.beparanoid.de/

### ISSUE THREAD

**Issue by hnhx** [spikecodes/libreddit#495]
Country: Switzerland
Cloudflare: No
Clearnet: https://reddit.beparanoid.de/
Tor v3 hidden service: http://reddit.prnoid54e44a4bduq5due64jkk7wcnkxcp5kv3juncm7veptjcqudgyd.onion/
I2P hidden service: http://be3sji4vh5zbkpu7av5rkt3sdeyi3v7hclodlbs266v7hiyxhtfq.b32.i2p/

**Comment by spikecodes** [comment]
Thanks for hosting Libreddit! https://github.com/spikecodes/libreddit/commit/1c50c8f30dfc19e5f43073b8b31d17d2d77943df
