### ISSUE TITLE
🐛 Bug Report: Quarantined Subreddits

### ISSUE THREAD

**Issue by Adi1200** [spikecodes/libreddit#496]
## Describe the bug
  When attempting to view a quarantined subreddit and clicking 'Continue', nothing happens.

## Steps to reproduce the bug

1. Go to a quarantined subreddit 
2. Click on 'Continue'
3. Nothing happens
-->

## What's the expected behavior?
It lets me view the subreddit  I expected to view the subreddit

**Comment by mikupls** [comment]
I think #208 implemented that. The test-case from there `r/fullcommunism` works on my libreddit instance.

Could you check if the subreddit you are trying to open is accessible without login on reddit? If login is required, we likely cannot work around that (though maybe there is a way?)

**Comment by Adi1200** [comment]
> I think #208 implemented that. The test-case from there `r/fullcommunism` works on my libreddit instance.
> 
> Could you check if the subreddit you are trying to open is accessible without login on reddit? If login is required, we likely cannot work around that (though maybe there is a way? It seems like I can actually see comments in the subreddit above on libreddit, but not on reddit)

I tried r/GenZedong on libreddit.spike.codes, and it is accessible through Reddit, but not on Libreddit

**Comment by mikupls** [comment]
Are you sure that you aren't logged in when trying to access it through reddit?

The options I get on reddit are either to leave or sign in:

![x](https://user-images.githubusercontent.com/93015331/165843950-1e52e14f-d38d-4da6-841a-9ba2b9be040f.png)

**Comment by Adi1200** [comment]
Sorry, I wasn't signed out, sorry for wasting your time. Kind of a dick move on Reddit's part.

**Comment by mikupls** [comment]
No problem @Adi1200, happy to help :slightly_smiling_face: 

And yeah, more and more things seem to move to registered users only (E.g. #325).
