### ISSUE TITLE
💡 Feature request: Sign-in or account sync feature

### ISSUE THREAD

**Issue by bigfloppa234** [spikecodes/libreddit#499]
## Is your feature request related to a problem? Please describe.

I don't like syncing subreddits or stuff manually and I think an account syncing/sign-in feature would be very useful
## Describe the feature you would like to be implemented

If you sign-in, it will sync subreddits and homepages
## Describe alternatives you've considered

Doing it manually (but nobody wants to do that)

**Comment by EdwardLangdon** [comment]
It would be great to have this feature, So Still attainaing Privacy with less Traffic on loading site comparing to the official one. But I Prefer Libreddit to act as Web Client like Slide and Infinity instead of just syncing.

**Comment by sph3** [comment]
It would be great for people who like to interact with posts and not just scroll.

**Comment by spikecodes** [comment]
Sign-in is not currently planned as discussed in https://github.com/spikecodes/libreddit/issues/229
