### ISSUE TITLE
Feature Request | Customize accent color

### ISSUE THREAD

**Issue by spikecodes** [spikecodes/libreddit#51]
**Is your feature request related to a problem? Please describe.**
No issue, but the customization of this would be nice.

**Describe the solution you'd like**
Setting to change accent color.

**Describe alternatives you've considered**
Command line argument to set instance-specific accent color.

**Additional context**
None.

**Comment by spikecodes** [comment]
Not something I feel needs working on atm.

**Comment by Kncuk** [comment]
Hi, wondering if there's any plan to get this into Libreddit? I notice there aren't many red/pink/oragn-ish dark theme
