### ISSUE TITLE
Remove libreddit.silkky.cloud instance.

### ISSUE THREAD

**Issue by TheSilkky** [spikecodes/libreddit#510]
Instance will shutting down at the end of May

**Comment by spikecodes** [comment]
Sorry to hear but thank you for letting me know. Was it an issue specifically with Libreddit or are you scaling back self-hosting overall?

**Comment by TheSilkky** [comment]
@spikecodes Libreddit has been great and definitely my favourite service to host. I can't afford cost of hosted services anymore, so I'm in the process of shutting everything down and telling people export their data, etc.

**Comment by BinaryGenius** [comment]
Oh that sucks but thanks for hosting the site I used it all the time for dark mode.
