### ISSUE TITLE
Add https://libreddit.mha.fi

### ISSUE THREAD

**Issue by datanomi** [spikecodes/libreddit#518]
Hello,
I started hosting a libreddit instance,

- https://libreddit.mha.fi
- http://libreddit.micohauwkjbyw5meacrb4ipicwvwg4xtzl7y7viv53kig2mdcsvwkyyd.onion/

Hosted in Finland, without Cloudflare or other proxy

**Comment by EdwardLangdon** [comment]
Off-Topic : Seems like you decrypted my PGP message.
