### ISSUE TITLE
Feature Request | Image placeholder when using card view

### ISSUE THREAD

**Issue by robrobinbin** [spikecodes/libreddit#52]
**Is your feature request related to a problem? Please describe.**
When using card view, inline images can push content down unexpectedly while loading.

**Describe the solution you'd like**
Reserve the correct amount of space for image

**Additional context**
Useful information to implement something like this can be found on this website https://css-tricks.com/preventing-content-reflow-from-lazy-loaded-images/

**Comment by spikecodes** [comment]
Closed by #55.
