### ISSUE TITLE
Feature Request | Support /user/ URLs

### ISSUE THREAD

**Issue by Zegnat** [spikecodes/libreddit#53]
**Is your feature request related to a problem? Please describe.**
The other day I was linked to a post that was posted on a user page rather than on a subreddit. This is possible because every user is also a subreddit (of sorts). There pages are available through libreddit, but only after manually tweaking the URL.

* Example on Reddit: `https://www.reddit.com/user/Planetsahead/comments/ktufit/peegate_update/`
* Gives an "Error: Nothing here" on libreddit: `https://libredd.it/user/Planetsahead/comments/ktufit/peegate_update/`
* But works if `/user/` is replaced with `/r/u_`: `https://libredd.it/r/u_Planetsahead/comments/ktufit/peegate_update/`

**Describe the solution you'd like**
Preferably switching `www.reddit.com` for `libredd.it` is enough to get the page loaded.

**Describe alternatives you've considered**
Another alternative (though less desirable IMHO) is to have `/user/` automatically redirect to the less specific `/r/u_` prefix.

**Comment by spikecodes** [comment]
Just added support for `/user/` posts!
