### ISSUE TITLE
Bug Report | When sorting by "top", the next button loses the "t=" parameter

### ISSUE THREAD

**Issue by robrobinbin** [spikecodes/libreddit#56]
**Describe the bug**
When sorting by "top", the next button at the bottom doesn't have the "t=" for time parameter, often making the second page empty or incorrect.

**To reproduce**
1. Select "Top"
2. Select a time period, eg. "Week" and go
3. Click "Next"

**Comment by spikecodes** [comment]
Can you share a URL of a page that this happens on?
