### ISSUE TITLE
Add space next to hide comment

### ISSUE THREAD

**Issue by B0pol** [spikecodes/libreddit#58]
**Describe the bug**
On mobile, it's hard to click on the hide comment button, we often missclick on the user profile

**To reproduce**
1. Have too large fingers?
2. Try to hide a comment

**Expected behavior**
It hides comment

**Additional context**
It is hard to click on hide comment, and easier to click on profile post. If you add space there it would make it easier to click on hide comment

**Comment by robrobinbin** [comment]
As a workaround, you can also click the timestamp of the comment to collapse it.

**Comment by spikecodes** [comment]
Thanks for this contribution! I just pushed 0f6e73d which makes the collapse button much larger and pushes the comment author text farther right. This should make it much easier to press, let me know if this fixes your issue.

![image](https://user-images.githubusercontent.com/19519553/104821717-9fd26500-57f2-11eb-88cb-f7204ba3569c.png)

**Comment by B0pol** [comment]
Yes, it's fine now. Thank you
