### ISSUE TITLE
Is Libreddit still maintained?

### ISSUE THREAD

**Issue by Daniel-Valentine** [spikecodes/libreddit#585]
Hi @spikecodes (et al),

I'm dropping a line to inquire if this project is still being maintained. The last commit is from June, and since then a queue of outstanding issues and pull requests has formed, and in addition some of the instances in the readme no longer work. I would like to help with the issues that I can -- for example, I've raised one PR for a minor issue, #578; would have drafted work toward #574; and have ideas for #577 for which I'd like input from other contributors -- but neither I nor anyone else can unless a maintainer reviews contributions.

Thank you for creating Libreddit, which has been my go-to for Reddit browsing ever since I discovered it a year ago. It is fantastic software, and I hope to contribute to the project in the future.

**Comment by ellieeet123** [comment]
Hello, 

Did you end up changing the organization name to libbacon? Currently [libreddit]https://github.com/libredditl) gives a 404 error, and the [libaccon](https://github.com/libreddit) organization has no repositories.

**Comment by spikecodes** [comment]
Hi all! I apologize for my absences but back and will be supporting Libreddit's transition, as best I can, to a community-run project so my absences won't stall growth going forward.

Read my full update [here](https://github.com/spikecodes/libreddit/issues/599#issuecomment-1297851595).
