### ISSUE TITLE
Feature Request | Support Reddit Galleries

### ISSUE THREAD

**Issue by spikecodes** [spikecodes/libreddit#59]
**Is your feature request related to a problem? Please describe.**
Gallery posts show the link to the gallery rather than embedding the media.

As shown by https://libredd.it/hrrh23,

![image](https://user-images.githubusercontent.com/19519553/104824959-7a9e2080-580b-11eb-8fca-c9aa9e67bd8e.png)

**Describe the solution you'd like**
Be able to render the images of a gallery like https://www.reddit.com/gallery/hrrh23.

**Comment by robrobinbin** [comment]
The upstream API gives us a number of things for gallery images:
* The image + dimensions
* Thumbnails for each image, in different sizes
* Optionally: a description provided by the user
* Optionally: a link provided by the user (eg. to link back to an original source)

There are a couple of things we could do to implement this:
1. Throw all full images + descriptions + links on the page, below one another or in some flex or grid layout
2. Put all thumbnails on the page (+ description and link?), with the thumbnails linking to the full image
3. Build a CSS only carousel, to mimic upstream behavior, which allows you to page through the images (https://css-tricks.com/css-only-carousel/, https://newtodesign.com/pure-css-carousels/)

I could help building any of the above visualizations. Do you have opinions or remarks on these options?

**Comment by spikecodes** [comment]
Thanks for this great run-down! I was thinking the first method.

**Comment by robrobinbin** [comment]
I'm working on this :)
