### ISSUE TITLE
Feature Request | Hide NSFW content by default

### ISSUE THREAD

**Issue by eightfiftytwo** [spikecodes/libreddit#63]
**Describe the bug**
The Reddit search box has an option to "include NSFW results".
Libreddit doesn't and searching in any NSFW subreddits will yield no results.
However, if you manually append `&include_over_18=on` to the URL, everything works as expected.
Seems like adding a button would be enough to fix this.

**Comment by spikecodes** [comment]
Thanks for reporting this! Libreddit currently has a setting for displaying NSFW posts. I just pushed 6641e24 which will make search results respect this setting:
![image](https://user-images.githubusercontent.com/19519553/105271986-669e4a00-5b90-11eb-8cc8-68f487537ace.png)
Changes should be live shortly!

**Comment by eightfiftytwo** [comment]
Would you consider enabling that option by default and/or adding an "over 18?" prompt? The norm among major sites that contain some NSFW content (Reddit, Twitter, Tumblr etc.) seems to be seeking user consent before show NSFW content. I assume it's because infrastructure providers don't take kindly to services that show NSFW content by default (cf. Apple's App Store rules). It is also the right thing to do imo to avoid exposing minors to NSFW content accidentally.

**Comment by spikecodes** [comment]
Apologies for the late response. Good idea! I'll make hiding NSFW content the default.

**Comment by spikecodes** [comment]
1653d4fb4c069b1cc997130f472fb613dbe4593d has implemented this!
