### ISSUE TITLE
Feature Request | Add "Show parent comments"button when viewing a comment

### ISSUE THREAD

**Issue by robrobinbin** [spikecodes/libreddit#65]
**Is your feature request related to a problem? Please describe.**
When you navigate to a comment directly, eg. coming from a user's profile, you cannot easily see the context of the comment.

**Describe the solution you'd like**
Add a "Show parent comments" button. This button would append "?context=9999" to the URL (or a similar value).

**Additional context**
IIRC, the number of nested comments is now capped at 3 by libreddit. To display a full context, deeper nesting should be supported.

**Comment by spikecodes** [comment]
Good feature request!
