### ISSUE TITLE
Bug Report | 1 karma for score hidden

### ISSUE THREAD

**Issue by B0pol** [spikecodes/libreddit#66]
**Describe the bug**

**To reproduce**
1. Find posts with score hidden (many subreddits apply this policy for few hours after creating a comment)
2. Notice the score is 1

**Expected behavior**
The score is ? or another sign to show it's hidden, unknown

**Additional context**

**Comment by spikecodes** [comment]
Thanks!

**Comment by spikecodes** [comment]
Just fixed this with 971f14b! I chose a bullet point character for posts and comments that have a hidden score:
![image](https://user-images.githubusercontent.com/19519553/106399559-3b79ed00-6411-11eb-8f0e-4f16086938a2.png)
