### ISSUE TITLE
could you add my instance to your list?

### ISSUE THREAD

**Issue by fres7h** [spikecodes/libreddit#73]
the url is https://libreddit.himiko.cloud.

thank you <3

**Comment by spikecodes** [comment]
Thank you for hosting Libreddit! :smiley: 
What country is the server hosted in?

**Comment by fres7h** [comment]
Bulgaria

**Comment by spikecodes** [comment]
Thanks! Just added: e6c2d08

**Comment by fres7h** [comment]
i recently set up hidden services for all of my sites, so my libreddit has one now. not sure if you want to add it to the list, but thought i'd mention it.

http://libreddit.himiko7xl2skojc6odi7hykl626gt4qki3vxdbv33u2u3af76d6k32ad.onion/

**Comment by spikecodes** [comment]
Awesome, thanks! Just added
