### ISSUE TITLE
Feature Request | Fonts

### ISSUE THREAD

**Issue by Mennaruuk** [spikecodes/libreddit#74]
**Is your feature request related to a problem? Please describe.**
I see libreddit being described as more of a privacy-respecting alternative to redesigned Reddit. I was thinking about possibility of including Reddit's fonts for Libreddit.

**Describe the solution you'd like**
Reddit uses [IBM Plex Sans](https://fonts.google.com/specimen/IBM+Plex+Sans) for titles and [Noto Sans](https://fonts.google.com/specimen/Noto+Sans) for body. Both are free: IBM Plex Sans is licensed under the [Open Font License](https://scripts.sil.org/cms/scripts/page.php?site_id=nrsi&id=OFL) while Noto Sans is licensed under [Apache License, Version 2](https://www.apache.org/licenses/LICENSE-2.0).

**Describe alternatives you've considered**
I understand there are different tastes for different people. I see Arial currently being used, and while it has [its critics](https://www.marksimonson.com/notebook/view/the-scourge-of-arial), Arial is ubiquitous. So it's up to you!

**Additional context**
I love libreddit!

**Comment by spikecodes** [comment]
Thank you for this suggestion! Currently Libreddit uses your browser-default font so if your browser (or system) font is set to Arial, that's what Libreddit will use. I like this idea, a specific font would be useful to ensure Libreddit appears the same no matter the user's device.

**Comment by Mennaruuk** [comment]
Thank you for considering the idea!!

**Comment by spikecodes** [comment]
I've just published [v0.14.2](https://github.com/spikecodes/libreddit/releases/tag/v0.14.2) which uses the minimalist [Inter](https://rsms.me/inter/) font! I'll be closing this issue for now but I may open a separate issue for users to specify a custom font in settings.

**Comment by Mennaruuk** [comment]
THANK YOU Spike! This looks freakin’ awesome!!!

![167CD03A-7F33-4CCE-B766-ED4D7BE44D51](https://user-images.githubusercontent.com/52135169/118912047-31fb8e80-b8f5-11eb-9ff5-da34673bf1dd.jpeg)

**Comment by spikecodes** [comment]
I'm so glad you like it! :) Inter is open source and a minimalist font so I thought it suited Libreddit really well!
