### ISSUE TITLE
Bug Report | Long subreddit name moves elements beyond screen on smartphones

### ISSUE THREAD

**Issue by Mennaruuk** [spikecodes/libreddit#75]
**Describe the bug**

Longer subreddit names move the Enter button beyond the screen, as well as move Libreddit’s logo and version, settings, and code elements. The only workaround is to rotate the smartphone from portrait to landscape. However, even then, while the Enter button becomes visible, elements such as Libreddit’s logo, version, settings, code are still off, compared to their position on a subreddit whose name is short.

**To reproduce**
1. Go to [this subreddit](https://libredd.it/r/UNBGBBIIVCHIDCTIICBG). It’s called UNBGBBIIVCHIDCTIICBG.
2. Locate search button

**Expected behavior**
Regardless of subreddit length name, the Enter button should still be visible either in portrait or landscape layout. Other elements should maintain position as well.

**Additional context**
![ABA04575-E286-45E0-A61C-8AE1D464AA64](https://user-images.githubusercontent.com/52135169/106093758-de272880-60fe-11eb-83cc-42550b9bd731.jpeg)

**Comment by spikecodes** [comment]
Thanks for this bug report, just fixed! Changes should be live soon

**Comment by Mennaruuk** [comment]
Awesomesauce!!!!
![DC919BC0-C30F-47CC-81CB-22623A390DA0](https://user-images.githubusercontent.com/52135169/106214814-999e9a00-619d-11eb-8423-540d78a9e4f5.jpeg)
