### ISSUE TITLE
Feature Request | Collapse on clicking comment guide lines

### ISSUE THREAD

**Issue by Mennaruuk** [spikecodes/libreddit#77]
**Is your feature request related to a problem? Please describe.**
On Reddit, when I click on a guide line belonging to a comment, all posts from the child posts up with that particular parent post collapse. I think Libreddit would benefit greatly from such feature.

**Describe the solution you'd like**
Clicking on any of the guide lines would collapse all comments below and including the comment next to this guide line. So this would be the same thing as clicking the upside down triangle, except this happens when I click the guide line and not the triangle.
![image](https://user-images.githubusercontent.com/52135169/106345984-a694b980-6281-11eb-8d17-a37f49e93ce2.png)

**Describe alternatives you've considered**
I hope this doesn't require JavaScript. I inspected the element for these guide lines, and they match div classes. So it seems more of an HTML feature than a JavaScript one.

**Additional context**
![guf](https://user-images.githubusercontent.com/52135169/106345865-28d0ae00-6281-11eb-93da-612748ed22fd.gif)

**Comment by spikecodes** [comment]
Thanks for this suggestion! The comments collapse and expand by using the [`<summary>`](https://developer.mozilla.org/en-us/docs/Web/HTML/Element/summary) and [`<details>`](https://developer.mozilla.org/en-us/docs/Web/HTML/Element/details) HTML tags. Using these will automatically generate a "marker", the pseudo-element that creates the dropdown arrow.

Sadly, this arrow can't be the entire line instead and therefore, I don't think this would be possible under the `summary`/`details` tags without Javascript.

**Comment by Mennaruuk** [comment]
That's okay, thank you so much for your consideration 🙏
