### ISSUE TITLE
Bug Report | CSP Blocks video playback

### ISSUE THREAD

**Issue by robrobinbin** [spikecodes/libreddit#79]
**Describe the bug**
The CSP header was updated recently. Since, videos don't play anymore and Firefox reports that the CSP is to blame.

**To reproduce**
1. View any post with an embedded video, eg. https://libredd.it/r/gifs/comments/l8hbml/snowboarder_flying_through_the_air/
2. Video doesn't play back.

**Expected behavior**
Play videos ;)

**Additional context**
Screenshot of the issue. Firefox reporting the CSP issue in the console

![image](https://user-images.githubusercontent.com/8597693/106365289-e49ee580-6334-11eb-9777-1792308361a2.png)

**Comment by spikecodes** [comment]
Thanks! a1d800a should fix this, changes will be live shortly.
