### ISSUE TITLE
Feature Request | Local Time

### ISSUE THREAD

**Issue by Mennaruuk** [spikecodes/libreddit#80]
**Is your feature request related to a problem? Please describe.**
Unfortunately, all time is shown as UTC. While that's great for all people living in UTC, people who don't live in UTC have to do some mental math each time they read the time.

**Describe the solution you'd like**
A privacy-respecting solution. One solution would be a setting to change timezone. So if user lives in the PST region, they can choose PST (UTC−07:00), and all their time from then on would be shown in PST (so hovering over date could reflect his as well). However, even this solution can be faced with criticism. [Nitter](https://github.com/zedeus/nitter/issues/65) has been debating this for a while. [One solution provided there ](https://github.com/zedeus/nitter/issues/65#issuecomment-552829218)"is by serving UTC times from the server, but suppling the unix timestamp in a data attribute, and adding a script that finds elements with timestamps, gets the data attribute, makes a local time string, and writes it back into the element. This would provide local times for people with JavaScript enabled, and fall back to UTC time for users with JavaScript disabled. While this isn't perfect, I think it's the best possible solution."

**Describe alternatives you've considered**
There is no alternative, as all times in Libreddit are shown in UTC.

**Additional context**
I have a side question: how is Libreddit pronounced!? Is it leeb-reddit? leeb-ruh-dit? lib-reddit?

**Comment by spikecodes** [comment]
Thanks for this feature request! Yeah local time would be a useful addition.

Though, I'm not sure how this could be achieved without the use of JavaScript (Nitter's solution) or tracking IP addresses and pinpointing coordinates from that (would be a privacy hazard, I feel).

>  I have a side question: how is Libreddit pronounced!? Is it leeb-reddit? leeb-ruh-dit? lib-reddit?

😁 Great question! I'm fine with any pronunciation but I personally say "lib-reddit".

**Comment by Mennaruuk** [comment]
Yes, that's the dilemma. No one wants geolocation lookup or JavaScript, so until a good solution comes up, it seems like local time is a sacrifice. I was personally thinking of a client-side option where the user specifies their timezone and Libreddit would subtract from or add to the UTC time however many hours, and nothing ever goes through Libreddit's servers (by the fact that once the Libreddit optional cookies storing configuration settings are deleted, it goes back to UTC). But even then, there might be privacy concerns about this.

ME TOO! That's how I say it. I know it's a portmanteau of _libre_ and _reddit_, yet I couldn't resist calling it lib-reddit.

**Comment by spikecodes** [comment]
Unfortunately, I don't see a way of doing this in a private and JavaScript-free fashion so I'll be closing this issue for now.

**Comment by TheCultLeader666** [comment]
This doesn't seem to be a problem for me, all the times match up with my local timezone, could you be using a fingerprint spoofer extension or the privacy.resistFingerprinting setting in Firefox, which would report UTC to make you less unique?

**Comment by Mennaruuk** [comment]
That's really interesting. I thought local time wasn't even a feature. May you please take a screenshot of the time when you hover over it? Does it end with UTC? You can blur out your time, I'm more interested in whether it ends with UTC.

**Comment by TheCultLeader666** [comment]
Sorry for the misunderstanding, thought you were talking about something else, but I can't find anywhere where I could hover to find the time?

**Comment by Mennaruuk** [comment]
Just hover over the time since a post or comment was made.
![image](https://user-images.githubusercontent.com/52135169/110807592-32224280-8251-11eb-85a4-e303b5bf876d.png)

**Comment by TheCultLeader666** [comment]
Ok, It says UTC on my end as well, sorry for the misunderstanding

**Comment by Mennaruuk** [comment]
No problem!
