### ISSUE TITLE
Feature Request | Ability to subscribe to r/all and/or r/popular

### ISSUE THREAD

**Issue by Mennaruuk** [spikecodes/libreddit#88]
**Is your feature request related to a problem? Please describe.**
I can't subscribe to r/all and r/popular. I understand they're not really subreddits, however, now that subscriptions have been implemented in Libreddit (thank you!), I can't visit r/all or r/popular without directly typing them in the address bar. This is important because often I like have this kind of container where I can access Libreddit without the influence of subreddits I've subscribed to, and r/all and r/popular provides a good solution for that problem.

**Describe the solution you'd like**
Having dedicated buttons for r/all and r/popular, Or, when I visit r/all or r/popular, there can be a subscribe button so I can subscribe to either.

**Describe alternatives you've considered**
Typing in the URL ([libredd.it/r/all](https://libredd.it/r/all)) or ([libredd.it/r/popular](https://libredd.it/r/popular)) solves this problem.

**Additional context**
CONGRATS!
![congrats](https://user-images.githubusercontent.com/52135169/106511944-f3091080-649e-11eb-8979-f1af3817f87b.gif)

**Comment by spikecodes** [comment]
:smile: Thank you Mennaruuk!

Do you want to have a subscription feed that contains posts from your subscriptions and posts from r/popular or r/all? If so, I see what you mean. It would be a useful feature to subscribe to those as well.

If you want to *only* see those in your front page, you can customize your front page in the settings, where you can set it to "Popular" (for r/popular) or "All" for (r/all).

Or do you want quick navigation buttons to switch between your subscription feed, r/popular and r/all?

**Comment by Mennaruuk** [comment]
The last request! I’m sure the first one would be pretty awesome (so it’d act more like a timeline where one can choose what to show based on what they subscribe to, and that would include r/all and r/popular). I think lots of duplicates would show up, though, would there be a way to prevent that?

But my request is for easier navigation to access each _individually_ (subscriptions, r/all, and r/popular).

**Comment by spikecodes** [comment]
Awesome, I know precisely what you mean! Reddit has a dropdown in the top left where you can select "Front page", "Popular", "All", or one of your subscriptions. I've added this to my to-do list.

**Comment by Mennaruuk** [comment]
Thanks a lot!!!!!!!!
I love the new wrench and code icons, they’re pretty:
![F94693DD-830E-4090-B4BD-41075AD47C19](https://user-images.githubusercontent.com/52135169/106520069-35841a80-64aa-11eb-864b-77a6303e2378.jpeg)

**Comment by spikecodes** [comment]
Just added this! 69941d9

![image](https://user-images.githubusercontent.com/19519553/106540952-ec0eec00-64f8-11eb-9c4f-558e2fca1199.png)
![image](https://user-images.githubusercontent.com/19519553/106540964-f03b0980-64f8-11eb-9093-885cc55e0dce.png)

**Comment by Mennaruuk** [comment]
THANK YOU!!!!!!!!!!!!!!!!!!  This is pure eye candy
![45219326-69E1-4EAC-98B7-4486188750B2](https://user-images.githubusercontent.com/52135169/106553073-97627580-64e6-11eb-8abb-bface4760926.jpeg)
