### ISSUE TITLE
Feature Request | generate URL to restore settings

### ISSUE THREAD

**Issue by B0pol** [spikecodes/libreddit#89]
**Is your feature request related to a problem? Please describe.**
If you clear cookies, settings are gone.

**Describe the solution you'd like**
I'd like to be able to get an URL that would restore settings.

**Describe alternatives you've considered**
Many other websites save settings with an account, but:
- I don't think you or libreddit users want accounts
- logging in is still longer than restore settings manually, whereas an URL bookmarked is really quick.

**Additional context**
teddit, searX, Bibliogram (and many probably many other websites) implemented this feature.
(actually not really for searX, it does not restore settings you can use this URL to search, but as soon as you change tab (images, news…) default settings are used).

**Comment by spikecodes** [comment]
Good idea, thanks!

**Comment by Mennaruuk** [comment]
One of the best things about this is if it'll be implemented is, once all instances get on board with such an update, I can basically change the URL to whatever instance and it'd preload all my settings. Wouldn't that be cool!? Better than going to each instance individually and "syncing" all the settings to match. Wonderful feature suggestion!
