### ISSUE TITLE
Sort is lost when paging.

### ISSUE THREAD

**Issue by Zegnat** [spikecodes/libreddit#9]
**Steps to reproduce:**

1. Visit any subreddit, e.g. [/r/news](https://libredd.it/r/news).
2. [Sort by "New"](https://libredd.it/r/news?sort=new).
3. Scroll to the end of the page and click NEXT.

**Result:** you end up on the page with a cursor in the URL but no more sort, thus ending up on an unspecified page of the subreddit when sorted by "Hot".

Example URL: `https://libredd.it/r/news?after=t3_kka1pr`.

**Expected:** the sort parameter is kept in the URL.

Example URL: `https://libredd.it/r/news?sort=new&after=t3_kka1pr`.

**Comment by spikecodes** [comment]
Thank you for the bug report! Fixed with bec5c78, updating the instances shortly

**Comment by Zegnat** [comment]
Awesome! :tada: 

I have been testing the libredd.it instance by automatically redirecting reddit links to it using a browser extension. Been holding up really nicely so far. Will report back if I bump into any other small bugs like this.

**Comment by spikecodes** [comment]
I love that idea! Yeah let me know if you encounter any other issues.
