### ISSUE TITLE
Bug Report | Thumbnail Size & Alignment on iOS

### ISSUE THREAD

**Issue by Mennaruuk** [spikecodes/libreddit#94]
**Describe the bug**
On Libreddit, there is no set thumbnail size. Some thumbnails appear tiny. Additionally, thumbnails don't align correctly.
![gif](https://user-images.githubusercontent.com/52135169/106700785-8d5a7880-65b3-11eb-938c-4804c6163b0f.gif)

I also think for the sake of consistency that, for videos, there should be a play button overlay. It'd save the black top and bottom, and also there would no longer be a need for captioning it **video**.
![makephotogallery net_1612328771921](https://user-images.githubusercontent.com/52135169/106700991-eb875b80-65b3-11eb-9497-9f64dd34d56e.jpg)

**To reproduce**
1. Visit r/popular
2. Check out thumbnail size
3. Also check out whether thumbnails are aligned

**Expected behavior**
Thumbnail size should remain consistent. Also, thumbnails should align.

**Additional context**
I deleted the Reddit app and clicked Add to Home Screen for Libreddit. Now it acts like its own app, isn't that cool?
![7FA446A1-5A43-4C4C-BD39-C6C0F6B5](https://user-images.githubusercontent.com/52135169/106701954-8cc2e180-65b5-11eb-9fd4-5696820bb07d.jpg)

**Comment by spikecodes** [comment]
Thanks for this bug report! It appears @robrobinbin has opened #92 to fix this thumbnail issue!

> I deleted the Reddit app and clicked Add to Home Screen for Libreddit. Now it acts like its own app, isn't that cool?

Totally, it's awesome! :smile: Big thanks to @JPyke3 for #83 which turns Libreddit into a PWA to allow this feature!

**Comment by Mennaruuk** [comment]
Wow, what a timing! **_THANK YOU ALL!!!_** All of these additions, big and small, matter.

**Comment by spikecodes** [comment]
Don't worry, you can keep this issue open until #92 is fixed! (@robrobinbin set it as a draft but when it's mergedf it will automatically close this issue)

**Comment by robrobinbin** [comment]
Hi @Mennaruuk!

Those tiny images are actually supposed to be full inline images, but Safari didn't like the way we did it :smile:

I fixed it in #92, which will be on your way shortly :tada: 

PS: If you prefer thumbnails instead of inline images, you can switch from card view to clean view in the settings.
