### ISSUE TITLE
Feature Request | Domain/Hostname Remapping in links

### ISSUE THREAD

**Issue by stranger-danger-zamu** [spikecodes/libreddit#96]
**Is your feature request related to a problem? Please describe.**
Whenever you encounter a link in the comments to something else in reddit (eg. linking to /r/cute), the link will probably take you to actual reddit. In other words, links to other posts or subreddits will link to actual reddit than to libreddit. 

**Describe the solution you'd like**
Replacing the host part of the URL with the configured libreddit URL. It'd be fine if this was even client side with some JS so that non-implemented portions of the libreddit could still link to reddit until page parity was reached.

**Describe alternatives you've considered**
The following worked and definitely can be improved through the efficient use of regex, but it's enough to make this work.
```javascript
Array.from(document.querySelectorAll('a[href]'))
    .filter(x=>{
        // filter to only links that come from `reddit.com` and point to `/r/<something>` 
        let url = new URL(x.href);
        return url.hostname.includes('reddit.com') && url.pathname.startsWith('/r/')
    })
    .map(x=>{
        // change the domain and the scheme to the instance values 
        let url = new URL(x.href); 
        url.hostname = "localhost:8080"; // aka domain
        url.protocol = 'http:';          // aka scheme
        x.href = url.toString(); 
        return x
    })
```

**Additional context**
Might be cool to extend this out to the other services like invidious for youtube and bibliogram for instagram, but that's probably a much bigger ask.

**Comment by spikecodes** [comment]
From what I can tell, this functionality has already been implemented under the [`rewrite_url` utility](https://github.com/spikecodes/libreddit/blob/master/src/utils.rs#L175-L178).

Example: https://libredd.it/r/findareddit/comments/lbvl1x/is_there_a_reddit_for_posting_whether_a_bill/glxh21x
Clicking the r/keep_track link brings the user to Libreddit instead of Reddit.

**Comment by stranger-danger-zamu** [comment]
It seems to only work on links that are either explicitly `www.reddit.com` or `reddit.com`. More than a few links I've seen so far have been `old.reddit.com` and a few `np.reddit.com`. Maybe grab all subdomains?

**Comment by spikecodes** [comment]
Good suggestion! All subdomains may include ones like `blog.reddit.com` but I've added `old.reddit.com` and `np.reddit.com`,
